### ISSUE TITLE
期待能出个使用说明

### ISSUE THREAD

**Issue by lllrrr** [kuoruan/luci-app-v2ray#1]
K大的luci-app-frp luci-app-v2ray，功能都很强大，自由度高，但对小白来说，有点不知道怎么使用。看那位大神能帮写个说明。谢谢

**Comment by kuoruan** [comment]
确实比较硬核，支持官方的所有配置项。
你可以和配置文件一一对应着来配置

https://www.v2ray.com/chapter_02/01_overview.html

**Comment by hcym** [comment]
比较晕核，一段一段的，有个范本就好照猫画虎了

**Comment by lllrrr** [comment]
我是完全蒙的。试了一下，用v2rayN的正常运行的config.json文件放到v2ray目录下，可以运行，但不能fanqiang

**Comment by kuoruan** [comment]
更新了一下默认的配置文件
在这里下载 https://github.com/kuoruan/luci-app-v2ray/releases/latest
默认带一个 socks 和 透明代理的入站连接配置

你需要自己添加或者修改自带的那个出站连接配置 ```upstream_vmess```。
如果你的服务端是 vmess 的话，修改配置里边的服务器 IP 就行了

路由里边的规则是用于国内直连和去广告的

**Comment by hcym** [comment]
谢谢谢谢，马上呈现

**Comment by lllrrr** [comment]
> 
> 
> 谢谢谢谢，马上呈现

你好，你配置成功了吗。例如我的服务器是a.domain.com 端口是8888 用的是KCP +utp协议，要怎么设置。请帮指点一下。

**Comment by hcym** [comment]
就是vems，最简单的改个地址，mkcp还没搞
