### ISSUE TITLE
有兼容OpenWrt 19.07.1的开发计划吗？

### ISSUE THREAD

**Issue by jklin1978** [kuoruan/luci-app-v2ray#101]
现在的版本不兼容OpenWrt 19.07.1

**Comment by adolink** [comment]
https://openwrt.org/releases/19.07/notes-19.07.1
官方known issues有说
LuCI web interface: some optional GUI packages crash with an error about missing “cbi.lua”, install the luci-compat package to fix these
安装luci-compat

**Comment by jklin1978** [comment]
测试了一下，好像不行。先安装的luci-app-v2ray，再安装luci-compat。回头，我再看看

**Comment by liuxiaochakan** [comment]
> 测试了一下，好像不行。先安装的luci-app-v2ray，再安装luci-compat。回头，我再看看

你那边装完有LuCI界面吗，我也是19.07.1，装完openwrt-v2ray、luci-app-v2ray后连界面都没有。不过我的是装在U盘，难道需要另外启动？
![image](https://user-images.githubusercontent.com/19406466/73911758-b9ceac80-48ed-11ea-81d5-cc29caec7d53.png)

**Comment by LongLights** [comment]
安装luci-conpat就可以使用了

**Comment by ykla** [comment]
安装了也不行，提示：
`ull_2.80-18_aarch64_cortex-a53.ipk
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/uci-defaults/50-dnsmasq-migrate-resolv-conf-auto.sh
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
        But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-v2ray.
root@OpenWrt:~#`

**Comment by ppseesea** [comment]
安装luci-compat就可以使用了。上面这些错误是说想安装dnsmasq-full，结果已经安装了dnsmasq了，把dnsmasq删除后安装dnsmasq-full就可以往下走了

**Comment by halfroad** [comment]
Adding the dependency 'luci-compat' to Makefile inside luci-app-v2ray,

LUCI_DEPENDS:=+jshn +luci-compat +luci-mod-admin-full +luci-lib-jsonc +ip + ipset +.....

luci-mod-admin-full may not be necessary.

when you "make menuconfig", please uncheck dnsmasq, and leave dnsmasq-full there.

**Comment by H0u5er** [comment]
看到标题表示很奇怪，我在 OpenWrt 19.07.2 下没遇到不兼容的问题，当前环境是群晖下启用VM安装OpenWrt 19.07.2

**Comment by zjufrankzhang** [comment]
同表示没碰到不兼容问题，LZ的问题是dnsmasq和dnsmasq-full冲突导致的
