### ISSUE TITLE
代理模式选择“直连cn”，部分国外网址无法访问，添加额外代理也没有用

### ISSUE THREAD

**Issue by LongLights** [kuoruan/luci-app-v2ray#102]
### 症状描述
在openwrt中安装本插件后，透明代理中选了“直连cn”并且更新了“APNIC 分配列表镜像”，随后测试可以访问谷歌，speedtest中显示的ip也是代理服务器的（图片下方显示的ip是google cloud platform的）。
![](https://www.ugediao.com/wp-content/uploads/2020/02/speedtest.png)

然后神奇的事情发生了，我发现我可以访问YouTube，但是不能播放视频（YouTube视频的链接貌似是googleviodes.com），将googlevideos.com加入额外代理列表重启v2服务也没有作用。

通过国内ipip.net查看到的ip是我的真实ip，通过myip.com查看到的ip是我代理服务器的ip，因此我觉得直连cn的模式的确是在工作了。

但之后我又发现了更多网址无法完成代理访问（比如p站可以访问，x站不行。。。）

### 贴上我的相关设置

插件设置中，dns、路由的启用选项都没有勾，“透明代理”的相关设置如下图：
![](https://www.ugediao.com/wp-content/uploads/2020/02/dokodemo-door.png)

wan口和lan口的dns都手动设置了8.8.8.8。

**Comment by LongLights** [comment]
再贴一下我的配置文件，直接从v2rayN导出加了一个inboundDetour字段（服务器信息那里不是真实的）

{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "debug"
  },
  "inboundDetour": [
    {
      "port": 1081,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp",
        "followRedirect": true
      }
    }
  ],
  "inbounds": [
    {
      "tag": "proxy",
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "www.baidu.com",
            "port": 443,
            "users": [
              {
                "id": "2e4cbce4-4b6c-458b-9291-312f5e803978",
                "alterId": 16,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "https://www.iqiyi.com"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/iqiyi.com",
          "headers": {
            "Host": "https://www.iqiyi.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,

  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}

**Comment by LongLights** [comment]
而且ssh上路由器，通过curl命令 所有网址都能获得正确的结果。。。

**Comment by NemoAlex** [comment]
+1 
Same here

**Comment by xun404** [comment]
+1 确实不生效

**Comment by LongLights** [comment]
放弃原版openwrt了，改用Lienol的固件使用passwall了，一切正常

**Comment by luminislight** [comment]
+1，同样的问题。但改成default能用。

**Comment by shenlijun** [comment]
抄这个设置一下就可以用https://toutyrater.github.io/app/tproxy.html

**Comment by kuoruan** [comment]
光设置直连 cn 不行，需要同时转发 dns，然后添加路由让对应的 dns 走代理。
dns 不配置无法正常解析
