### ISSUE TITLE
dns转发问题

### ISSUE THREAD

**Issue by Ben56** [kuoruan/luci-app-v2ray#104]
请问V2Ray - 透明代理菜单里的最下面代理列表 DNS和直连列表 DNS这两个是干嘛用的？和 转发dns功能冲突吗？如果 开启dns转发后这两个地方填写 dns服务器还管用吗？以哪个为准？我试了一下，如果只把dns转发功能打开后，好像没有把解析请求转发到v2ray内置的dns服务上，我测试的时候把facebook.com|7.7.7.7  添加到v2ray内置dns的静态列表中，然后测试的时候返回的不是7.7.7.7   我又把那个透明代理菜单中代理列表 DNS填写1.1.1.1#53  再测试就可以了，返回了7。7。7。7说明已经转发到内置dns上了，不理解是为什么，而且还有个奇怪的问题，就是如果把那个透明代理菜单中代理列表 DNS填写成114.114.114.114#53 再测试就又失败了，解析出来的不是7.7.7.7

**Comment by Ben56** [comment]
而且 代理模式选择“直连cn”， 转发 DNS 流量到 V2Ray好像也不能用

**Comment by Ben56** [comment]
代理列表 DNS和直连列表 DNS    和  dns转发   不冲突吗？以哪个为准？

**Comment by chnnnkk** [comment]
从生成的iptables规则看，转发DNS和直连CN冲突。直连CN的规则在转发DNS之前。意味着如果DNS服务器是国内地址，则不会将DNS请求转发给V2RAY
