### ISSUE TITLE
请教如何暂时停用luci-app-v2ray？

### ISSUE THREAD

**Issue by macdoor** [kuoruan/luci-app-v2ray#105]
为了调试各种场景，需要与没有启动 v2ray 时的情况对比，如何把OpenWRT的配置暂时恢复到没有启动 luci-app-v2ray 的配置，包括防火墙、dhcp 等的配置。
只是 service n2ray stop ，就所有都不通了。

**Comment by kuoruan** [comment]
```/etc/init.d/v2ray stop``` 这个不行吗？
