### ISSUE TITLE
Any recommended router ?

### ISSUE THREAD

**Issue by Limezy** [kuoruan/luci-app-v2ray#107]
Hi guys, I really want to have V2Ray working on a router because it's troublesome (and slow) to have a client on each device. Because I don't have a good router yet, I'm planning to buy one.
Do you have any recommendation about how to chose a good router for maximising V2Ray speed ? I guess the clock speed and RAM size are important ?

I am thinking of buying a Linksys WRT 1200AC because it looks powerful and compatible with OpenWRT. Anybody using this one or a similar one ?

Thanks in advance for your help,

**Comment by kuoruan** [comment]
It is recommend to build a x86 router, with a separate AP.

like: 3865U/3965U/E3845/J1900

**Comment by Limezy** [comment]
Hi, thanks for your answer ! What does explain this ? Better ability for the cipher / decipher operations than ARM based router ?

**Comment by zyfdegh** [comment]
I'm using an old device, Lenovo Newifi Y1, with only 16MB nand & 128MB memory, but it works well.

**Comment by Limezy** [comment]
I have bought a 3205U router, sufficient for my needs. Thanks !
