### ISSUE TITLE
How to configure V2ray in Lucci

### ISSUE THREAD

**Issue by bigleooo** [kuoruan/luci-app-v2ray#108]
Hi, 

I've already set up my v2ray server and been running it smoothly with the Mac OS "V2RayX 2" APP, and it work wonders, I'm able to access the outside world. I only had to input the:
address, port, userid, alterid, and bam was working.

I've also already set up v2ray on my OpenWrt router.
<img width="1440" alt="Screen Shot 2020-02-26 at 3 10 03 AM" src="https://user-images.githubusercontent.com/13649913/75278845-93919200-5845-11ea-901f-17e3babb6568.png">
The problem I find is that its a bit complicated on the router? its not as easy as just inputing the above as I did in the Mac OS APP.
Can someone guide me as to where to input the details as the above and which settings I have to configure to get it working. There are a lot of settings.

Thanks

**Comment by kuoruan** [comment]
See: https://www.v2ray.com/en/configuration/overview.html

**Comment by Limezy** [comment]
Same here, sorry to bother but I don't understand how I should configure my inbounds ?
Outbounds are pretty clear but for inbounds I'm totally lost.
Thanks !

**Comment by chinaxmj** [comment]
我与楼主问题一样，配置界面完全蒙圈了，求高手指点

**Comment by Limezy** [comment]
I managed to get it working. You need to :
1. Setup a dokodemo door in your inbounds, listening to 0.0.0.0, with a random port (I use 10800), sniffing enabled and dest override http + tls
2. Setup the "Transparent Proxy" tab by choosing your dokodemo door as redirect port, bridge it to the lan interface
3. Setup your outbounds as usual

What took me time to understand is the chain of how it works. Here is a schematic of what I've understood (I'm using a soft X86 router) : 
House <- Wifi AP -> Transparent Proxy <- V2ray inbound (Dokodemo door) -> V2ray core of router (including routing if you setup some) <- V2ray outbound (Vmess or other) -> V2ray core of VPS <- Freedom outbound -> Outside world

I still have a few questions, one of them is about the routing.
Looks like the routing China direct / Others V2ray could be partially done at the Transparent Proxy layer or at the V2ray routing layer.
Is there any benefit of doing it at Transparent proxy layer ?

**Comment by geekmichael** [comment]
Works for me when the Proxy mode is Default, but not GFWList Proxy.
