### ISSUE TITLE
期待加入ip6tables规则创建

### ISSUE THREAD

**Issue by shenlijun** [kuoruan/luci-app-v2ray#109]
目前透明代理好像之支持ipv4

**Comment by kuoruan** [comment]
一般路由器使用的时候会同时分配 ipv4 和 ipv6 地址，所以路由端可以不配置 ip6tables 规则，想使用 ipv6 的话可以先直接填 ipv6 的服务器地址

**Comment by shenlijun** [comment]
> 一般路由器使用的时候会同时分配 ipv4 和 ipv6 地址，所以路由端可以不配置 ip6tables 规则，想使用 ipv6 的话可以先直接填 ipv6 的服务器地址

同样的域名我的dns解析v4和v6都有，出站是一个vmess，在ipv6-test.com测试的时候显示ipv6没有走v2ray代理，是需要其他什么样的设置么？分两个vmess？

**Comment by shenlijun** [comment]
> 一般路由器使用的时候会同时分配 ipv4 和 ipv6 地址，所以路由端可以不配置 ip6tables 规则，想使用 ipv6 的话可以先直接填 ipv6 的服务器地址

ping6 google.com, 现在是不通的

**Comment by kuoruan** [comment]
ICMP 协议没有代理，所以肯定是 ping 不通的，可以直接访问 ipv6.google.com

**Comment by shenlijun** [comment]
> ICMP 协议没有代理，所以肯定是 ping 不通的，可以直接访问 ipv6.google.com

确实可以的
