### ISSUE TITLE
不是很明白要怎么用这个界面，以及设置outbound时遇到的问题

### ISSUE THREAD

**Issue by chenyc1995** [kuoruan/luci-app-v2ray#11]
我使用websocks连接，每当我在outbound标签下输入
`"path": "/PATH"`
就会自动变成
`"path": "\/PATH"`

另外期待能给出一个模板，luci界面有点令人摸不着头脑。

**Comment by kuoruan** [comment]
related to #6 
直接看默认的配置就好了，常见的都有样例，启动后看“关于”里的配置文件

**Comment by hcym** [comment]
请教大大，配置好一切正常，确实强大确实硬核。但是把关于里面的复制成自定义就不能用，只有国内cn的可以。

**Comment by kuoruan** [comment]
@hcym 没明白你的意思，是把配置文件拷贝成文件使用吗？

**Comment by hcym** [comment]
是的，指定上传文件，国外的不行国内的正常，广告标签也正常。所以纳闷呢

**Comment by kuoruan** [comment]
手动指定上传文件的话，需要自己添加透明代理规则

**Comment by hcym** [comment]
哦，学习了，谢谢指教

**Comment by wenjacky** [comment]
> 手动指定上传文件的话，需要自己添加透明代理规则

怎么添加透明代理规则，规则的内容是什么？

**Comment by kuoruan** [comment]
@wenjacky 
https://github.com/kuoruan/luci-app-v2ray/blob/master/root/etc/init.d/v2ray#L200

**Comment by hcym** [comment]
好的，谢谢，我再看看能不能用硬核桃

**Comment by wenjacky** [comment]
> @wenjacky
> https://github.com/kuoruan/luci-app-v2ray/blob/master/root/etc/init.d/v2ray#L200

好的，谢谢。自己找到了已经。脚本写的不错，赞！

**Comment by crackself** [comment]
@wenjacky @kuoruan 请教，用域名+ws链接时无法保持域名到出站vmess设置（提示要ip）。上传配置后可以在浏览器指定proxy接入。手动配置iptable透明代理时终端执行“add_v2ray_rules()”这段，设置失败，能否给个实例，感谢！
