### ISSUE TITLE
openwrt-luci-app-v2ray 图形界面如何配置？

### ISSUE THREAD

**Issue by chinaxmj** [kuoruan/luci-app-v2ray#110]
按网上教程编译了最新原版openwrt v.19.07.2固件，刷入机器内。需要实现科学上网，又安装了 luci-app-v2ray_1.5.3-1_all.ipk & v2ray-core_4.22.1-4_x86_64.ipk & luci-i18n-v2ray-zh-cn_1.5.3-1_all.ipk，这3个ipk，安装过程提示缺少几个依赖包，各种折腾终于在路由器上成功安装了v2ray。

现在问题是luci-app-v2ray配置界面太复杂，与电脑端的v2rayN.exe和手机端的v2rayNG.app配置完全不一样，“全局设置/入站连接/出站连接/DNS/路由/策略/反向代理/透明代理”这些内容不知道怎样填写，全局模式/PAC模式/订阅也都没有，https://www.v2ray.com/chapter_02/ 官方教程也看过，说的都是config.json文件配置，与luci-app-v2ray图形配置还是不一样，现在完全蒙圈了，希望看到的高手给予指点。
![微信图片_20200301113257](https://user-images.githubusercontent.com/25171342/75618977-80b5ef00-5bb0-11ea-9728-9cd989eff861.png)
![微信图片_20200301110014](https://user-images.githubusercontent.com/25171342/75618980-8f040b00-5bb0-11ea-88dc-aeeae76e9c7d.png)

**Comment by chinaxmj** [comment]
配置截图
![20200301114155](https://user-images.githubusercontent.com/25171342/75619138-eefbb100-5bb2-11ea-8543-13fff9e44b80.png)
![20200301114131](https://user-images.githubusercontent.com/25171342/75619139-f02cde00-5bb2-11ea-8c37-55c4b163d426.png)
![20200301114104](https://user-images.githubusercontent.com/25171342/75619140-f0c57480-5bb2-11ea-97fa-997cc8583420.png)
![20200301114032](https://user-images.githubusercontent.com/25171342/75619141-f15e0b00-5bb2-11ea-826c-ed54c51b2a5e.png)
![20200301113958](https://user-images.githubusercontent.com/25171342/75619142-f15e0b00-5bb2-11ea-9aa2-d7c9dfd183bc.png)
![20200301113922](https://user-images.githubusercontent.com/25171342/75619143-f1f6a180-5bb2-11ea-9c80-97311bc09077.png)
![20200301113834](https://user-images.githubusercontent.com/25171342/75619144-f28f3800-5bb2-11ea-8f86-d8e229f8db9e.png)
![20200301113658](https://user-images.githubusercontent.com/25171342/75619145-f327ce80-5bb2-11ea-8fa9-a2705113e53f.png)

**Comment by cp315** [comment]
防火墙里边把1081加进去

**Comment by jdx805** [comment]
> 防火墙里边把1081加进去
> 出站把你的鸡场vmess链接加进去，并且保证鸡场可用
> 全局出站勾选的的鸡场，只勾选可用的鸡场。
> 全局入站只勾选dokodemo_door，除非透明代理启用1080，并且防火墙把1080也加上。

大哥,首页有个v2ray file怎么填?

**Comment by cp315** [comment]
> > 防火墙里边把1081加进去
> > 出站把你的鸡场vmess链接加进去，并且保证鸡场可用
> > 全局出站勾选的的鸡场，只勾选可用的鸡场。
> > 全局入站只勾选dokodemo_door，除非透明代理启用1080，并且防火墙把1080也加上。
> 
> 大哥,首页有个v2ray file怎么填?

其他都默认不要改

**Comment by zjzb** [comment]
我也是菜鸟，用了作者的luci，费了好大力气终于用起来了，很多名词我也不懂，我写了一篇简单的配置教程，方便菜鸟吧，有可能我里面说的都不是很对，但是真的用起来了，我要谢谢作者的无私奉献，一下是我博客文章地址：http://loonlog.com/2020/3/13/v2ray-for-openwrt-config/   如果作者认为我这是个广告，可以提醒我删除。

**Comment by tpaullee** [comment]
That has a lot of screenshots and annotations.Thanks for your effort and good work.I bookmark it for future use if I have to re-create another v2ray-capable router.
TPL
N 37-17.454 W 121-57.679 http://tpaullee.blogspot.com/ Cultivating Human Goodness 

    On Friday, March 13, 2020, 08:09:34 AM PDT, zjzb <notifications@github.com> wrote:  
 
 


我也是菜鸟，用了作者的luci，费了好大力气终于用起来了，很多名词我也不懂，我写了一篇简单的配置教程，方便菜鸟吧，有可能我里面说的都不是很对，但是真的用起来了，我要谢谢作者的无私奉献，一下是我博客文章地址：http://loonlog.com/2020/3/13/v2ray-for-openwrt-config/ 如果作者认为我这是个广告，可以提醒我删除。

**Comment by AlexYe233** [comment]
刚配置完 仅代理GFWList
只要配置好 入站连接 出站连接 和 透明代理 即可，dns 路由 策略 反向代理 等等无需开启，防火墙也无需额外设置
入站连接：需要保证 dokodemo_door协议 监听路由器lan口ip(如192.168.1.1，或0.0.0.0)，只监听127.0.0.1无效
出站连接：需要确认出站连接有效性
透明代理：
先在ssh执行opkg install libustream-openssl20150806 安装透明代理所需的libustream-openssl
再点击更新GFWList
设置成如图即可
![捕获](https://user-images.githubusercontent.com/34712118/76700693-1f843480-66f5-11ea-8f0e-84a57dbf69e5.PNG)

**Comment by chinaxmj** [comment]
收到 感谢


 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AlexYe233"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月15日(星期天) 晚上7:43
收件人:&nbsp;"kuoruan/luci-app-v2ray"<luci-app-v2ray@noreply.github.com&gt;;
抄送:&nbsp;"辛明-17701325709"<43450301@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [kuoruan/luci-app-v2ray] openwrt-luci-app-v2ray 图形界面如何配置？ (#110)





 
刚配置完 仅代理GFWList
 只要配置好 入站连接 出站连接 和 透明代理 即可，dns 路由 策略 反向代理 等等无需开启，防火墙也无需额外设置
 入站连接：需要保证 dokodemo_door协议 监听路由器lan口ip(如192.168.1.1，或0.0.0.0)，只监听127.0.0.1无效
 出站连接：需要确认出站连接有效性
 透明代理：
 先在ssh执行opkg install libustream-openssl20150806 安装透明代理所需的libustream-openssl
 再点击更新GFWList
 设置成如图即可

**Comment by chinaxmj** [comment]
收到 感谢







 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"T.Paul Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月14日(星期六) 上午6:25
收件人:&nbsp;"kuoruan/luci-app-v2ray"<luci-app-v2ray@noreply.github.com&gt;;
抄送:&nbsp;"辛明-17701325709"<43450301@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [kuoruan/luci-app-v2ray] openwrt-luci-app-v2ray 图形界面如何配置？ (#110)





 That has a lot of screenshots and annotations.Thanks for your effort and good work.I bookmark it for future use if I have to re-create another v2ray-capable router.
 TPL
 N 37-17.454 W 121-57.679 http://tpaullee.blogspot.com/ Cultivating Human Goodness 
 
     On Friday, March 13, 2020, 08:09:34 AM PDT, zjzb <notifications@github.com&gt; wrote:  
  
  
 
 
 我也是菜鸟，用了作者的luci，费了好大力气终于用起来了，很多名词我也不懂，我写了一篇简单的配置教程，方便菜鸟吧，有可能我里面说的都不是很对，但是真的用起来了，我要谢谢作者的无私奉献，一下是我博客文章地址：http://loonlog.com/2020/3/13/v2ray-for-openwrt-config/ 如果作者认为我这是个广告，可以提醒我删除。

**Comment by chinaxmj** [comment]
收到 感谢


 时间：2020年6月9-11日&nbsp; &nbsp;地址：北京-中国国际展览中心
 ———————————————————————————
 联系主办方
电&nbsp; &nbsp;话：+86-10-8620 9998
 联系人：辛 明 17701325709
 E-mail：43450301@qq.com


 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zjzb"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 晚上11:09
收件人:&nbsp;"kuoruan/luci-app-v2ray"<luci-app-v2ray@noreply.github.com&gt;;
抄送:&nbsp;"辛明-17701325709"<43450301@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [kuoruan/luci-app-v2ray] openwrt-luci-app-v2ray 图形界面如何配置？ (#110)





 
我也是菜鸟，用了作者的luci，费了好大力气终于用起来了，很多名词我也不懂，我写了一篇简单的配置教程，方便菜鸟吧，有可能我里面说的都不是很对，但是真的用起来了，我要谢谢作者的无私奉献，一下是我博客文章地址：http://loonlog.com/2020/3/13/v2ray-for-openwrt-config/   如果作者认为我这是个广告，可以提醒我删除。

**Comment by kellandJuniper** [comment]
@AlexYe233 按你描述的配置，奇怪，在远端服务器上可以看到来自本地的请求，但是所有链接都自动加上1081，如访问推特在服务端看后台记录，访问地址变为：`twitter.com:1081`

记录如下：
`2022/12/07 12:28:47 [Warning] [2530733544] app/dispatcher: default route for tcp:twitter.com:1081`

更详细记录： #463
