### ISSUE TITLE
请教v2ray路由下 设备 直连

### ISSUE THREAD

**Issue by 007learner** [kuoruan/luci-app-v2ray#111]
请教关于v2ray路由下，特定设备直接代理，特定设备直联的设置方法。

openwrt路由下使用v2ray core和luci-app-v2ray，访问网站国内外分流基本识别正确.
但是路由下的特定设备， google home想要设置全局代理 ，  PT下载设备全局直连，应该怎么设置。
望各位大佬指教，谢谢。

**Comment by halfroad** [comment]
在透明代理找到额外的代理和额外的直连。输入目标设备的ip地址

**Comment by 007learner** [comment]
> 在透明代理找到额外的代理和额外的直连。输入目标设备的ip地址
谢谢答复，我试了这个方法，但是不起作用。你按照这个配置是可用的吗？

**Comment by emacsnt** [comment]
在route ojbect里面不是有一个direct_bt，主要是根据协议判定，如果是bittorrent协议，就direct了

**Comment by 007learner** [comment]
> 在route ojbect里面不是有一个direct_bt，主要是根据协议判定，如果是bittorrent协议，就direct了

照理来说PT是bittorrent协议的，但是我这边设置后并没有正确区分，没有实现直连，tracker和端口也都是有问题的。你有实际配置 操作是可用的吗？
