### ISSUE TITLE
安装dnsmasq-full时出现以下的问题

### ISSUE THREAD

**Issue by TodayNow** [kuoruan/luci-app-v2ray#113]
udhcpc: started, v1.30.1
udhcpc: sending discover
udhcpc: no lease, failing
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc/config/dhcp-opkg

斐讯k2

**Comment by halfroad** [comment]
To replace the dhcp, please issue the directive: mv /etc/config/dhcp-opkg /etc/config/dhcp

I encounter this problem yesterday.

**Comment by kuoruan** [comment]
This means the config file from the new package (maybe update package) is different from yours.
Just ignore this.
