### ISSUE TITLE
balancerTag: is missed from routing object 

### ISSUE THREAD

**Issue by emacsnt** [kuoruan/luci-app-v2ray#115]
it seems missing balancerTag field in luci  rule object editing view. so can not add BalancerObject to RoutingObject

**Comment by kuoruan** [comment]
as the official docs says:  When ```outboundTag``` and ```balancerTag``` are specified, ```outboundTag``` takes priority.

so the balancerTag is hide when outboundTag is specified.

https://www.v2ray.com/en/configuration/routing.html#ruleobject

**Comment by emacsnt** [comment]
Got it. The balancerTag is hidden. this feature is cool, thanks.
