### ISSUE TITLE
1.5.4-1的语言文件与openwrt18.06.8的luci-i18n-base-zh-cn冲突？

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/luci-app-v2ray#118]
1.5.4-1的中文文件，似乎与18.06.8的luci-i18n-base-zh-cn有什么冲突，安装后整个LUCI的中文消失。
因为不是什么大问题，就随手把luci-i18n-v2ray-zh-cn删了，因此提供不了更多信息。

**Comment by kuoruan** [comment]
无法重现
