### ISSUE TITLE
can not build on the master branch

### ISSUE THREAD

**Issue by moralrebuild** [kuoruan/luci-app-v2ray#12]
Hope this project and its v2ray-core sister one have been fully ported and validated on both the latest official release (v18.06.4) and certainly the master branch. But obviously this is not the case so far:
```
./scripts/feeds install -a
WARNING: Makefile 'package/luci-app-v2ray/Makefile' has a dependency on 'luci-lib-jsonc', which does not exist
WARNING: Makefile 'package/luci-app-v2ray/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/luci-app-v2ray/Makefile' has a build dependency on 'csstidy/host', which does not exist
...
WARNING: Makefile 'package/v2ray-core/Makefile' has a build dependency on 'golang/host', which does not exist
```

**Comment by kuoruan** [comment]
Download and install OpenWrt feeds first.

**Comment by moralrebuild** [comment]
I began to build openWrt half decade before. Any indeed I had already downloaded everything.  Could you please point me which feed got missed?

**Comment by kuoruan** [comment]
Follow https://openwrt.org/docs/guide-developer/using_the_sdk
```
./scripts/feeds update -a
./scripts/feeds install -a
```

**Comment by moralrebuild** [comment]
That's basic step sir. Please take a look at my original issue report. It was from command: ./scripts/feeds install -a

**Comment by kuoruan** [comment]
Make sure there are luci and  package feeds in your ```feeds.conf``` or ```feeds.conf.default```

like:
```
src-git packages https://git.openwrt.org/feed/packages.git
src-git luci https://git.openwrt.org/project/luci.git
```

**Comment by kuoruan** [comment]
My releases are build from 18.06.4, no errors.

see https://github.com/kuoruan/luci-app-v2ray/blob/master/.travis.yml#L51-L62

**Comment by moralrebuild** [comment]
How about the error:
```
WARNING: Makefile 'package/v2ray-core/Makefile' has a build dependency on 'golang/host', which does not exist
```
This fatal issue affects both official build 18.06.4 and latest master branch. 

B.T.W. yesterday and today, after deselecting your two v2ray projects, I've just successfully built every custom packages including v2ray-plugin which used for shadowsocks-libev.

**Comment by moralrebuild** [comment]
> 
> 
> My releases are build from 18.06.4, no errors.
> 
> see https://github.com/kuoruan/luci-app-v2ray/blob/master/.travis.yml#L51-L62

That's great. Please help to share the exact step that other can follow. I think we all can benefit from it.

**Comment by kuoruan** [comment]
Compare the build log with your's:

https://travis-ci.org/kuoruan/openwrt-v2ray/jobs/559755335
