### ISSUE TITLE
导入 vmess:// 格式链接的时候 TLS - Server name 为空

### ISSUE THREAD

**Issue by zhangjint5** [kuoruan/luci-app-v2ray#120]
vmess 链接导入时，发现 TLS - Server name 项目为空！正常的话，此项目应该与中 http head 中 host 的值相同吧！建议默认将其设置上！

**Comment by kuoruan** [comment]
https://www.v2ray.com/chapter_02/05_transport.html#tlsobject

serverName 默认可以不填，会自动通过证书获取

**Comment by kuoruan** [comment]
而且按链接定义来说，并不存在 serverName 字段

https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

**Comment by zhangjint5** [comment]
> serverName 默认可以不填，会自动通过证书获取

这个 serverName 对应的是 TLS 的 SNI 信息！是客户端发出 https 请求中携带的信息，不是客户端能自动通过证书获取的！！！

如果假定 wss 服务器443端口上仅仅只有一个缺省站点，这种情况是可以不填 SNI 的，serverName 为空也没事！你感觉的“会自动通过证书获取”应该就是这种情况！

但是如果 wss 服务器443端口上有多个站点的时候，就得靠 SNI 来区分！例如在套 cloudflare 的时候！或者有 nginx 前端并配置有多证书多站点的时候！

这个 serverName 还是非常重要有必要设上的！

**Comment by zhangjint5** [comment]
> 而且按链接定义来说，并不存在 serverName 字段
> 
> https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

虽然 vmess 没有 serverName 字段，但是 v2rayN 软件在实际发出 wss 请求的时候，把 host 字段值作为 TLS SNI 信息发送了！所以并不需要在 vmess 链接中有 serverName 字段也能正常工作！

问题是，客户端发出 ws 请求的时候，有 http host 头没问题
但是如果客户端发出 wss 请求，不光需要 host 头，还需要 SNI （也就是serverName），否则在服务器多站点的时候就会有问题。
