### ISSUE TITLE
luci-i18n-v2ray-zh-cn如何编译进固件？

### ISSUE THREAD

**Issue by shmily103** [kuoruan/luci-app-v2ray#121]
luci-i18n-v2ray-zh-cn如何编译进固件？

**Comment by kuoruan** [comment]
在编译界面选择 LuCI 简体中文之后会自动编译进固件

**Comment by shmily103** [comment]
已经选了中文，就是不会编译进固件，wrt1900acs

**Comment by kuoruan** [comment]
最新源码吗？

应该是新版改名了，现在叫 zh_Hans

你把 po 下的 zh-cn 目录改为 zh_Hans

**Comment by shmily103** [comment]
好的，谢谢大佬。
