### ISSUE TITLE
Crash after few minutes of working

### ISSUE THREAD

**Issue by amirmt71** [kuoruan/luci-app-v2ray#122]
Hi
Im on Raspberry Pi 3 B+ (Cortex_a53), running OpenWrt 19.07.2
Is it fully compatible with my implementation?
I have installed the last versions, and it seem to work. I need to send DNS requests through proxy, so I should enable UDP transparent proxy and if I don't, I cannot access censored websites.

But after a few minutes, it crashes. By watching the logs, I noticed that it fails to correctly route the traffic. I wonder why everything is fine in the first minutes and then crashes.

I tried to keep my confguration as simple as possible. No special routing rules, No nothing. I just want to tunnel all the traffic (udp/tcp) through transparent proxy and it fails.

So do you think this is my fault with mis-configuration or there is some bug with my hardware/software?

OpenWRT 19.07.2
Raspberry Pie 3 B + (cortex A53)

**Comment by kuoruan** [comment]
Crash? Is the process exit? lack of CPU or memory?

need your config file and error log.

**Comment by amirmt71** [comment]
Thanks for the fast reply.
No, process (seems) ok, but fails to find the outband. I think it is a routing problem. Log constantly says fail to connect to outband, but if I restart the service, it comes back to normal.

assume:
outband: "server.com" / ws/
inband: default transparent
transparent: only on wireless interface, UDP enable, no custom rules
routing: one rule, all udp/tcp/http/tls, outband tag: proxy
(tried dns_out, dns_proxy enable disable anycombination what ever, no difference)
DNS: enable/disable no difference.

logs: totally clear for few minutes, and everything is superb
then after few minutes, constantly saying: fails to find "server.com"

I will send the files, I dont have right now.
thanks!

**Comment by tpaullee** [comment]
Amir,Good to know there are people like me doing OpenWRT+v2ray on a Raspberry PI.Any special group or mailing list I should sign up to learn from?I also hope that you can resolve your "crash" problem with PI 3 B+ model soon.
Best Regards,T.Paul  

    On Friday, April 3, 2020, 07:40:32 AM PDT, amirmt71 <notifications@github.com> wrote:  
 
 


Hi
Im on Raspberry Pi 3 B+ (Cortex_a53), running OpenWrt 19.07.2
Is it fully compatible with my implementation?
I have installed the last versions, and it seem to work. I need to send DNS requests through proxy, so I should enable UDP transparent proxy and if I don't, I cannot access censored websites.

But after a few minutes, it crashes. By watching the logs, I noticed that it fails to correctly route the traffic. I wonder why everything is fine in the first minutes and then crashes.

I tried to keep my confguration as simple as possible. No special routing rules, No nothing. I just want to tunnel all the traffic (udp/tcp) through transparent proxy and it fails.

So do you think this is my fault with mis-configuration or there is some bug with my hardware/software?

OpenWRT 19.07.2
Raspberry Pie 3 B + (cortex A53)

**Comment by amirmt71** [comment]
Hi 
here is my conf:

`
{
	"log": {
		"access": "/dev/null",
		"loglevel": "warning",
		"error": "/var/log/v2ray-error.log"
	},
	"dns": {
		"servers": [
			"8.8.8.8",
			{
				"address": "208.67.222.222",
				"port": 5353
			},
			{
				"address": "114.114.114.114",
				"port": 53
			},
			"4.2.2.2"
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand"
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1080,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true,
				"ip": "127.0.0.1"
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		},
		{
			"port": 1081,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp,udp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "redirect"
				}
			},
			"tag": "transparent",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"allocate": {
				"strategy": "always"
			}
		}
	],
	"outbounds": [
		{
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "server.com",
						"port": 443,
						"users": [
							{
								"id": "*****",
								"alterId": 233
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"tlsSettings": {
					"allowInsecure": false,
					"allowInsecureCiphers": false,
					"disableSystemRoot": false,
					"certificates": [
						
					]
				},
				"wsSettings": {
					"path": "/"
				},
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "proxy"
		}
	]
}
`

And this is the log file:

[v2ray-error.log](https://github.com/kuoruan/luci-app-v2ray/files/4434710/v2ray-error.log)


it worked for almost 3 minutes and then failed to work, continuously repeating that log.

@tpaullee  Hi Paul, I haven't found any groups up to now.
so we could create a telegram group :)

**Comment by tpaullee** [comment]
>> @tpaullee Hi Paul, I haven't found any groups up to now.
so we could create a telegram group :)

Will be happy to join. Anyone else is welcome too. My fictitious user name there is @SueJackson.
I did some very rudimentary setup with this in January on a inexpensive router (Newifi3) and thus joined this group.
My github user name you used is all right to use.

T.Paul


     On Sunday, April 5, 2020, 01:17:39 PM PDT, amirmt71 <notifications@github.com> wrote:  
 
 


Hi
here is my conf:

`
{
"log": {
"access": "/dev/null",
"loglevel": "warning",
"error": "/var/log/v2ray-error.log"
},
"dns": {
"servers": [
"8.8.8.8",
{
"address": "208.67.222.222",
"port": 5353
},
{
"address": "114.114.114.114",
"port": 53
},
"4.2.2.2"
]
},
"routing": {
"domainStrategy": "IPOnDemand"
},
"inbounds": [
{
"listen": "0.0.0.0",
"port": 1080,
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true,
"ip": "127.0.0.1"
},
"streamSettings": {
"sockopt": {
			}		},		"sniffing": {			"enabled": true,			"destOverride": [				"http",				"tls"			]		}	},	{		"port": 1081,		"protocol": "dokodemo-door",		"settings": {			"followRedirect": true,			"network": "tcp,udp"		},		"streamSettings": {			"sockopt": {				"tproxy": "redirect"			}		},		"tag": "transparent",		"sniffing": {			"enabled": true,			"destOverride": [				"http",				"tls"			]		},		"allocate": {			"strategy": "always"		}	}],"outbounds": [	{		"protocol": "vmess",		"settings": {			"vnext": [				{					"address": "server.com",					"port": 443,					"users": [						{							"id": "*****",							"alterId": 233						}					]				}			]		},		"streamSettings": {			"network": "ws",			"security": "tls",			"tlsSettings": {				"allowInsecure": false,				"allowInsecureCiphers": false,				"disableSystemRoot": false,				"certificates": [									]			},			"wsSettings": {				"path": "/"			},			"sockopt": {				"mark": 255			}		},		"tag": "proxy"	}]
}
`

And this is the log file:

v2ray-error.log

it worked for almost 3 minutes and then failed to work, continuously repeating that log.

@tpaullee Hi Paul, I haven't found any groups up to now.
so we could create a telegram group :)

**Comment by amirmt71** [comment]
I think there is an infinite routing loop when I enable UDP in transparent proxy. It seems a little complicated and common issue with iptables rules:
look at he UDP section [here](https://xdays.me/V2RAY%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86/)
and [here ](https://github.com/v2ray/v2ray-core/issues/1671)

I believe this is an iptables miss-configuration error that causes the infinite loop while enabling the UDP. this [link ](https://xdays.me/V2RAY%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86/) seems has a solution for it. Im not sure.

**Comment by kuoruan** [comment]
use ```resolveip YOUR_SERVER_ADDR``` to see if the router can get the remote ip address?

and the ip addresses should in ```ipset list v2ray_dst_direct_v4```

**Comment by amirmt71** [comment]
@kuoruan 
Before the loop (crash) happen:
the ` resolveip YOUR_SERVER_ADDR` returns the IP of the server
ip addresses are available in ipset list 'v2ray_dst_direct_v4'

After the loop (crash):
the ` resolveip YOUR_SERVER_ADDR` returns nothing
ip addresses are still available in ipset list 'v2ray_dst_direct_v4'

**Comment by kuoruan** [comment]
Does your server behind a CDN?

Try add a TLS serverName? #120

**Comment by kuoruan** [comment]
I notice that there is no routing rules in your config.
You need some rules to direct or proxy your dns ip address you use.

**Comment by amirmt71** [comment]
> Does your server behind a CDN?
> 
> Try add a TLS serverName? #120

what is the TLS serverName format?
I tried this but with no difference: 

`
"network": "ws",
				"security": "tls",
				"tlsSettings": {
					"serverName": "server.com",
					"allowInsecure": false,
					"allowInsecureCiphers": false,
					"disableSystemRoot": false,
					"certificates": [
						
					]
				},
				"wsSettings": {
					"path": "/",
					"headers": {
						"Host": "server.com"
`

Resulted in no difference.
-------------
There is no need to add a route for DNS if enabling `Redirect UDP`, because it routes everything from every port through proxy. But I enabled the default dns_proxy rule which includes my DNS servers and still no difference.

**Comment by kuoruan** [comment]
1. Your router wants to get your server address, send a dns request to default dns server.
2. The dns request(UDP) will be redirect to your V2Ray if ```Redirect DNS``` or ```Redirect UDP``` is enabled.
3. V2Ray use route to find which outbound to pass the dns request.

If you only have a proxy outbound, your V2ray can't get your server ip.

So you need:

1. Add a direct outbound;

2. Add a routing rule for your default DNS ip, need to pass through direct outbound.

**Comment by amirmt71** [comment]
> 1. Your router wants to get your server address, send a dns request to default dns server.
> 2. The dns request(UDP) will be redirect to your V2Ray if `Redirect DNS` or `Redirect UDP` is enabled.
> 3. V2Ray use route to find which outbound to pass the dns request.
> 
> If you only have a proxy outbound, your V2ray can't get your server ip.
> 
> So you need:
> 
> 1. Add a direct outbound;
> 2. Add a routing rule for your default DNS ip, need to pass through direct outbound.

Correct. But:
If I do so, all the DNS requests including the DNS requests from the clients connected to the router, goes to direct outbound. How should I prevent this?

**Comment by kuoruan** [comment]
https://www.v2ray.com/chapter_02/03_routing.html#ruleobject

route only your server name with direct outbound.

**Comment by kuoruan** [comment]
And add a dns rule for your server name.

https://www.v2ray.com/chapter_02/04_dns.html#dnsobject

Also, the dns ip should go through direct outbound.

**Comment by amirmt71** [comment]
now happened this:
failed to lookup server.com 127.0.0.1:53: read udp 127.0.0.1:47521->127.0.0.1:53: i/o timeout 
I defined static domain ->IP in both v2ray DNS and DNS forwarding of OpenWRT, but doesnt work.

v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://server.com/):  > dial tcp: lookup server.com on 127.0.0.1:53: read udp 127.0.0.1:37794->127.0.0.1:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket

**Comment by kuoruan** [comment]
paste your config file here.

**Comment by amirmt71** [comment]
Problem solved in the newest update, and newest default routing Rules.
Using UDP redirect is now safe.
I also added a static Host in DNS objects (using luci interface) to my Server, but it seems not needed. 

Thank you for your accompany.
