### ISSUE TITLE
Multiple outbounds, how to route?

### ISSUE THREAD

**Issue by Tualua** [kuoruan/luci-app-v2ray#123]
Hello! Now I have one outbound and transparent proxy (tcp and udp), everything is working fine.
I have setup additional dokodemo inbound for openvpn client (openvpn client on device connects to local address and port and connection is forwarded to openvpn server).

However, I would like to make 2 outbounds, one use for all traffic except that dokodemo I created for openvpn. 

Is it possible?

**Comment by kuoruan** [comment]
See https://www.v2ray.com/chapter_02/03_routing.html#ruleobject
