### ISSUE TITLE
fatal error: failed to reserve page summary memory

### ISSUE THREAD

**Issue by yuanwb1984** [kuoruan/luci-app-v2ray#124]
openwrt 19.01 Orange Pi Zero Plus arm64 更新到luci-app-v2ray_1.5.5-1_all.ipk
后v2ray不运行，日志里报错如下：
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: fatal error: failed to reserve page summary memory
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]:
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime stack:
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime.throw(0xc3587f, 0x25)
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: 	runtime/panic.go:1114 +0x54 fp=0x7ff0bde040 sp=0x7ff0bde010 pc=0x4327ac
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime.(*pageAlloc).sysInit(0x12fd7a8)
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: 	runtime/mpagealloc_64bit.go:80 +0x158 fp=0x7ff0bde0d0 sp=0x7ff0bde040 pc=0x4298b0
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime.(*pageAlloc).init(0x12fd7a8, 0x12fd7a0, 0x1312098)
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: 	runtime/mpagealloc.go:297 +0x74 fp=0x7ff0bde100 sp=0x7ff0bde0d0 pc=0x427bec
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime.(*mheap).init(0x12fd7a0)
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: 	runtime/mheap.go:694 +0x2a0 fp=0x7ff0bde130 sp=0x7ff0bde100 pc=0x424d98
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime.mallocinit()
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: 	runtime/malloc.go:470 +0x124 fp=0x7ff0bde160 sp=0x7ff0bde130 pc=0x40be1c
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime.schedinit()
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: 	runtime/proc.go:545 +0x6c fp=0x7ff0bde1d0 sp=0x7ff0bde160 pc=0x435df4
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: runtime.rt0_go(0x0, 0x7ff0bde230, 0x7f81b408f8, 0x7f81b410d0, 0x7f81b40aa0, 0x2, 0x7ff0bdef60, 0x7ff0bdef6f, 0x0, 0x7ff0bdef97, ...)
Tue Apr  7 14:10:45 2020 daemon.err v2ray[31041]: 	runtime/asm_arm64.s:70 +0xb8 fp=0x7ff0bde200 sp=0x7ff0bde1d0 pc=0x45ee90

但是单独在终端 v2ray -c /var/etc/v2ray/config.main 可以运行

**Comment by kuoruan** [comment]
disable memory limit
