### ISSUE TITLE
当导入过多节点时 global 界面 Outbounds enabled 列表横向显示显得混乱

### ISSUE THREAD

**Issue by zhangjint5** [kuoruan/luci-app-v2ray#126]
页面：/cgi-bin/luci/admin/services/v2ray/global
项目：Outbounds enabled
描述：当节点很多时，横向显示变得非常混乱，建议使用纵向列表方式显示！

**Comment by kuoruan** [comment]
现在的多选框样式是默认的，能给个截图看看吗？

**Comment by zhangjint5** [comment]
![无标题](https://user-images.githubusercontent.com/57692302/79213203-5b88f180-7e7b-11ea-9b78-7f300e2563f7.png)
> 给

变成这样一堆
