### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by ohyeah521** [kuoruan/luci-app-v2ray#128]
问题重新：当修改v2ray配置或重起v2ray服务后，ipset规则会被清空，而此时电脑中已经缓存了原ipset规则中的ip地址，电脑直接与其通信，这时由于路由器中的ipset为空，此次通信不会走v2ray代理导致被阻断。

修改方法：在修改配置或重启v2ray前缓存ipset中的ip地址，v2ray服务启动后重新导入原ipset中的ip

**Comment by kuoruan** [comment]
Duplicate of kuoruan/openwrt-v2ray#62
