### ISSUE TITLE
已经装好了，请问怎样才能翻出去啊？

### ISSUE THREAD

**Issue by NeedforGit** [kuoruan/luci-app-v2ray#13]
3个IPK文件都已经装好了，服务也显示正在运行，现在就是翻不出去。

请问在界面中 要勾选那些 才能翻出去呢？

是勾选出站连接的哪个，还是 启用路由里的哪个？ 才能以大陆白名单翻出去呢？

请帮帮小白！

**Comment by kuoruan** [comment]
先试试正常启透明代理

**Comment by NeedforGit** [comment]
感谢回复，请问具体怎样启动透明代理啊？ 具体要勾选哪些啊？

救救小白吧！

**Comment by kuoruan** [comment]
如果你使用 vmess 协议，直接修改默认的 出站连接 upstream_vmess
然后在设置里启用所有的入站和出站代理，即可。
确保入站里的 transparent_proxy 已启用透明代理
