### ISSUE TITLE
请教大佬一个问题，关于自己建dns。

### ISSUE THREAD

**Issue by snakwu** [kuoruan/luci-app-v2ray#132]
我的环境是在局域网一台主机自建了一个dns服务器，openwrt的wan口和dhcp里的dns转发都填我这个自建dns的ip，然后v2ray会非常慢，开udp转发，更是国内外无网，如果把wan口的dhcp的dns转发填114或者自动，就正常，其实我大概也知道是自环了，请问有办法可以解决吗？

**Comment by kuoruan** [comment]
所有的dns请求都会过 v2ray，你需要添加一条路由，让到你 DNS IP 的流量走 direct

**Comment by snakwu** [comment]
> 所有的dns请求都会过 v2ray，你需要添加一条路由，让到你 DNS IP 的流量走 direct

请问应该怎么操作？谢谢

**Comment by kuoruan** [comment]
请参考 v2ray 的路由配置

**Comment by snakwu** [comment]
> 请参考 v2ray 的路由配置

如果对于openwrt本身这个dns ip就自环了，可有解决办法

**Comment by kuoruan** [comment]
为什么会呢？iptables 已经跳过了所有保留地址

**Comment by snakwu** [comment]
> 为什么会呢？iptables 已经跳过了所有保留地址

所以我也不理解，我除了v2ray，另外也有个解锁音乐插件，也是这问题，当在dhcp转发dns到我自建的dns就会访问不了网页。

**Comment by kuoruan** [comment]
你这个 DNS 是在内网里边吗？而且在路由器下？

**Comment by snakwu** [comment]
> 你这个 DNS 是在内网里边吗？而且在路由器下？
内网下的一台机子上

**Comment by kuoruan** [comment]
把dns代理关了试试

现在是局域网内所有的 dns 请求都会被转发到 v2ray，所以你 192.168.88.100 出来的查询请求又会回到 v2ray

**Comment by snakwu** [comment]
> 把dns代理关了试试
> 
> 现在是局域网内所有的 dns 请求都会被转发到 v2ray，所以你 192.168.88.100 出来的查询请求又会回到 v2ray

关了dns模块，不开tproxy，关了udp转了，访问国外非常慢

**Comment by kuoruan** [comment]
我的意思是关了 dns 转发

**Comment by snakwu** [comment]
> 我的意思是关了 dns 转发

嗯，关了dhcp的转发，也不行，必须wan口改自动或非内网dns，才正常，应该是环回了，但不知道怎么解决

**Comment by kuoruan** [comment]
在不开启转发 DNS 流量到 V2ray 的情况下，不会出现 UDP 流量被转发的情况，也不会出现 UDP 的回环。可能是你自建 dns 查询速度过慢

**Comment by snakwu** [comment]
> 在不开启转发 DNS 流量到 V2ray 的情况下，不会出现 UDP 流量被转发的情况，也不会出现 UDP 的回环。可能是你自建 dns 查询速度过慢

我dig过，延时是非常低的

**Comment by snakwu** [comment]
> 在不开启转发 DNS 流量到 V2ray 的情况下，不会出现 UDP 流量被转发的情况，也不会出现 UDP 的回环。可能是你自建 dns 查询速度过慢

K大，我如果放弃用coerdns，想直接用v2ry做分流，但我还没搞明白v2ray模块之间的关系，我看过默认路由规则和dns的规则，路由里面也有dns分流，dns模块也有作了分流，这鼐先后顺序是什么？谢谢你的解答

**Comment by kuoruan** [comment]
https://medium.com/@TachyonDevel/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0

**Comment by tpaullee** [comment]
Great reference to read.
N 37-17.454 W 121-57.679 http://tpaullee.blogspot.com/ Cultivating Human Goodness 

    On Saturday, April 25, 2020, 03:36:23 AM PDT, Xingwang Liao <notifications@github.com> wrote:  
 
 


https://medium.com/@TachyonDevel/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0
