### ISSUE TITLE
请问，怎么批量导入ip规则和域名规则呢？

### ISSUE THREAD

**Issue by zenyanbo** [kuoruan/luci-app-v2ray#14]
请问，怎么批量导入ip规则和域名规则呢？ip与ip、域名与域名间空格、我都试过了。在/etc/v2ray下也没有看见关于路由的json文件。

**Comment by kuoruan** [comment]
当前并不支持批量导入，只能通过修改 /etc/config/v2ray 文件快速添加

**Comment by zenyanbo** [comment]
好像可以这样输入（我看about确实批量导入了）：epochtimes domain:881903.com domain:aboluowang.com domain:bannedbook.org domain:china21.org domain:chinaaffairs.org domain:dajiyuan.com domain:dalianmeng.org domain:dkn.tv domain:dongtaiwang.com domain:edoors.com domain:epochweekly.com domain:falundafa.org domain:fgmtv.org domain:gardennetworks.com domain:gongyiluntan.org domain:gpass1.com domain:hrichina.org domain:huanghuagang.org domain:internetfreedom.org domain:kanzhongguo.com domain:lagranepoca.com domain:mh4u.org domain:mhradio.org domain:minghui.org domain:newrealmstudios.ca domain:ntdtv.com domain:ogate.org domain:open.com.hk domain:organcare.org.tw domain:qxbbs.org domain:renminbao.com domain:secretchina.com domain:shenyun.com domain:shenyunperformingarts.org domain:shenzhoufilm.com domain:soundofhope.org domain:theepochtimes.com domain:tiandixing.org domain:tuidang.org domain:velkaepocha.sk domain:watchinese.com domain:wixsite.com domain:wujie.net domain:wujieliulan.com domain:xinsheng.net domain:zhengjian.org domain:zhuichaguoji.org adservice analytics analysis domain:42trck.com domain:51.la domain:adjust.com domain:adjust.io domain:admaster.com.cn domain:adsensor.org domain:adtarget.tech domain:adthor.com domain:amazon-adsystem.com domain:app-adforce.jp domain:appier.net domain:appsflyer.com domain:apsalar.com domain:apxadtracking.net domain:cloudmobi.net domain:cnzz.com domain:ctrmi.com domain:go2cloud.org domain:growingio.com domain:haloapps.com domain:irs01.com domain:iskyworker.com domain:kochava.com domain:lenzmx.com domain:lnk0.com domain:lnk8.cn domain:measurementapi.com domain:miaozhen.com domain:mopub.com domain:onelink.me domain:rayjump.com domain:scorecardresearch.com domain:sdkclick.com domain:smartadserver.com domain:smartnews-ads.com domain:tanv.com domain:tanx.com domain:uri6.com domain:xdrig.com domain:ad.daum.net domain:track.xiachufang.com domain:deliver.ifeng.com full:abema-adx.ameba.jp full:ad.12306.cn full:ad.caiyunapp.com full:ad.huajiao.com full:ad.hzyoka.com full:ad.jiemian.com full:ad.qingting.fm full:ad.wappalyzer.com full:ad-cn.jovcloud.com full:ads.daydaycook.com.cn full:adsapi.manhuaren.com full:adsdk.dmzj.com full:adui.tg.meitu.com full:adx.hupu.com full:adx-api.hupu.com full:adxserver.ad.cmvideo.cn full:app-ad.variflight.com full:applog.mobike.com full:appnext.hs.llnwd.net full:appnext-a.akamaihd.net full:ggs.myzaker.com full:itad.linetv.tw full:ja.chushou.tv full:mads.suning.com full:mopnativeadv.037201.com full:nativeadv.dftoutiao.com full:optimus-ads.amap.com full:sugar.zhihu.com full:track.tiara.daum.net full:track.tiara.kakao.com full:trackapp.guahao.cn full:traffic.mogujie.com full:wmlog.meituan.com full:adshow.58.com full:track.58.com full:tracklog.58.com domain:iadsdk.apple.com domain:ads.internal.unity3d.com domain:ads.prd.ie.internal.unity3d.com domain:unityads.unity3d.com full:acs4baichuan.m.taobao.com full:adash.m.taobao.com full:adash.man.aliyuncs.com full:adashbc.ut.taobao.com full:adash-c.ut.taobao.com full:adashxgc.ut.taobao.com full:adashx4yt.m.taobao.com full:apoll.m.taobao.com full:nbsdk-baichuan.alicdn.com full:tunion-api.m.taobao.com full:adproxy.autohome.com.cn full:rd.autohome.com.cn full:al.autohome.com.cn full:applogapi.autohome.com.cn domain:baidustatic.com full:afd.baidu.com full:duclick.baidu.com full:hm.baidu.com full:hmma.baidu.com full:mobads.baidu.com full:mobads-logs.baidu.com full:nsclick.baidu.com full:wn.pos.baidu.com full:applog.musical.ly full:track.toutiao.com full:xlog.snssdk.com full:xlog-va.byteoversea.com full:adx.yiche.com full:log.ycapp.yiche.com full:advertise.baicizhan.org full:advertise.baicizhan.com full:galaxy.bjcathay.com full:mdrecv.app.cntvwb.cn full:sdapprecv.app.cntvwb.cn full:vdapprecv.app.cntvwb.cn full:admarket.21cn.com full:adshows.21cn.com domain:doubleclick.net domain:googleadservices.com domain:googleadsserving.cn domain:googlesyndication.com domain:googletagmanager.com domain:googletagservices.com domain:da.mgtv.com domain:da.hunantv.com domain:log.hunantv.com full:log.v2.hunantv.com full:v2.log.hunantv.com full:ifacelog.iqiyi.com full:mbdlog.iqiyi.com full:msg.71.am full:msg.qy.net full:t7z.cupid.iqiyi.com full:adserviceretry.kugou.com full:ads.service.kugou.com full:adsfile.bssdlbig.kugou.com full:g.koowo.com full:log.stat.kugou.com full:log.web.kugou.com full:log.kuwo.cn full:kgmobilestat.kugou.com full:kgmobilestatbak.kugou.com full:mobilelog.kugou.com full:mobilead.kuwo.cn full:rich.kuwo.cn full:ad-stat.ksosoft.com full:img.auction-ads.wpscdn.cn full:minfo.wps.cn domain:webp2p.letv.com full:ark.letv.com full:emma-414870e223.huodonghezi.com full:g3.letv.com full:n.mark.letv.com domain:ad.xiaomi.com domain:admob.xiaomi.com domain:ad.intl.xiaomi.com domain:tracking.miui.com full:adv.sec.miui.com full:adv.sec.intl.miui.com full:o2o.api.xiaomi.com full:ad.api.moji.com full:adlaunch.moji.com full:ads.mojicdn.com full:v1.log.moji.com full:ad.bn.netease.com full:ad.yixin.im full:admusicpic.music.126.net full:iadmat.nosdn.127.net full:iadmusicmat.music.126.net full:iadmusicmatvideo.music.126.net full:impservice.dictapp.youdao.com full:impservice.youdao.com full:log.yex.youdao.com full:log-yex.youdao.com full:n.3g.163.com full:nex.163.com full:yt-adp.nosdn.127.net full:ads.aplus.pptv.com full:ads.aplusapi.pptv.com full:asimgs.pplive.cn full:de.as.pptv.com full:regist.fotoable.com full:cdn.adapi.fotoable.com full:adnew.wifi8.com full:adfile.wifi8.com full:u1.img.mobile.sina.cn full:sax.sina.com.cn full:saxs.sina.com.cn full:saxn.sina.com.cn domain:ads.sohu.com domain:aty.sohu.com full:imp.optaim.com full:v2.reachmax.cn full:track.sohu.com full:hui.sohu.com domain:bugly.qq.com domain:e.qq.com domain:gdt.qq.com domain:l.qq.com domain:rqd.qq.com full:adsmind.tc.qq.com full:btrace.qq.com full:mtrace.qq.com full:oth.eve.mdt.qq.com full:pgdt.gtimg.cn full:pingma.qq.com full:pingtcss.qq.com full:splashqqlive.gtimg.com full:tajs.qq.com full:wxsnsdy.wxs.qq.com full:wxsnsdythumb.wxs.qq.com full:imgadpai.thepaper.cn full:admonitor.thepaper.cn full:adsp.xunlei.com full:etl.xlmc.sandai.net full:adm.10jqka.com.cn full:stat.10jqka.com.cn full:ad-analysis.pconline.com.cn full:iad0ssl.pcauto.com.cn full:iad0ssl.pconline.com.cn full:imgad0.pcauto.com.cn full:imgad0.pconline.com.cn full:ivy.pchouse.com.cn full:adtrack.ucweb.com full:applogios.uc.cn full:track.uc.cn full:a.wkanx.com full:cwx.lianwangtech.com full:c1wx.lianwangtech.com full:ad.ximalaya.com full:adse.ximalaya.com full:adse.wsa.ximalaya.com full:adbehavior.wsa.ximalaya.com full:t-ads.xiaohongshu.com full:apm-track.xiaohongshu.com domain:atm.youku.com full:ad.mobile.youku.com full:iyes.youku.com full:apppv.zol.com.cn full:pvnapp.zol.com.cn domain:17gouwuba.com domain:186078.com domain:189zj.cn domain:285680.com domain:3721zh.com domain:4336wang.cn domain:51chumoping.com domain:51mld.cn domain:58mingri.cn domain:58mingtian.cn domain:6d63d3.com domain:7gg.cc domain:91veg.com domain:9s6q.cn domain:adsame.com domain:aiclk.com domain:akuai.top domain:atplay.cn domain:baiwanchuangyi.com domain:bayimob.com domain:beerto.cn domain:beilamusi.com domain:benshiw.net domain:bianxianmao.com domain:bryonypie.com domain:cishantao.com domain:cszlks.com domain:cudaojia.com domain:dafapromo.com domain:daitdai.com domain:dsaeerf.com domain:dugesheying.com domain:dv8c1t.cn domain:erdoscs.com domain:fan-yong.com domain:feih.com.cn domain:fjlqqc.com domain:fkku194.com domain:freedrive.cn domain:gclick.cn domain:goufanli100.com domain:gouwubang.com domain:haoshengtoys.com domain:ichaosheng.com domain:ishop789.com domain:jdkic.com domain:jiubuhua.com domain:jwg365.cn domain:kawo77.com domain:kualianyingxiao.cn domain:kumihua.com domain:linktech.cn domain:ltheanine.cn domain:maipinshangmao.com domain:minisplat.cn domain:mkitgfs.com domain:mlnbike.com domain:mobjump.com domain:nbkbgd.cn domain:newapi.com domain:pinzhitmall.com domain:poppyta.com domain:qichexin.com domain:qinchugudao.com domain:quanliyouxi.cn domain:qutaobi.com domain:ry51w.cn domain:sg536.cn domain:sifubo.cn domain:sifuce.cn domain:sifuda.cn domain:sifufu.cn domain:sifuge.cn domain:sifugu.cn domain:sifuhe.cn domain:sifuhu.cn domain:sifuji.cn domain:sifuka.cn domain:smgru.net domain:taoggou.com domain:tcxshop.com domain:tjqonline.cn domain:topitme.com domain:tuia.cn domain:tuipenguin.com domain:tuitiger.com domain:wx16999.com domain:xiaohuau.xyz domain:yinmong.com domain:yiqifa.com domain:yitaopt.com domain:yjqiqi.com domain:yukhj.com domain:zhaozecheng.cn domain:zhenxinet.com domain:zunmi.cn domain:zzd6.com domain:kuaizip.com domain:mackeeper.com domain:flash.cn full:geo2.adobe.com domain:4009997658.com domain:abbyychina.com domain:bartender.cc domain:betterzip.net domain:beyondcompare.cc domain:bingdianhuanyuan.cn domain:chemdraw.com.cn domain:cjmakeding.com domain:cjmkt.com domain:codesoftchina.com domain:coreldrawchina.com domain:crossoverchina.com domain:easyrecoverychina.com domain:ediuschina.com domain:flstudiochina.com domain:formysql.com domain:guitarpro.cc domain:huishenghuiying.com.cn domain:hypersnap.net domain:iconworkshop.cn domain:imindmap.cc domain:jihehuaban.com.cn domain:keyshot.cc domain:kingdeecn.cn domain:logoshejishi.com domain:mairuan.cn domain:mairuan.com domain:mairuan.com.cn domain:mairuan.net domain:mairuanwang.com domain:makeding.com domain:mathtype.cn domain:mindmanager.cc domain:mindmapper.cc domain:mycleanmymac.com domain:nicelabel.cc domain:ntfsformac.cc domain:ntfsformac.cn domain:overturechina.com domain:passwordrecovery.cn domain:pdfexpert.cc domain:shankejingling.com domain:ultraiso.net domain:vegaschina.cn domain:xmindchina.net domain:xshellcn.com domain:yihuifu.cn domain:yuanchengxiezuo.com domain:zbrushcn.com domain:zhzzx.com

**Comment by ttimasdf** [comment]
可以参考我做的一些小修改，加入一个ipset导入chnroute。v2ray自身转发性能比较差，即使freedom也非常占CPU，放路由器上容易吃不满带宽。更不用提往里塞chnroute还有gfwlist这种巨大的列表了。。

下面的patch应用到 `/etc/init.d/v2ray`上，并自己准备一份chnroute，就可以将IP规则以ipset列表的形式应用了。有v2做dns净化，域名规则应该没有多大意义。

```diff
11a12
> CHNROUTE_FILE=/root/chnroute.txt
199a201,204
> gen_chnroute_ip() {
> 	[ -f "${CHNROUTE_FILE:=/dev/null}" ] && grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" $CHNROUTE_FILE
> }
>
225a231,238
> 	# https://github.com/shadowsocks/luci-app-shadowsocks/blob/e4bd61df5657d53ba6383c08c6e05e0a8f110658/files/root/usr/bin/ss-rules#L58-L74
> 	ipset -! restore <<-EOF
> 		create v2ray_dst_bp hash:net hashsize 64
> 		$(for ip in $server_ips; do echo "add v2ray_dst_bp $ip"; done)
> 		$(for ip in $reserved_ips; do echo "add v2ray_dst_bp $ip"; done)
> 		$(gen_chnroute_ip | sed -e "s/^/add v2ray_dst_bp /")
> 	EOF
>
226a240
> 	# https://jiangxin.info/0807/high-quality-proxy/#iptables
230,231c244,246
< 		$(for s in $server_ips ; do echo "-A V2RAY -d $s -j RETURN" ; done)
< 		$(for r in $reserved_ips ; do echo "-A V2RAY -d $r -j RETURN" ; done)
---
> 		$(for s in $server_ips ; do echo "#-A V2RAY -d $s -j RETURN" ; done)
> 		$(for r in $reserved_ips ; do echo "#-A V2RAY -d $r -j RETURN" ; done)
> 		-A V2RAY -m set --match-set v2ray_dst_bp dst -j RETURN
265a281
> 	ipset destroy v2ray_dst_bp
```

作者如果有精力的话可以把这个patch做成一个可选的选项加入到配置列表中，可以显著提高国内网站的吞吐量，对百兆以上宽带效果很明显。 @kuoruan

**Comment by zenyanbo** [comment]
> 可以参考我做的一些小修改，加入一个ipset导入chnroute。v2ray自身转发性能比较差，即使freedom也非常占CPU，放路由器上容易吃不满带宽。更不用提往里塞chnroute还有gfwlist这种巨大的列表了。。
> 
> 下面的patch应用到 `/etc/init.d/v2ray`上，并自己准备一份chnroute，就可以将IP规则以ipset列表的形式应用了。有v2做dns净化，域名规则应该没有多大意义。
> 
> ```diff
> 11a12
> > CHNROUTE_FILE=/root/chnroute.txt
> 199a201,204
> > gen_chnroute_ip() {
> > 	[ -f "${CHNROUTE_FILE:=/dev/null}" ] && grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" $CHNROUTE_FILE
> > }
> >
> 225a231,238
> > 	# https://github.com/shadowsocks/luci-app-shadowsocks/blob/e4bd61df5657d53ba6383c08c6e05e0a8f110658/files/root/usr/bin/ss-rules#L58-L74
> > 	ipset -! restore <<-EOF
> > 		create v2ray_dst_bp hash:net hashsize 64
> > 		$(for ip in $server_ips; do echo "add v2ray_dst_bp $ip"; done)
> > 		$(for ip in $reserved_ips; do echo "add v2ray_dst_bp $ip"; done)
> > 		$(gen_chnroute_ip | sed -e "s/^/add v2ray_dst_bp /")
> > 	EOF
> >
> 226a240
> > 	# https://jiangxin.info/0807/high-quality-proxy/#iptables
> 230,231c244,246
> < 		$(for s in $server_ips ; do echo "-A V2RAY -d $s -j RETURN" ; done)
> < 		$(for r in $reserved_ips ; do echo "-A V2RAY -d $r -j RETURN" ; done)
> ---
> > 		$(for s in $server_ips ; do echo "#-A V2RAY -d $s -j RETURN" ; done)
> > 		$(for r in $reserved_ips ; do echo "#-A V2RAY -d $r -j RETURN" ; done)
> > 		-A V2RAY -m set --match-set v2ray_dst_bp dst -j RETURN
> 265a281
> > 	ipset destroy v2ray_dst_bp
> ```
> 
> 作者如果有精力的话可以把这个patch做成一个可选的选项加入到配置列表中，可以显著提高国内网站的吞吐量，对百兆以上宽带效果很明显。 @kuoruan

谢谢。我也感觉对tcp处理有点小问题，经常掉线。我去试试

**Comment by kuoruan** [comment]
@ttimasdf 暂且加了三个代理模式，现在都通过 ipset 设置 iptables 了。
