### ISSUE TITLE
在opkg upgrade时出现错误

### ISSUE THREAD

**Issue by shadowNo-1** [kuoruan/luci-app-v2ray#142]
更新时总会报错说缺少resolveip，实在不知道怎么解决，

> Collected errors:

> * opkg_conf_parse_file: Duplicate src declaration (kuoruan_universal >http://openwrt.kuoruan.net/packages/releases/all). Skipping.
>* satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-v2ray-zh-cn:
>* 	resolveip

**Comment by kuoruan** [comment]
```opkg update && opkg install resolveip```
