### ISSUE TITLE
部分谷歌网站不能访问，keep.google.com能访问，www.googole.com，youtube.com 不能访问。

### ISSUE THREAD

**Issue by alonewoo** [kuoruan/luci-app-v2ray#144]
升完级出现问题了，部分谷歌网站不能访问，keep.google.com能访问，www.googole.com，youtube.com 不能访问。查了2天了，不知道问题出在哪里。麻烦帮我看看。

![image](https://user-images.githubusercontent.com/44246977/81381562-81827880-913f-11ea-838a-caadd0a2b8d5.png)

{
	"log": {
		"access": "/dev/null",
		"loglevel": "warning",
		"error": "/var/log/v2ray-error.log"
	},
	"dns": {
		"servers": [
			"1.1.1.1",
			{
				"address": "114.114.114.114",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"protocol": [
					"bittorrent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "dns_out"
			},
			{
				"type": "field",
				"ip": [
					"114.114.114.114",
					"223.5.5.5"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"1.1.1.1",
					"8.8.8.8",
					"208.67.222.222"
				],
				"outboundTag": "proxy"
			},
			{
				"type": "field",
				"port": "123",
				"network": "udp",
				"outboundTag": "direct"
			}
		]
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1080,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true,
				"ip": "127.0.0.1"
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		},
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp,udp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "redirect"
				}
			},
			"tag": "transparent",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"sendThrough": "192.168.200.148",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "35.201.1.253",
						"port": 23998,
						"users": [
							{
								"id": "2b813205-459f-4fe2--",
								"alterId": 64,
								"security": "auto"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"tcpSettings": {
					
				},
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "proxy"
		},
		{
			"protocol": "freedom",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "direct"
		},
		{
			"sendThrough": "192.168.200.148",
			"protocol": "dns",
			"settings": {
				"network": "udp",
				"address": "1.1.1.1",
				"port": 53
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "dns_out"
		}
	]
}

**Comment by H0u5er** [comment]
keep.google.com 能访问多半是缓存，切换浏览器到无痕模式或者隐私模式试试。看上去参数没问题，请问确定存在 sendThrough 参数进行转发？ 另外请检查防火墙转发设置。

**Comment by alonewoo** [comment]
谢谢答复。
昨天今天又折腾一天，发现是dns解析出问题了。
用nslookup查看，www.google.com 返回0.0.0.0，但www.google.com.au 就能返回正确IP地址，把www.google.com ip手工加到本机hosts里就ok了，youtube.com也是同样解决了。只是还是不明白这个问题真正原因是啥。
顺便说一下，同样的配置文件，仅仅把透明代理的部分去掉，自己在本机pc上连v2ray，完全没有问题。
