### ISSUE TITLE
An err

### ISSUE THREAD

**Issue by AlexYe233** [kuoruan/luci-app-v2ray#149]
openwrt-19.07.2
安装luci-app-v2ray (1.5.6)后访问路由管理界面，出现:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/bootstrap/header'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/bootstrap/hea..."]:20: attempt to call field 'node_childs' (a nil value)
stack traceback:
	[string "/usr/lib/lua/luci/view/themes/bootstrap/hea..."]:20: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:755: in function 'include'
	[string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:755: in function 'include'
	[string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
	(tail call): ?
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:979: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

谢谢您一直在维护这个软件

**Comment by kuoruan** [comment]
luci-compat 装了吗？

**Comment by AlexYe233** [comment]
装了，第一次装完luci-app-v2ray的后就出现这种情况，重置后第二次装完luci-app-v2ray1.5.5正常，但是当别的luci-app装完出现这种情况

**Comment by AlexYe233** [comment]
直接安装luci-compat的时候显示 
Installing luci-compat (git-20.131.47987-bcdb9fd-1) to root...
Downloading 
Errors
Collected errors:
 * check_data_file_clashes: Package luci-compat wants to install file /usr/lib/lua/luci/tools/webadmin.lua
	But that file is already provided by package  * luci-base
……（一大堆类似的）

先卸载luci-base --force-depends再安装luci-compat就易出现usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.这种情况
是不是luci-compat依赖有问题，dalao有解决的方法吗

**Comment by kuoruan** [comment]
luci-base 明显不能卸载啊。
把 luci-base 装回去，不装 luci-compat 再试试

**Comment by AlexYe233** [comment]
不装luci-compat的话 luci-app-v2ray能安装，但进不去（网页报错），还有很多luci-app就不能安装了

**Comment by AlexYe233** [comment]
卸载luci-base再安装luci-compat后还会把luci-base给装回去的，luci-compat依赖于，但是用的时候会出第一个错

**Comment by kuoruan** [comment]
新版本的 luci-base 是不会包含 luci-compat 的文件的，你是不是没有 opkg update 啊？

**Comment by kuoruan** [comment]
看看 ```/etc/opkg.conf``` 文件

**Comment by AlexYe233** [comment]
/etc/opkg.conf:
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
option check_signature
用的清华源
/etc/opkg/distfeeds.conf:
src/gz openwrt_core https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.2/targets/ramips/mt7621/packages
src/gz openwrt_kmods https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.2/targets/ramips/mt7621/kmods/4.14.171-1-2e88863ccdd594fb8e842df3c25842ee
src/gz openwrt_base https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.2/packages/mipsel_24kc/base
src/gz openwrt_luci https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.2/packages/mipsel_24kc/luci
src/gz openwrt_packages https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.2/packages/mipsel_24kc/packages
src/gz openwrt_routing https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.2/packages/mipsel_24kc/routing
src/gz openwrt_telephony https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.2/packages/mipsel_24kc/telephony
![捕获](https://user-images.githubusercontent.com/34712118/81669615-0c81ac80-9479-11ea-9fc7-a00df3a43aa9.PNG)
已update，系统是mipsel24kc/openwrt19.07.2

**Comment by AlexYe233** [comment]
opkg install luci-compat --force-overwrite就可以了， 谢谢大佬的指点
