### ISSUE TITLE
outbound排序导致数据丢失

### ISSUE THREAD

**Issue by mlgexyz** [kuoruan/luci-app-v2ray#15]
移动自己添加的出站连接后保存并应用会导致luci报错，并且自己添加的这个出站连接配置丢失，然后移到原来顺序上数据再次保存并应用又会回来。
luci报错：
> /usr/lib/lua/luci/dispatcher.lua:509: Failed to execute arcombine dispatcher target for entry '/admin/services/v2ray/outbounds'.
The called action terminated with an exception:
invalid key to 'next'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:509: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by kuoruan** [comment]
没看懂，具体重现步骤？

**Comment by mlgexyz** [comment]
添加一个出站连接，填写配置后保存并应用，一切正常，然后将新添加的出站连接（理论排序在最下面）向上移，保存并应用，产生报错，之后排序移动是成功了，但是新添加的出站连接配置会丢失（设置和底层设置变成空白），但如果把这个出站连接再往下移动动原排序上，保存并应用，配置又会回来。
个人推测为数据存储逻辑问题

**Comment by kuoruan** [comment]
在新版 OpenWrt 上无法重现

**Comment by ttimasdf** [comment]
可以复现。本质原因是添加inbound、outbound配置时，额外的配置信息存储于 `/etc/v2ray/inbound-settings.json` 及相关文件中，而这些文件中，每个配置项用uci里配置项的索引作为key，类似这种 `cfgXXXXXX` 。因此这个值一变，service启动寻找config的时候就找不到对应的内容了。

我的解决办法是在自己创建的出入站连接上，都给它加上一个名字。类似这样：

```
# BEFORE
config inbound
        option alias 'vmess_in'
        option listen '0.0.0.0'
        option port '12345'
        option protocol 'vmess'
        option tag 'vmess_in'

# AFTER
config inbound 'vmess_in'
        option alias 'vmess_in'
        option listen '0.0.0.0'
        option port '12345'
        option protocol 'vmess'
        option tag 'vmess_in'
```
这样排序或者删除其他连接配置的时候，这个配置的名字永远不会变。我对uci不是特别熟，只能希望作者给加上了 😅

**Comment by kuoruan** [comment]
我加个选项将key固定吧
