### ISSUE TITLE
始终显示无法运行啊

### ISSUE THREAD

**Issue by adolfvicious** [kuoruan/luci-app-v2ray#151]
按照各种方式进行配置，也试过了https://www.solarck.com/openwrt-v2ray.html的方法，
但就是显示未运行，而且还有Can't get V2Ray version提示。求救~

![21453212](https://user-images.githubusercontent.com/8144674/81847765-9ff4d380-9586-11ea-8fe8-0011552f205d.png)

路由器是极路由1(HC6361)，版本是原版OpenWrt 18.06.8 r7989-82fbd85747 / LuCI openwrt-18.06 branch (git-20.029.49294-41e2258)

**Comment by tpaullee** [comment]
I have vague memory that /usr/bin/v2ray/v2ray is the binary. Do a "which v2ray" for good measure.TPL

    On Wednesday, May 13, 2020, 11:01:12 AM PDT, adolfvicious <notifications@github.com> wrote:  
 
 


按照各种方式进行配置，也试过了https://www.solarck.com/openwrt-v2ray.html的方法，
但就是显示未运行，而且还有Can't get V2Ray version提示。求救~



路由器是极路由1(HC6361)，版本是原版OpenWrt 18.06.8 r7989-82fbd85747 / LuCI openwrt-18.06 branch (git-20.029.49294-41e2258)

**Comment by kuoruan** [comment]
大概率是 v2ray-core 安装失败了

在命令行试试 ```/usr/bin/v2ray --version``` 有输出吗

**Comment by adolfvicious** [comment]
显示的是安装成功呀，试过/usr/bin/v2ray --version后显示Segmentation fault...

**Comment by kuoruan** [comment]
软件包不支持你的硬件

**Comment by adolfvicious** [comment]
啊，是所有版本都不支持么，或者我试试老版本的？

**Comment by Gastovski** [comment]
我的路由是一款linksys的WRT1900ACS V2也算是一款比较流行的硬路由，CPU用的是arm_cortex-a9_vfpv3-d16。我看到release中有对这款CPU的支持，但是我在安装的过程中，安装mini版，图形界面提示服务未运行，用命令行检查版本号，系统反馈和上面这位的一样。我又尝试安装普通版，可是安装过程中overlay的空间不够了，无法完成安装，所以没法尝试。
我的这款路由倒是可以通过U盘扩展Overlay的空间用来安装软件，不过在做尝试之前，还是想问一下，这款路由和您的软件是不是存在兼容性问题呢？
