### ISSUE TITLE
有关透明代理路由器自身网络

### ISSUE THREAD

**Issue by MassSmith** [kuoruan/luci-app-v2ray#16]
透明代理路由器自身网络，在v2ray官网的白话文教程里面有。那个说的虽然不专门针对路由器，但是原理是一样的。网址：https://guide.v2fly.org/app/transparent_proxy.html
我自己也是根据这篇教程，做了一个树莓派的透明代理网关。并移植集成了V2ray.Fun的web控制界面。项目地址：
https://github.com/MassSmith/smgate

关键点在于在v2ray的config.json的每个出口中配置
"sockopt": {
					"mark": 255
				}
这是config.json的模板：https://raw.githubusercontent.com/MassSmith/smgate/master/config/tcp-config/%E6%A0%91%E8%8E%93%E6%B4%BE%E7%BD%91%E5%85%B3v2ray%E7%9A%84config.json%E6%A8%A1%E6%9D%BF/tcp-config.json

并且用iptable设置，命令如下：
iptables -t nat -A V2RAY -p tcp -j RETURN -m mark --mark 0xff

我用的全部命令是：https://raw.githubusercontent.com/MassSmith/smgate/master/v2rayiptable.sh

路由器的设置应该相似。

**Comment by kuoruan** [comment]
待研究

**Comment by kuoruan** [comment]
现在的问题是代理自身网络的时候开启国内直连的问题

**Comment by MassSmith** [comment]
试试这个配置，对直连出口的流量做标识。
{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		}
防火墙放行对应标识的流量。不再做转发。
iptables -t nat -A V2RAY -p tcp -j RETURN -m mark --mark 0xff
（上面这个命令是在debian中，openwrt不知道是否适用，我也在测试中）
我在树莓派3b上装了openwrt最新版，也装了你做的这个luci，很好用。不过需要对v2ray的json配置有一定的熟悉才能驾驭得了。但是你这个luci做的很棒。同时发现在树莓派的这个openwrt版本中，不用安装v2ray的ipk版，可以直接运行v2ray官网的arm64版本。只要指定v2ray的运行文件位置即可。
v2ray由于自身的特点，对设备的计算性能要求比ss要高，一般跑ss很溜的路由器，运行v2ray，有点吃力，高性能的路由器又贼贵。最后选择了树莓派做为硬件。感觉比较合适，除了wifi是短板，其他都不错。个人用，足够了。

**Comment by kuoruan** [comment]
周末我加个选项，尝试一下

**Comment by kuoruan** [comment]
加了个选项，但是没有继续测试。
