### ISSUE TITLE
敢问大佬，lcui2和next分支是什么作用的？

### ISSUE THREAD

**Issue by snakwu** [kuoruan/luci-app-v2ray#161]
敢问大佬，lcui2和next分支是什么作用的？

**Comment by kuoruan** [comment]
LuCI2 是新版给 OpenWrt 19 及以后用的，开发中

**Comment by kuoruan** [comment]
Related to #101

**Comment by snakwu** [comment]
> Related to #101
Makefile少了这一行，希望可以加上，要不编译菜单看不到v2ray的选项，谢谢
# call BuildPackage - OpenWrt buildroot signature

**Comment by snakwu** [comment]
> LuCI2 是新版给 OpenWrt 19 及以后用的，开发中

刚才试用了luci2，gfw模式仍然有问题，打开github，图片读取不出来，raw.githubxxx.xxx和www.google.com,这些网站都不能打开!谢谢!
