### ISSUE TITLE
是否支持订阅

### ISSUE THREAD

**Issue by debussyster** [kuoruan/luci-app-v2ray#17]
我收到的配置是一个订阅地址，列表也是vmess协议格式的，不知道怎么用在这个上面。

**Comment by kuoruan** [comment]
你的订阅地址的具体内容格式是怎么样的？

**Comment by debussyster** [comment]
https://v2.xxxx.com/link/BhzuFcOlz8HModuY?sub=3&extend=1，抱歉做了一下特殊处理

**Comment by debussyster** [comment]
列表是很多vmess://eyJob3开头的一串这样格式的

**Comment by debussyster** [comment]
我的路由器是斐讯K3，刷的LEDE，安装了您的v2ray和luci，没有找到类似koolshare的v2ray插件那种订阅功能。

**Comment by ttimasdf** [comment]
你这个补充没有信息量啊……

我随便建了一个配置，内容如下：
![image](https://user-images.githubusercontent.com/2762704/65672888-5f3e5d80-e07c-11e9-82ca-944a0a3a2109.png)

用客户端生成vmess链接如下：
```
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIiIsDQogICJhZGQiOiAidGVzdC52eHh4eC5jb20iLA0KICAicG9ydCI6ICIyMzMzMyIsDQogICJpZCI6ICI3ZDgzZjQzMC1kNzA3LTQxNDUtYjJjMi0zOTllMDA1Y2JlZjkiLA0KICAiYWlkIjogIjY2NiIsDQogICJuZXQiOiAidGNwIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIiIsDQogICJ0bHMiOiAidGxzIg0KfQ==
```
vmess后面是一个base64编码的json字符串，内容如下：

```json
{
  "v": "2",
  "ps": "",
  "add": "test.vxxxx.com",
  "port": "23333",
  "id": "7d83f430-d707-4145-b2c2-399e005cbef9",
  "aid": "666",
  "net": "tcp",
  "type": "none",
  "host": "",
  "path": "",
  "tls": "tls"
}
```

OP提到的订阅地址就是一个URL，内容就是一行一个vmess链接，纯文本格式。这玩意应该是标准格式吧，毕竟各个客户端都能识别。

**Comment by debussyster** [comment]
因为我的信息不方便公开，感谢楼上提供详细的配置信息。目前这个luci还不会用，没有找到直接输入vmess信息就可以配置一个v2ray服务器的地方，如果有直接导入订阅更好。

**Comment by kunxiang1** [comment]
确实，现在的交流方式都是订阅地址。那个lean的luci就支持订阅，参考：
[https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-ssr-plus](url)

**Comment by kuoruan** [comment]
不好意思，我没用过订阅，也不知道想具体实现什么？自动获取列表并设置为透明代理？
我所有的服务器都是自建的。

**Comment by kuoruan** [comment]
况且你这属于自创协议吧？里边的具体内容也没个说明
自创协议谁有谁的说法，也没个标准

**Comment by kunxiang1** [comment]
众所周知的原因，服务器死得特别快。老是更新服务器比较烦，所以一些飞机场就启用了订阅，这样只要记住一个地址就行了，有变更刷新一下就可以了。具体的实现应该像@ttimasdf说的，里面是json。通过wget的方式下载回来一个文本文件，加到服务器设置文件里。
我不懂编程胡猜的。

**Comment by shynome** [comment]
订阅功能说明的链接是这个
[https://github.com/2dust/v2rayN/wiki/订阅功能说明](https://github.com/2dust/v2rayN/wiki/订阅功能说明)

**Comment by kuoruan** [comment]
@shynome 这个东西只是这个 v2rayN 的作者定的，并没有官方支持吧

**Comment by shynome** [comment]
所有的订阅功能, 分享链接都是根据这个来做的,  可以说是事实标准了, 有没有官方支持都无所谓了

**Comment by ttimasdf** [comment]
v2ray/v2ray-core#1487 和 v2ray/v2ray-core#1569 拟定了SIP002和FOV001两种链接格式标准，我只试过V2rayN支持SIP002，但是说实话我感觉luci里支持订阅没啥用。因为很难判断哪个节点是可用的。

我个人的用法是在内网RPi开一个 [Clash](https://github.com/Dreamacro/clash) 更新订阅并测速，然后再写个脚本通过Clash的API读取最快节点，再同步到openwrt上v2ray的配置文件里去。供参考

**Comment by AlexYe233** [comment]
非常感谢您的软件
大佬是否考虑下从某个url定期更新vmess链接的功能

**Comment by cart88** [comment]
这个可以开一个bug,我有兴趣写写。
