### ISSUE TITLE
代理模式的4种模式区别

### ISSUE THREAD

**Issue by q629988171** [kuoruan/luci-app-v2ray#180]
1. 默认 : 智能模式（国内网站直连，国外网站走代理，通过IP地址判断）
2. 直连CN : 白名单模式（名单内的网站直连）
3. 代理CN : 全局模式（所有网站走代理）
4. 代理GFWList : 黑名单模式（名单内的网站走代理）

我这样的理解✔❓，有✖的地方欢迎指教。谢谢。

**Comment by kuoruan** [comment]
1. 默认是指所有的请求全部转发给 V2RAY
2. 直连 CN，指目标 IP 是国内地址的直连，剩下的转发给 V2RAY
3. 代理 CN，指目标 IP 是国内地址的转发给 V2RAY，剩下的直连
4. 代理 GFWLIST，指目标域名在 GFWLIST 中时，转发给 V2RAY，剩下的直连

流量进入 V2RAY 之后，还会走 V2RAY 的路由过滤一遍。
