### ISSUE TITLE
Use ss-rules from luci-app-shadowsocks to setup iptables rules

### ISSUE THREAD

**Issue by poscat0x04** [kuoruan/luci-app-v2ray#19]
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Instruction-of-ss-rules
ss-rules is much more configurable and flexible

**Comment by kuoruan** [comment]
Already added some iptables rules like ss-rule do.

related to https://github.com/kuoruan/luci-app-v2ray/issues/14#issuecomment-530241198
