### ISSUE TITLE
透明代理与mwan3的兼容性问题

### ISSUE THREAD

**Issue by lialosiu** [kuoruan/luci-app-v2ray#191]
场景
------

因需要在单根网线上分别传输普通流量和iptv的流量，需要mwan3做多wan，机顶盒的流量走iptv的pppoe，普通流量走上网的pppoe出口。

mwan3的规则是这样配置的：

![Snipaste_2020-06-21_02-33-54](https://user-images.githubusercontent.com/1682158/85209090-b81af800-b367-11ea-8b5f-12c87f369fd5.jpg)

10.1.1.92是我机顶盒的ip，mwan3把来源是这个ip的流量打到iptv拨号对应的接口上出站
其他 0.0.0.0/0 流量走上网pppoe拨号的wan接口上出站

问题
------

v2ray透明代理下，如果勾选TProxy，则透明代理不生效，感觉是流量直接从默认网关直接出了（可能是mwan3的规则优先级比较高？

![图片](https://user-images.githubusercontent.com/1682158/85209103-cec14f00-b367-11ea-9b4f-19b0b2783d7e.png)

也许和这个问题产生的原因差不多？ #91 

如果不勾选TProxy，则会出现v2ray内存占用疯狂上涨，直到爆满，然后openwrt巨卡，控制台提示table full

如果停止mwan3服务，则v2ray的透明代理恢复正常

请问有啥可用的解决方案吗？ m(_ _)m

**Comment by snakwu** [comment]
我开tproxy，直接不能访问国外！

**Comment by lialosiu** [comment]
![Snipaste_2020-07-13_16-33-21](https://user-images.githubusercontent.com/1682158/87282187-9a841d00-c526-11ea-9d96-af23f8cb6161.jpg)

今天抽空再测试了一下这个问题，报错信息如图^

**Comment by lialosiu** [comment]
终于找到了个变通的方法，可以凑合着临时解决此问题：

关闭本插件中的透明代理，并将生成的配置json文件复制一份
然后将 dokodemo-door 配置中的 followRedirect 设置为 true，手动指定加载此配置文件
安装 [luci-app-transparent-proxy](https://github.com/techotaku/luci-app-transparent-proxy) 插件
并将 luci-app-transparent-proxy 透传端口设置为dokodemo-door 入站端口

这种模式测试可用

估计是 luci-app-transparent-proxy 的 iptables 的配置可以和 mwan3 兼容
等哪天有空我研究下能不能把他的规则搬过来吧（

**Comment by lialosiu** [comment]
![Snipaste_2020-07-13_18-34-36](https://user-images.githubusercontent.com/1682158/87295323-97ddf380-c537-11ea-9bfa-4ffc6791fae3.jpg)

![Snipaste_2020-07-13_18-34-43](https://user-images.githubusercontent.com/1682158/87295328-9a404d80-c537-11ea-98e1-4b045bd928ea.jpg)

本插件的 iptables 长这样，在prerouting链的最下面，有可能是难道是因为这个导致的？

**Comment by snakwu** [comment]
我用mwan3时，开tp模式，也同样不能fq，然后直接把mwan3插件删掉，就正常了

**Comment by ttimasdf** [comment]
mwan3插入的规则在PREROUTING链中，其规则优先级高于 V2RAY链，故V2RAY不会生效。而且从本质上讲能不能兼容不太好说，因为都是从iptables把流量转发到应用层某个端口上，是不是只能达到某些流量用v2ray处理，return回来（国内分流）的流量用 mwan3 处理？这样mwan就没有意义了吧。

**Comment by ttimasdf** [comment]
如果OP仅仅是一个网络隔离或分网段路由的需求，单纯的用iptables就可以解决……LUCI里有一个菜单叫静态路由，加一条设置把IPTV的网段指到对应WAN口的网关IP就行了。

其实我感觉很多问题都没必要上mwan3，规则太复杂，和v2ray差不多了，作为一个路由管理还不够（不能替代v2ray），链接状态管理又太重了（家庭用户手动设置一个 metric 就足够了）

**Comment by snakwu** [comment]
> 如果OP仅仅是一个网络隔离或分网段路由的需求，单纯的用iptables就可以解决……LUCI里有一个菜单叫静态路由，加一条设置把IPTV的网段指到对应WAN口的网关IP就行了。或者干脆创建个VLAN，把IPTV的网口单独拉到一个VLAN里，上游连接到对应的WAN。这都比鼓捣mwan的iptables容易的多。
> 
> 其实我感觉很多问题都没必要上mwan3，规则太复杂，和v2ray差不多了，作为一个路由管理还不够（不能替代v2ray），链接状态管理又太重了（家庭用户手动设置一个 metric 就足够了）

所以，我已经放弃mwan3了，之前是为了多拨，还有，这个luci的v2ray还有很多不足的地方，单ip控制不了走国外规则，好像作者也不怎么更新了，最后一次更新，差不多快半年了！

**Comment by lialosiu** [comment]
问题就是，我软路由到下游只有一根网线，没法划分多网段。。。vlan的话，要下游再搞个带管交换机才行

Tim Zhang <notifications@github.com> 于 2020年10月7日周三 11:15写道：
