### ISSUE TITLE
安装完成后进入v2ray界面报错

### ISSUE THREAD

**Issue by yang229** [kuoruan/luci-app-v2ray#198]
固件版本:Openwrt Koolshare mod V2.35 r14297-5efd32232b
内核版本:5.4.41
安装步骤: opkg install v2ray-core
                 opkg install luci-app-v2ray
                 opkg install luci-i18n-v2ray-zh-cn
故障描述:安装完成后打开service->v2ray界面报错，错误提示“权限不足，无法读取UCI配置。”，仅关于界面可以正常使用，其余界面均无法显示。由于配置是恢复的，功能正常。

**Comment by jdkcn** [comment]
我也是这样。
Openwrt Koolshare mod V2.36 r14941-67f6fa0a30
