### ISSUE TITLE
[Feature request] 支持自定义 ipset v2ray_dst_direct_v4

### ISSUE THREAD

**Issue by StoneMoe** [kuoruan/luci-app-v2ray#200]
目前正在使用v2ray的路由功能，打通两个异地内网，但v2ray_dst_direct_v4直接过滤掉了内网段的dst
希望可以在web ui中支持自定义这些内置的ipset，来做一些细粒度的自定义

**Comment by StoneMoe** [comment]
如果不方便的话，我可以尝试pr一下，但对openwrt相关开发不是很熟悉

**Comment by nobk** [comment]
帮你搜索了一下，v2ray_dst_direct_v4在/etc/init.d/v2ray这个脚本里面，属于bash脚本开发
