### ISSUE TITLE
额外直连列表不起作用

### ISSUE THREAD

**Issue by Aaronwang81** [kuoruan/luci-app-v2ray#208]
透明代理中配置了额外直连列表，保存并应用后，在配置文件中找不到对应的配置。但透明代理页面的配置还在。
另外，在透明代理页，有时候点【保存并应用】不会生效，会自动跳到页面顶部，需要取消【桥接『br-lan』】生才能保存生效。且被取消的勾选会自动重新勾选。

**Comment by nobk** [comment]
透明代理的额外的直连列表功能不在v2ray的配置文件中，用的是iptables ipset技术，自然在v2ray的那个配置文件里面找不到。
那个列表保存在/etc/v2ray/srcdirectlist.txt，被应用在ipset中，通过命令行
`ipset list v2ray_src_direct_v4`
可以查看是否已经生效。

**Comment by Aaronwang81** [comment]
> 透明代理的额外的直连列表功能不在v2ray的配置文件中，用的是iptables ipset技术，自然在v2ray的那个配置文件里面找不到。
> 那个列表保存在/etc/v2ray/srcdirectlist.txt，被应用在ipset中，通过命令行
> `ipset list v2ray_src_direct_v4`
> 可以查看是否已经生效。
看了，生效了

/etc/v2ray/srcdirectlist.txt 是空的
应该是/etc/v2ray/directlist.txt
命令应该是：ipset list v2ray_dst_direct_v4，-_-
