### ISSUE TITLE
全局设置无法选出入站连接

### ISSUE THREAD

**Issue by EdisonzhoNG0623** [kuoruan/luci-app-v2ray#216]
![Screenshot_20200707-094924](https://user-images.githubusercontent.com/30425893/86686929-56c97900-c037-11ea-9381-d6143c7c9287.png)

**Comment by EdisonzhoNG0623** [comment]
看别人的配置教程，下面都有好多选项，是我安装失败了吗？

**Comment by EdisonzhoNG0623** [comment]
![Screenshot_20200707-095118](https://user-images.githubusercontent.com/30425893/86687166-82e4fa00-c037-11ea-9fc4-571eef14c453.png)

**Comment by EdisonzhoNG0623** [comment]
@kuoruan

**Comment by EdisonzhoNG0623** [comment]
大佬麻烦帮忙看看

**Comment by kuoruan** [comment]
使用自定义配置文件时没有具体的选项

**Comment by EdisonzhoNG0623** [comment]
> 使用自定义配置文件时没有具体的选项

好的谢谢
