### ISSUE TITLE
iptables的转发读取额外的配置文件

### ISSUE THREAD

**Issue by Herts** [kuoruan/luci-app-v2ray#22]
目前使用环境：软路由作为透明代理，使用节点A作为代理。
个人在使用的时候有可能需要使用节点B，这个时候按照我的理解：
访问请求->电脑V2RAY->软路由->V2RAY->节点A->节点B->网站。

我在Openwrt中防火墙自定义规则中配置了：
iptables -t nat -N V2RAYDIRECT
iptables -t nat -A V2RAYDIRECT -d $(dig +short 节点B地址) -j RETURN
iptables -t nat -A PREROUTING -j V2RAYDIRECT

但是每次添加节点地址重启防火墙时会造成luci-app-v2ray配置的规则丢失，因此我想把这个加入到luci-app-v2ray中。手工修改服务启动文件的方法我也看到了，如果能有一个GUI中有额外配置或者读取配置的方法会更好一些。

**Comment by Herts** [comment]
参考了这个：https://gitee.com/felix-fly/v2ray-dnsmasq-dnscrypt
该项目的cn.conf要用ipset读取， 在iptables中直接绕过。

我根据该项目的思路进行改写：
/etc/init.d/v2ray
```bash
        # ToutyRater/v2ray-guide#24
        ipset -R < /etc/v2ray/cn.conf # load the cn.conf
        iptables-restore --noflush <<-EOF 2>/dev/null
                *nat
                :V2RAY -                                
                $(for s in $server_ips ; do echo "-A V2RAY -d $s -j RETURN" ; done)
                $(for r in $reserved_ips ; do echo "-A V2RAY -d $r -j RETURN" ; done)
                -A V2RAY -m set --match-set cn dst -j RETURN # return the traffic directly            
                -A V2RAY -p tcp -j REDIRECT --to-ports $port
                -A PREROUTING -p tcp -j V2RAY
                #-A OUTPUT -p tcp -j V2RAY 
                COMMIT              
        EOF
```
cn.conf
```bash
create cn hash:net family inet hashsize 1024 maxelem 65536
add cn 1.0.1.0/24
add cn 1.0.2.0/23
...
add cn 223.255.252.0/23
```

据此可以再添加一个custom.conf，用同样的方法直接避开v2ray。

**Comment by Herts** [comment]
目前自己fork了一个版本加入了这个功能，但是还有待完善：
1. ipset成为项目依赖包
2. 无GUI界面
3. UDP转发未做相应处理。

不过明显改善当前ssh断联的情况。

**Comment by kuoruan** [comment]
服务重启的时候会将所有包含 V2RAY 的规则给清除掉，所以你指定一个不含 V2RAY 的表名就行了

https://github.com/kuoruan/luci-app-v2ray/blob/88a4a3d570d1001db4deeca3dbc73843544165bb/root/etc/init.d/v2ray#L288

**Comment by Herts** [comment]
> 服务重启的时候会将所有包含 V2RAY 的规则给清除掉，所以你指定一个不含 V2RAY 的表名就行了
> 
> https://github.com/kuoruan/luci-app-v2ray/blob/88a4a3d570d1001db4deeca3dbc73843544165bb/root/etc/init.d/v2ray#L288

是我想在luci中的firewall中配置规则，然后这里的规则重启防火墙才能生效，但也会导致目前正在运行的V2RAY规则被清空。
