### ISSUE TITLE
能否给一个json配置样板

### ISSUE THREAD

**Issue by poemsiu** [kuoruan/luci-app-v2ray#23]
已经装好了，还不太会使用，作者能否给点json样板以供参考？

**Comment by hcym** [comment]
就是内置的改参数，然后透明传输什么的都选上勾，应用。我用的tcp和mkcp都正常，内置去广告也行，就是ipv6不行，这个有点要命，两个vps都是半身不遂只能用ipv6

**Comment by poemsiu** [comment]
> 就是内置的改参数，然后透明传输什么的都选上勾，应用。我用的tcp和mkcp都正常，内置去广告也行，就是ipv6不行，这个有点要命，两个vps都是半身不遂只能用ipv6

可以分享一下你的配置截图吗 万分感谢

**Comment by hcym** [comment]
前面博主有发过模板的，你找找关闭的帖子，我也是看了照猫画虎

**Comment by poemsiu** [comment]
> 前面博主有发过模板的，你找找关闭的帖子，我也是看了照猫画虎

你是直接丢的json还是用界面配置的？

**Comment by hcym** [comment]
界面，必须界面，试过自己的不行

**Comment by hcym** [comment]
非常遗憾不能用ipv6，已经用大雕的了

**Comment by poemsiu** [comment]
@hcym 你是指大雕的ssr plus+么？ 我也用过 本地策略无法配置 tcp+http伪装还有故障

**Comment by kuoruan** [comment]
@hcym ipv6 不能用是指无法填写 ipv6 地址吗？现在确实有这个问题，我可以处理一下，先允许填写 ipv6，后期再看支持问题

**Comment by hcym** [comment]
无意中发现的，以前都是4的，这次死人节都挂了，除了机场我自己的vps只有ipv6可用，呵呵😄，谢谢大佬

**Comment by hcym** [comment]
哦，地址没问题，就是不能用，估计是缺规则吧，不急不急
