### ISSUE TITLE
期待大师能给出各个配置界面的截图，方便小白们照猫画虎。

### ISSUE THREAD

**Issue by szhhq** [kuoruan/luci-app-v2ray#24]
vps、pc和手机上都设置好了，能顺利使用，但是搞不定这个路由器设置啊！vps、pc、手机上的配置文件也就一两个，各种设置参数都在这一两个文件里。现在这个luci有这么多的配置框，都不知哪个参数要填在哪个框里？

**Comment by kuoruan** [comment]
大部分配置并不会自动生成，需要熟悉 v2ray 配置文件的格式。
不适合小白使用。
