### ISSUE TITLE
入站连接中transparent_proxy无法自定义timeout

### ISSUE THREAD

**Issue by poemsiu** [kuoruan/luci-app-v2ray#25]
由于入站透明代理setting中timeout默认值为30，导致安卓设备gms服务长连接频繁断开重连，耗电严重，遂尝试取消自动透明代理手动写入配置`{
				"network": "tcp",
				"timeout": 999,
				"followRedirect": true
			}`
![image](https://user-images.githubusercontent.com/28263140/66718313-2f7dac80-ee15-11e9-8818-77adf0e21536.png)

结果却无法正常透明代理，求助。

**Comment by kuoruan** [comment]
在不选择透明代理时，不会自动添加 iptables 规则，默认将 timeout 设置为了 30
我会将其改为配置选项，稍等。。

**Comment by poemsiu** [comment]
@kuoruan 感谢🙏
