### ISSUE TITLE
使用刚发布的最新版后出现国内网无法访问，路由器管理页面间歇性卡死

### ISSUE THREAD

**Issue by poemsiu** [kuoruan/luci-app-v2ray#26]
以下为部分错误日志
疑为Transparent proxy router's own network导致
`2019/10/15 08:22:06 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:06 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:07 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:07 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:08 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:08 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:09 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:09 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:10 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:10 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1081: accept4: too many open files
2019/10/15 08:22:11 [Warning] [2106317230] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 35.201.187.166:12595: socket: too many open files dial tcp 35.201.187.166:51279: socket: too many open files dial tcp 35.201.187.166:12595: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed`

**Comment by kuoruan** [comment]
ckecking...

**Comment by kuoruan** [comment]
我这里使用 vmess 是可以访问国内的，能贴一下你的配置文件吗？

**Comment by poemsiu** [comment]
@kuoruan 以下为配置
```
{
	"log": {
		"loglevel": "warning",
		"access": "\/usr\/info.log",
		"error": "\/usr\/bug.log"
	},
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn",
					"mtalk"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:speedtest"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:category-ads-all"
				],
				"outboundTag": "block"
			}
		]
	},
	"policy": {
		"levels": {
			"0": {
				"handshake": 4,
				"connIdle": 9999,
				"uplinkOnly": 999,
				"downlinkOnly": 999,
				"statsUserUplink": false,
				"statsUserDownlink": false,
				"bufferSize": 4096
			}
		},
		"system": {
			"statsInboundUplink": false,
			"statsInboundDownlink": false
		}
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"tag": "transparent_proxy",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"settings": {
				"network": "tcp",
				"timeout": 999,
				"followRedirect": true
			}
		}
	],
	"outbounds": [
		{
			"sendThrough": "0.0.0.0",
			"protocol": "vmess",
			"tag": "proxy",
			"mux": {
				"enabled": false,
				"concurrency": 8
			},
			"settings": {
				"vnext": [
					{
						"port": *****,
						"users": [
							{
								"id": "**************",
								"alterId": 233,
								"security": "auto"
							}
						],
						"address": "***.***.***.***"
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"tcpSettings": {
					"header": {
						"request": {
							"method": "GET",
							"path": [
								"\/tv"
							],
							"version": "1.1",
							"headers": {
								"Host": [
									"ltevod.tv189.cn"
								]
							}
						},
						"type": "http"
					}
				},
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "freedom",
			"tag": "direct",
			"mux": {
				"enabled": false,
				"concurrency": 8
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "blackhole",
			"tag": "block",
			"mux": {
				"enabled": false,
				"concurrency": 8
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		}
	]
}
```

**Comment by kuoruan** [comment]
更新了一下 iptables，你替换你的 ```/etc/init.d/v2ray``` 为

https://github.com/kuoruan/luci-app-v2ray/raw/master/root/etc/init.d/v2ray

再试试

**Comment by poemsiu** [comment]
> 更新了一下 iptables，你替换你的 `/etc/init.d/v2ray` 为
> 
> https://github.com/kuoruan/luci-app-v2ray/raw/master/root/etc/init.d/v2ray
> 
> 再试试

换了这个文件后，并且关闭opemwrt网络选项卡中的DNS加速功能后，使用暂时一切正常。也不知道是哪个起作用了。

**Comment by kuoruan** [comment]
我这里现在倒是无法访问国内网站了，我再研究一下

**Comment by poemsiu** [comment]
@kuoruan 大佬怎么样了 能完美解决不

**Comment by poemsiu** [comment]
@kuoruan 刚更新的版本还是一样的问题 改了你给的文件也不行

**Comment by kuoruan** [comment]
具体问题？表现？

**Comment by poemsiu** [comment]
> 具体问题？表现？

无法访问国内网 软路由风扇狂转 路由器界面卡死

**Comment by kuoruan** [comment]
查看一下你的防火墙规则，是否存在循环规则

**Comment by kuoruan** [comment]
```
iptables -t nat -nL
```

或者 LuCI 界面上的防火墙

```/etc/init.d/v2ray``` 第 270 行 注释掉即可

```
#-A OUTPUT -p tcp -j V2RAY
```

**Comment by poemsiu** [comment]
谢谢
