### ISSUE TITLE
透明代理中的转发udp启用之后无法正常使用192.168.1.1作为dns服务器

### ISSUE THREAD

**Issue by shirakun** [kuoruan/luci-app-v2ray#262]
RT
当转发 UDP被勾选后通过本机`nslookup google.com 192.168.1.1`进行测试提示`;; connection timed out; no servers could be reached`
但关闭转发 UDP之后则可以正常解析域名
此外还通过`nslookup google.com 8.8.8.8`进行测试,当转发udp开启时正常返回结果,但关闭后则返回被污染的结果

尝试通过在 额外的直连列表 和 本地设备直接连出列表 中添加192.168.1.1
但问题依旧未能解决.

**Comment by suyar** [comment]
我打开了转发 UDP 但是返回了被污染的地址：
```
$ nslookup toutyrater.github.io 192.168.100.1
服务器:  OpenWrt.lan
Address:  192.168.100.1

非权威应答:
名称:    toutyrater.github.io
Addresses:  127.0.0.1
          127.0.0.1
```
但是使用谷歌的 dns 则返回正确的地址：
```
$ nslookup toutyrater.github.io 8.8.8.8
服务器:  dns.google
Address:  8.8.8.8

名称:    toutyrater.github.io
Addresses:  185.199.108.153
          185.199.109.153
          185.199.111.153
          185.199.110.153
```

我怀疑启用透明代理后，UDP 流量没有成功被转发到 v2ray

<details>
<summary>这是我的配置文件，点击打开：</summary>
<pre>
{
    "log": {
        "access": "/dev/null",
        "loglevel": "warning",
        "error": "/var/log/v2ray-error.log"
    },
    "dns": {
        "servers": [
            "1.1.1.1",
            {
                "address": "8.8.8.8",
                "port": 53,
                "domains": [
                    "geosite:google",
                    "geosite:geolocation-!cn",
                    "geosite:facebook",
                    "github"
                ]
            },
            {
                "address": "114.114.114.114",
                "port": 53,
                "domains": [
                    "geosite:cn"
                ]
            },
            {
                "address": "223.5.5.5",
                "port": 53,
                "domains": [
                    "geosite:cn"
                ]
            }
        ]
    },
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private",
                    "geoip:cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "protocol": [
                    "bittorrent"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "port": "53",
                "network": "udp",
                "inboundTag": [
                    "transparent"
                ],
                "outboundTag": "dns_out"
            },
            {
                "type": "field",
                "ip": [
                    "114.114.114.114",
                    "223.5.5.5"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "1.1.1.1",
                    "8.8.8.8"
                ],
                "outboundTag": "proxy"
            },
            {
                "type": "field",
                "port": "123",
                "network": "udp",
                "inboundTag": [
                    "transparent"
                ],
                "outboundTag": "direct"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
            },
            "streamSettings": {
                "sockopt": {}
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
            "listen": "0.0.0.0",
            "port": 1081,
            "protocol": "dokodemo-door",
            "settings": {
                "followRedirect": true,
                "network": "tcp,udp"
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy"
                }
            },
            "tag": "transparent",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "mo-xxxxxxxx",
                        "port": 8333,
                        "users": [
                            {
                                "id": "2fce6d4f-4347-0bdxxxxxxxxxxxxxx",
                                "alterId": 2,
                                "security": "aes-128-gcm",
                                "level": 2
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "headers": {
                        "moxxxxxx": "moxxxxx"
                    }
                },
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "block"
        },
        {
            "protocol": "dns",
            "settings": {},
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "dns_out"
        }
    ]
}
</pre>
</details>

这是我的透明代理截图：
![image](https://user-images.githubusercontent.com/15704489/92329003-3188d380-f097-11ea-9921-86ffe2c3ef35.png)

问题还未解决

**Comment by shirakun** [comment]
> 我使用的版本是：`v2.0.0-1`
> 
> 我打开了转发 UDP 但是返回了被污染的地址：
> 
> ```
> $ nslookup toutyrater.github.io 192.168.100.1
> 服务器:  OpenWrt.lan
> Address:  192.168.100.1
> 
> 非权威应答:
> 名称:    toutyrater.github.io
> Addresses:  127.0.0.1
>           127.0.0.1
> ```
> 
> 但是使用谷歌的 dns 则返回正确的地址：
> 
> ```
> $ nslookup toutyrater.github.io 8.8.8.8
> 服务器:  dns.google
> Address:  8.8.8.8
> 
> 名称:    toutyrater.github.io
> Addresses:  185.199.108.153
>           185.199.109.153
>           185.199.111.153
>           185.199.110.153
> ```
> 
> 我怀疑启用透明代理后，UDP 流量没有成功被转发到 v2ray
> 
> 这是我的配置文件，点击打开：
> 这是我的透明代理截图：
> ![image](https://user-images.githubusercontent.com/15704489/92329003-3188d380-f097-11ea-9921-86ffe2c3ef35.png)
> 
> 防火墙状态：
> ![image](https://user-images.githubusercontent.com/15704489/92329362-8af20200-f099-11ea-85a1-9c9937679fb3.png)
> 
> 补充：
> 根据v2ray access-log 显示，udp直连到192.168.100.1:53，看起来像是没有经过v2ray的dns，而直接走到了运营商的dns，运营商的dns 218.85.157.99 是有污染的
> 
> 问题还未解决

网络->dhcp/dns->host和解析文件, 勾选忽略解析文件->保存&应用

**Comment by shirakun** [comment]
问题已经解决,原因是设置透明代理后,客户端的连接也被转到v2ray进行处理
解决方法:
在出站连接添加一个freedom的接口,在路由中添加路由,匹配ip:192.168.0.0/16 出口设置为前面配置的freedom接口即可

**Comment by suyar** [comment]
> > 我使用的版本是：`v2.0.0-1`
> > 我打开了转发 UDP 但是返回了被污染的地址：
> > ```
> > $ nslookup toutyrater.github.io 192.168.100.1
> > 服务器:  OpenWrt.lan
> > Address:  192.168.100.1
> > 
> > 非权威应答:
> > 名称:    toutyrater.github.io
> > Addresses:  127.0.0.1
> >           127.0.0.1
> > ```
> > 
> > 
> > 但是使用谷歌的 dns 则返回正确的地址：
> > ```
> > $ nslookup toutyrater.github.io 8.8.8.8
> > 服务器:  dns.google
> > Address:  8.8.8.8
> > 
> > 名称:    toutyrater.github.io
> > Addresses:  185.199.108.153
> >           185.199.109.153
> >           185.199.111.153
> >           185.199.110.153
> > ```
> > 
> > 
> > 我怀疑启用透明代理后，UDP 流量没有成功被转发到 v2ray
> > 这是我的配置文件，点击打开：
> > 这是我的透明代理截图：
> > ![image](https://user-images.githubusercontent.com/15704489/92329003-3188d380-f097-11ea-9921-86ffe2c3ef35.png)
> > 防火墙状态：
> > ![image](https://user-images.githubusercontent.com/15704489/92329362-8af20200-f099-11ea-85a1-9c9937679fb3.png)
> > 补充：
> > 根据v2ray access-log 显示，udp直连到192.168.100.1:53，看起来像是没有经过v2ray的dns，而直接走到了运营商的dns，运营商的dns 218.85.157.99 是有污染的
> > 问题还未解决
> 
> 网络->dhcp/dns->host和解析文件, 勾选忽略解析文件->保存&应用
> 推荐dns使用chinadns+forwarder

目前不想使用chinadns，问题依旧没解决
