### ISSUE TITLE
WebSocket+TLS+Web 无法正常走代理

### ISSUE THREAD

**Issue by zdz2019** [kuoruan/luci-app-v2ray#27]
更新到最新的1.30版后，无法正常代理上网，只能正常访问国内，
换回1.2.3版后则能正常代理，
我使用的是WebSocket+TLS+Web方式，
以下是部分调试日志：
2019/10/15 16:30:27 [Info] [886902391] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:mydomain.***.***:443
2019/10/15 16:30:27 [Info] [961627686] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 62 but actually 80
2019/10/15 16:30:27 [Info] [961627686] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2019/10/15 16:30:27 [Debug] [113739468] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.1.240:11643
2019/10/15 16:30:27 [Info] [113739468] v2ray.com/core/app/dispatcher: sniffed domain: clients1.google.com
2019/10/15 16:30:27 [Info] [113739468] v2ray.com/core/app/dispatcher: taking detour [v2ray] for [tcp:clients1.google.com:443]
2019/10/15 16:30:27 [Info] [113739468] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:mydomain.***.***:443
2019/10/15 16:30:27 [Info] [886902391] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:play.google.com:443 via tcp:mydomain.***.***:443
2019/10/15 16:30:27 [Info] [1247215546] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:play.google.com:443 via tcp:mydomain.***.***:443
2019/10/15 16:30:27 [Info] [113739468] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients1.google.com:443 via tcp:mydomain.***.***:443
2019/10/15 16:30:27 [Info] [1247215546] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 20 but actually 108
2019/10/15 16:30:27 [Info] [886902391] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 78 but actually 44
2019/10/15 16:30:27 [Info] [886902391] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2019/10/15 16:30:27 [Info] [1247215546] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2019/10/15 16:30:27 [Info] [113739468] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 189 but actually 217
2019/10/15 16:30:27 [Info] [113739468] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2019/10/15 16:30:27 [Debug] [2292789070] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.1.240:11644
2019/10/15 16:30:27 [Info] [2292789070] v2ray.com/core/app/dispatcher: sniffed domain: clients1.google.com
2019/10/15 16:30:27 [Info] [2292789070] v2ray.com/core/app/dispatcher: taking detour [v2ray] for [tcp:clients1.google.com:443]
2019/10/15 16:30:27 [Info] [2292789070] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:mydomain.***.***:443
2019/10/15 16:30:27 [Info] [2292789070] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients1.google.com:443 via tcp:mydomain.***.***:443
2019/10/15 16:30:27 [Debug] [2162470646] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.1.240:11645
2019/10/15 16:30:27 [Info] [2162470646] v2ray.com/core/app/dispatcher: sniffed domain: play.google.com
2019/10/15 16:30:27 [Info] [2162470646] v2ray.com/core/app/dispatcher: taking detour [v2ray] for [tcp:play.google.com:443]
2019/10/15 16:30:27 [Info] [2162470646] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:mydomain.***.***:443
2019/10/15 16:30:28 [Info] [2292789070] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 54 but actually 247
2019/10/15 16:30:28 [Info] [2292789070] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe

**Comment by kuoruan** [comment]
related to #26

**Comment by zdz2019** [comment]
最新的1.3.1版已下载测试，依然无法正常代理，
访问国外网站，浏览器表现为提示
“无法安全地连接到此页面“
”这可能是因为该站点使用过期的或不安全的 TLS 安全设置。如果这种情况持续发生，请与网站的所有者联系。“
感觉可能和dns转发有关，我使用了透明代理DNS流量和v2ray内置的dns服务。

**Comment by kuoruan** [comment]
贴一下你的配置文件？

**Comment by zdz2019** [comment]
{
	"log": {
		"loglevel": "warning",
		"access": "\/var\/log\/v2ray-access.log",
		"error": "\/var\/log\/v2ray-error.log"
	},
	"dns": {
		"servers": [
			{
				"address": "208.67.222.222",
				"port": 53
			},
			{
				"address": "8.8.8.8",
				"port": 53
			},
			{
				"address": "114.114.114.114",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			},
			{
				"address": "223.5.5.5",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"domain": [
					"ext:h2y.dat:gfw"
				],
				"outboundTag": "v2ray"
			},
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"transparent_proxy"
				],
				"outboundTag": "dns_out"
			}
		]
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"tag": "transparent_proxy",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"settings": {
				"network": "tcp,udp",
				"timeout": 300,
				"followRedirect": true
			}
		}
	],
	"outbounds": [
		{
			"sendThrough": "0.0.0.0",
			"protocol": "freedom",
			"tag": "direct",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "vmess",
			"tag": "v2ray",
			"settings": {
				"vnext": [
					{
						"address": "www.baidu.com",
						"port": 443,
						"users": [
							{
								"id": "23ad6b10-8d1a-40f7-8ad0-e3e35cd38297",
								"alterId": 4
							}
						]
					}
				]
			},
			"streamSettings": {
				"proxy": {
					"network": "ws",
					"security": "tls",
					"wsSettings": {
						"path": "\/ray"
					}
				},
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "blackhole",
			"tag": "block",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "dns",
			"tag": "dns_out",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		}
	]
}

**Comment by kuoruan** [comment]
https://github.com/kuoruan/luci-app-v2ray/blob/312389b23bb72cc82a39d79d483514806c5844fb/root/etc/init.d/v2ray#L283-L295

把 293 行注释掉试试

**Comment by zdz2019** [comment]
还是不行。

**Comment by kuoruan** [comment]
https://github.com/kuoruan/luci-app-v2ray/blob/967d36aaefa786b00e9054a2ee853041122c91c5/root/etc/init.d/v2ray#L250-L252

你可以对比一下 1.2.3 和 1.3.1 对 ```/etc/init.d/v2ray``` 的 udp 转发规则的修改。
然后修改回去试试

**Comment by zdz2019** [comment]
把两个版本的配置文件进行仔细对比终于找到问题了。多了这个参数不知道什么时候复制进去的。现在删掉就好了。
![Snipaste_2019-10-17_20-05-08](https://user-images.githubusercontent.com/50648881/67007692-8982b880-f11a-11e9-9cc1-dd0d7c9d4eb2.png)
