### ISSUE TITLE
安装之后openwrt里面可以看见v2ray，但是V2Ray 文件 /usr/bin/v2ray    无法获取 V2Ray 版本信息

### ISSUE THREAD

**Issue by xnxy2012** [kuoruan/luci-app-v2ray#29]
安装之后openwrt里面可以看见v2ray，但是V2Ray 文件 /usr/bin/v2ray    无法获取 V2Ray 版本信息，请问是什么情况，实在是不想编译，想直接安装，有没有好的解决方案

**Comment by kuoruan** [comment]
在命令行手动 ```v2ray --version``` 看看输出什么

**Comment by zydycjr** [comment]
root@OpenWrt:~# v2ray --version
-ash: v2ray: Permission denied

**Comment by zydycjr** [comment]
权限 +x 也没用。请问有建议吗

**Comment by tpaullee** [comment]
Do a pwd.  I vaguely remember that there is a v2ray directory above the v2ray binary.T.Paul
N 37-17.454 W 121-57.679 http://tpaullee.blogspot.com/ Cultivating Human Goodness 

    On Tuesday, March 24, 2020, 07:42:10 PM PDT, zydycjr <notifications@github.com> wrote:  
 
 


root@OpenWrt:~# v2ray --version
-ash: v2ray: Permission denied

**Comment by Kev1nZheng** [comment]
> 权限 +x 也没用。请问有建议吗

请问这个问题解决了么？
我尝试在raspberry pi 4B的docker上安装也遇到了同样的问题

**Comment by zydycjr** [comment]
Direct swap the v2ray file, mine was corrupted that lead to permission error.

**Comment by pcexpert007** [comment]
有可能是内核没安装，或者安装的版本不符合，以下命令从新安装v2内核

1、导入证书

wget -O kuoruan-public.key http://openwrt.kuoruan.net/packages/public.key
opkg-key add kuoruan-public.key
2、导入v2ray安装源

echo "src/gz kuoruan_packages http://openwrt.kuoruan.net/packages/releases/$(. /etc/openwrt_release ; echo $DISTRIB_ARCH)" \
  >> /etc/opkg/customfeeds.conf
3、更新软件包并安装
opkg update
opkg install v2ray-core

**Comment by h2ohorse** [comment]
> 有可能是内核没安装，或者安装的版本不符合，以下命令从新安装v2内核
> 
> 1、导入证书
> 
> wget -O kuoruan-public.key http://openwrt.kuoruan.net/packages/public.key opkg-key add kuoruan-public.key 2、导入v2ray安装源
> 
> ```
> echo "src/gz kuoruan_packages http://openwrt.kuoruan.net/packages/releases/$(. /etc/openwrt_release ; echo $DISTRIB_ARCH)" \
>   >> /etc/opkg/customfeeds.conf
> ```
> 
> 3、更新软件包并安装 opkg update opkg install v2ray-core

请教一下，在导入key的时候错误，提示
`/usr/sbin/opkg-key: line 58: usign: not found`
是什么问题？谢谢。
