### ISSUE TITLE
希望帮忙看一下我的设置，新手设置了一天有点迷茫

### ISSUE THREAD

**Issue by shuo4sell** [kuoruan/luci-app-v2ray#291]
![1全局](https://user-images.githubusercontent.com/38107095/96872810-afb60380-14a6-11eb-9a5e-9c45a940c79e.png)
![2入站](https://user-images.githubusercontent.com/38107095/96872820-b2185d80-14a6-11eb-9b57-08c0a51482d4.png)
![3出站](https://user-images.githubusercontent.com/38107095/96872825-b3498a80-14a6-11eb-811e-b1368d73c76d.png)
![4透明](https://user-images.githubusercontent.com/38107095/96872829-b3e22100-14a6-11eb-94a2-906ef319fbc5.png)
![5防火墙](https://user-images.githubusercontent.com/38107095/96872832-b5134e00-14a6-11eb-872b-c63e5cb2f0d4.png)
![6错误日志](https://user-images.githubusercontent.com/38107095/96873653-d163ba80-14a7-11eb-8214-5046ad7cd1a7.png)

以上很多设置是看了这边问题反馈下各网友解决办法的，可还是不行。个人主要怀疑是不是入站的监听、出站的发送IP地址，我设错了还是什么，也是反复尝试了几种选项无果。

目前能够确定出站鸡厂没问题（手机rocket能用），~~然后我这是放房间里的路由器，家门口一个路由器接外网，这台路由器是直接接墙上的网口（专业说法不太懂）。另外网络接口那里是LAN的IPv4: 192.168.1.1/24，WAN的IPv4: 192.168.1.106。实在是搞不太懂了，网上搜也都是软路由等各种魔改openwrt的教程~~。现在是未启用v2ray的状态（如图），启用了以后，什么网站都打不开。本人知识有限，希望能有大佬指点一下！能够简单指点到能用也可，详细介绍一下各种设置或者留下一个链接学习也可，先谢谢了！

**Comment by shuo4sell** [comment]
还有两个补充
1、启用了打不开任何网页，但是能登qq，可是我这边dns也没做修改，不知道原因
2、最后一图是我启用后报的错，发现时间和当前时间不一致，是不是哪里有问题？op里面我选的HK，本地时间显示的刚才也正常是八点多

**Comment by shynome** [comment]
你就直接改outbound里的那个vmess的, 不要自己新加, 新加的用不了, 我也不知道为啥

**Comment by shuo4sell** [comment]
> 你就直接改outbound里的那个vmess的, 不要自己新加, 新加的用不了, 我也不知道为啥

谢谢回复，还是不行，我基本是按照他的设置来的
https://github.com/kuoruan/luci-app-v2ray/issues/110#issuecomment-599199306
现在问题就是开启以后任何网页都打不开
![image](https://user-images.githubusercontent.com/38107095/96992785-ed756380-155c-11eb-8afe-689817403df6.png)
应该跟他是一样的问题，但是他的解决办法我没太看懂，有没有大佬一样的知道怎么解决的，还是说根源还是我的设置有问题
https://github.com/kuoruan/luci-app-v2ray/issues/192#issue-642561234

**Comment by shynome** [comment]
1. 关闭 v2ray
1. 把 `/etc/config/v2ray` 文件里的内容换成下面那个, 刷新页面看到新的配置
1. 修改 outbound 的 proxy 为有效的配置
1. 启动 v2ray
这样操作下来应该就没问题了
```conf

config v2ray 'main'
	option v2ray_file '/usr/bin/v2ray'
	option access_log '/dev/null'
	option error_log '/var/log/v2ray-error.log'
	option loglevel 'error'
	list outbounds 'vmess'
	list outbounds 'direct'
	list outbounds 'block'
	list outbounds 'dns_out'
	list inbounds 'socks_proxy'
	list inbounds 'dokodemo_door'
	option mem_percentage '80'
	option enabled '0'

config dns 'main_dns'
	option enabled '1'
	list hosts 'example.com|127.0.0.1'
	option servers 'cloudflare_dns_1 google_dns_1 114_dns_1 ali_dns_1'

config dns_server 'cloudflare_dns_1'
	option alias 'cloudflare_dns_1'
	option address '1.1.1.1'

config dns_server 'google_dns_1'
	option alias 'google_dns_1'
	option address '8.8.8.8'

config dns_server 'op_dns_1'
	option alias 'op_dns_1'
	option address '208.67.222.222'
	option port '5353'

config dns_server '114_dns_1'
	option alias '114_dns_1'
	option address '114.114.114.114'
	option port '53'
	list domains 'geosite:cn'

config dns_server 'ali_dns_1'
	option alias 'ali_dns_1'
	option address '223.5.5.5'
	list domains 'geosite:cn'

config routing 'main_routing'
	option enabled '1'
	option domain_strategy 'IPOnDemand'
	option rules 'direct_cn_ip direct_cn_domain direct_bt route_dns direct_dns proxy_dns direct_ntp'

config routing_rule 'direct_cn_ip'
	option alias 'direct_cn_ip'
	option type 'field'
	list ip 'geoip:private'
	list ip 'geoip:cn'
	option outbound_tag 'direct'

config routing_rule 'direct_cn_domain'
	option alias 'direct_cn_domain'
	option type 'field'
	list domain 'geosite:cn'
	option outbound_tag 'direct'

config routing_rule 'direct_speedtest'
	option alias 'direct_speedtest'
	option type 'field'
	list domain 'geosite:speedtest'
	option outbound_tag 'direct'

config routing_rule 'direct_bt'
	option alias 'direct_bt'
	option type 'field'
	option protocol 'bittorrent'
	option outbound_tag 'direct'

config routing_rule 'block_ad'
	option alias 'block_ad'
	option type 'field'
	list domain 'geosite:category-ads-all'
	option outbound_tag 'block'

config routing_rule 'route_dns'
	option alias 'route_dns'
	option type 'field'
	list network 'udp'
	list port '53'
	list inbound_tag 'transparent'
	option outbound_tag 'dns_out'

config routing_rule 'direct_dns'
	option alias 'direct_dns'
	option type 'field'
	list ip '114.114.114.114'
	list ip '223.5.5.5'
	option outbound_tag 'direct'

config routing_rule 'proxy_dns'
	option alias 'proxy_dns'
	option type 'field'
	list ip '1.1.1.1'
	list ip '8.8.8.8'
	list ip '208.67.222.222'
	option outbound_tag 'proxy'

config routing_rule 'direct_ntp'
	option alias 'direct_ntp'
	option type 'field'
	list network 'udp'
	list port '123'
	option outbound_tag 'direct'

config routing_balancer 'routing_balancer_1'
	option tag 'balancer'
	list selector 'a'
	list selector 'ab'

config policy 'main_policy'
	option enabled '0'

config policy_level 'policy_level_0'
	option level '0'
	option handshake '4'
	option conn_idle '300'
	option uplink_only '2'
	option downlink_only '5'
	option buffer_size '0'

config reverse 'main_reverse'
	option enabled '0'
	list bridges 'bridge|test.v2ray.com'
	list portals 'portal|test.v2ray.com'

config inbound 'socks_proxy'
	option alias 'socks_proxy'
	option listen '0.0.0.0'
	option port '1080'
	option protocol 'socks'
	option s_socks_auth 'noauth'
	option s_socks_udp '1'
	option s_socks_ip '127.0.0.1'
	option sniffing_enabled '1'
	option sniffing_dest_override 'http tls'

config inbound 'dokodemo_door'
	option alias 'dokodemo_door'
	option port '1081'
	option protocol 'dokodemo-door'
	option tag 'transparent'
	option sniffing_enabled '1'
	option sniffing_dest_override 'http tls'

config outbound 'vmess'
	option alias 'vmess'
	option protocol 'vmess'
	option tag 'proxy'
	option s_vmess_user_security 'auto'
	option ss_network 'ws'
	option ss_security 'tls'
	option ss_websocket_path '/ray'
	option s_vmess_user_alter_id '0'
	option s_vmess_port '443'
	option s_vmess_user_id 'your-domain-uuid'
	option s_vmess_address 'your.domain.com'

config outbound 'direct'
	option alias 'direct'
	option protocol 'freedom'
	option tag 'direct'

config outbound 'block'
	option alias 'block'
	option protocol 'blackhole'
	option tag 'block'

config outbound 'dns_out'
	option alias 'dns_out'
	option protocol 'dns'
	option tag 'dns_out'

config transparent_proxy 'main_transparent_proxy'
	option apnic_delegated_mirror 'apnic'
	option gfwlist_mirror 'github'
	option proxy_list_dns '8.8.8.8'
	list lan_ifaces 'lan'
	option direct_list_dns '223.5.5.5'
	option redirect_port '1081'
	option proxy_mode 'cn_direct'
	option redirect_udp '1'


```

**Comment by shuo4sell** [comment]
> 1. 关闭 v2ray
> 2. 把 `/etc/config/v2ray` 文件里的内容换成下面那个, 刷新页面看到新的配置
> 3. 修改 outbound 的 proxy 为有效的配置
> 4. 启动 v2ray
>    这样操作下来应该就没问题了
> 
> ```
> 
> config v2ray 'main'
> 	option v2ray_file '/usr/bin/v2ray'
> 	option access_log '/dev/null'
> 	option error_log '/var/log/v2ray-error.log'
> 	option loglevel 'error'
> 	list outbounds 'vmess'
> 	list outbounds 'direct'
> 	list outbounds 'block'
> 	list outbounds 'dns_out'
> 	list inbounds 'socks_proxy'
> 	list inbounds 'dokodemo_door'
> 	option mem_percentage '80'
> 	option enabled '0'
> 
> config dns 'main_dns'
> 	option enabled '1'
> 	list hosts 'example.com|127.0.0.1'
> 	option servers 'cloudflare_dns_1 google_dns_1 114_dns_1 ali_dns_1'
> 
> config dns_server 'cloudflare_dns_1'
> 	option alias 'cloudflare_dns_1'
> 	option address '1.1.1.1'
> 
> config dns_server 'google_dns_1'
> 	option alias 'google_dns_1'
> 	option address '8.8.8.8'
> 
> config dns_server 'op_dns_1'
> 	option alias 'op_dns_1'
> 	option address '208.67.222.222'
> 	option port '5353'
> 
> config dns_server '114_dns_1'
> 	option alias '114_dns_1'
> 	option address '114.114.114.114'
> 	option port '53'
> 	list domains 'geosite:cn'
> 
> config dns_server 'ali_dns_1'
> 	option alias 'ali_dns_1'
> 	option address '223.5.5.5'
> 	list domains 'geosite:cn'
> 
> config routing 'main_routing'
> 	option enabled '1'
> 	option domain_strategy 'IPOnDemand'
> 	option rules 'direct_cn_ip direct_cn_domain direct_bt route_dns direct_dns proxy_dns direct_ntp'
> 
> config routing_rule 'direct_cn_ip'
> 	option alias 'direct_cn_ip'
> 	option type 'field'
> 	list ip 'geoip:private'
> 	list ip 'geoip:cn'
> 	option outbound_tag 'direct'
> 
> config routing_rule 'direct_cn_domain'
> 	option alias 'direct_cn_domain'
> 	option type 'field'
> 	list domain 'geosite:cn'
> 	option outbound_tag 'direct'
> 
> config routing_rule 'direct_speedtest'
> 	option alias 'direct_speedtest'
> 	option type 'field'
> 	list domain 'geosite:speedtest'
> 	option outbound_tag 'direct'
> 
> config routing_rule 'direct_bt'
> 	option alias 'direct_bt'
> 	option type 'field'
> 	option protocol 'bittorrent'
> 	option outbound_tag 'direct'
> 
> config routing_rule 'block_ad'
> 	option alias 'block_ad'
> 	option type 'field'
> 	list domain 'geosite:category-ads-all'
> 	option outbound_tag 'block'
> 
> config routing_rule 'route_dns'
> 	option alias 'route_dns'
> 	option type 'field'
> 	list network 'udp'
> 	list port '53'
> 	list inbound_tag 'transparent'
> 	option outbound_tag 'dns_out'
> 
> config routing_rule 'direct_dns'
> 	option alias 'direct_dns'
> 	option type 'field'
> 	list ip '114.114.114.114'
> 	list ip '223.5.5.5'
> 	option outbound_tag 'direct'
> 
> config routing_rule 'proxy_dns'
> 	option alias 'proxy_dns'
> 	option type 'field'
> 	list ip '1.1.1.1'
> 	list ip '8.8.8.8'
> 	list ip '208.67.222.222'
> 	option outbound_tag 'proxy'
> 
> config routing_rule 'direct_ntp'
> 	option alias 'direct_ntp'
> 	option type 'field'
> 	list network 'udp'
> 	list port '123'
> 	option outbound_tag 'direct'
> 
> config routing_balancer 'routing_balancer_1'
> 	option tag 'balancer'
> 	list selector 'a'
> 	list selector 'ab'
> 
> config policy 'main_policy'
> 	option enabled '0'
> 
> config policy_level 'policy_level_0'
> 	option level '0'
> 	option handshake '4'
> 	option conn_idle '300'
> 	option uplink_only '2'
> 	option downlink_only '5'
> 	option buffer_size '0'
> 
> config reverse 'main_reverse'
> 	option enabled '0'
> 	list bridges 'bridge|test.v2ray.com'
> 	list portals 'portal|test.v2ray.com'
> 
> config inbound 'socks_proxy'
> 	option alias 'socks_proxy'
> 	option listen '0.0.0.0'
> 	option port '1080'
> 	option protocol 'socks'
> 	option s_socks_auth 'noauth'
> 	option s_socks_udp '1'
> 	option s_socks_ip '127.0.0.1'
> 	option sniffing_enabled '1'
> 	option sniffing_dest_override 'http tls'
> 
> config inbound 'dokodemo_door'
> 	option alias 'dokodemo_door'
> 	option port '1081'
> 	option protocol 'dokodemo-door'
> 	option tag 'transparent'
> 	option sniffing_enabled '1'
> 	option sniffing_dest_override 'http tls'
> 
> config outbound 'vmess'
> 	option alias 'vmess'
> 	option protocol 'vmess'
> 	option tag 'proxy'
> 	option s_vmess_user_security 'auto'
> 	option ss_network 'ws'
> 	option ss_security 'tls'
> 	option ss_websocket_path '/ray'
> 	option s_vmess_user_alter_id '0'
> 	option s_vmess_port '443'
> 	option s_vmess_user_id 'your-domain-uuid'
> 	option s_vmess_address 'your.domain.com'
> 
> config outbound 'direct'
> 	option alias 'direct'
> 	option protocol 'freedom'
> 	option tag 'direct'
> 
> config outbound 'block'
> 	option alias 'block'
> 	option protocol 'blackhole'
> 	option tag 'block'
> 
> config outbound 'dns_out'
> 	option alias 'dns_out'
> 	option protocol 'dns'
> 	option tag 'dns_out'
> 
> config transparent_proxy 'main_transparent_proxy'
> 	option apnic_delegated_mirror 'apnic'
> 	option gfwlist_mirror 'github'
> 	option proxy_list_dns '8.8.8.8'
> 	list lan_ifaces 'lan'
> 	option direct_list_dns '223.5.5.5'
> 	option redirect_port '1081'
> 	option proxy_mode 'cn_direct'
> 	option redirect_udp '1'
> ```

感谢老哥贴上的详细配置，光是把这份配置修改上去我又学习了好久hhh，收获颇丰。
可惜依然不行。看了一下有几处是不是要改一下，全局勾选是socks_proxy，透明代理是直连CN，虽然无论改不改目前都不行。
刚才一直在摸索OpenClash，已经成功了，不过用的是订阅链接，但同样的节点在那是能用的。
v2ray的功能应该是正常的。
启动以后报错倒是不报了，很神奇，而且能上强内的网站。
另外我出站是auto加密，tcp协议，无伪装，端口号也和你不一样，不知道这些会不会影响其他设置。
出站信息是完全照着v2rayN上的信息粘贴的。
确认一下，你这份配置是现在能用的配置吗？有空的话帮我看看还有什么可能性，感谢~

**Comment by shuo4sell** [comment]
更正一下，报错还是会报的，日志等级调到警告就有了。不过跟之前不太一样，现在不报那个non existing tag了，只报前面的v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by shynome** [comment]
按 v2rayN 的配置来就行, 不行的话我也帮不上忙
<del>除非你把 v2ray 的连接信息给我, 我配好把配置给回你</del>

**Comment by shuo4sell** [comment]
> 按 v2rayN 的配置来就行, 不行的话我也帮不上忙
> ~除非你把 v2ray 的连接信息给我, 我配好把配置给回你~

好的老哥，不过暂时准备先放一放这个插件，观察一下路由器本身和其他插件的稳定性（刚买路由器三天，目前遇到一个隔几分钟就断流十来秒的情况），顺便等等看有没有其他朋友的解决方案或者在其他issue下。

**Comment by youland** [comment]
1，V2ray - 全局设置-启用的入站连接，这里不要选socks_proxy，只在dokodemo_door前面打勾即可
2，V2Ray - 入站连接-dokodemo_door的监听地址写0.0.0.0，不要写192.168.1.1
3，V2Ray - 出站连接，数据流网络选tcp，发送IP地址可写192.168.1.1的路由器ip
4，V2Ray - 透明代理，使用 TProxy/转发 UDP这两个先不要打勾，等调试通了再勾。
5，这个图片里的两条规则删掉：https://user-images.githubusercontent.com/38107095/96872832-b5134e00-14a6-11eb-872b-c63e5cb2f0d4.png

重新设置后，重启一下路由器，再试一下。

**Comment by shuo4sell** [comment]
> 1，V2ray - 全局设置-启用的入站连接，这里不要选socks_proxy，只在dokodemo_door前面打勾即可
> 2，V2Ray - 入站连接-dokodemo_door的监听地址写0.0.0.0，不要写192.168.1.1
> 3，V2Ray - 出站连接，数据流网络选tcp，发送IP地址可写192.168.1.1的路由器ip
> 4，V2Ray - 透明代理，使用 TProxy/转发 UDP这两个先不要打勾，等调试通了再勾。
> 5，这个图片里的两条规则删掉：https://user-images.githubusercontent.com/38107095/96872832-b5134e00-14a6-11eb-872b-c63e5cb2f0d4.png
> 
> 重新设置后，重启一下路由器，再试一下。

谢谢老哥指点，尝试了几小时还是无果，先放弃了（目测主要问题就是入站出站ip，因为我是二级路由，可能和大家不一样，还有non existing tag的问题，就是 https://user-images.githubusercontent.com/38107095/96873653-d163ba80-14a7-11eb-8214-5046ad7cd1a7.png 这两个错误），转用其他插件，就先关闭本票以免打扰各位了。
