### ISSUE TITLE
请问如何配置绕过ipv6？

### ISSUE THREAD

**Issue by zhihuiyuze** [kuoruan/luci-app-v2ray#303]
您好，我在透明代理里的direct list写::/0发现无效。
我尝试在routing里写一个绕过::/0的规则但是好像会导致DNS无法正常解析。
![IMG_20201103_224456](https://user-images.githubusercontent.com/38281461/97999413-3b744c00-1e26-11eb-8b21-d3a8e95ac311.jpg)
我应该如何正确添加？因为服务端不支持IPv6但是本地的ipv6的TCP UDP流量都被v2Ray转发了

**Comment by youland** [comment]
我把电信的ipv6给禁用了，不过我有公网ipv4

**Comment by S0MEW0LF** [comment]
在/etc/sysctl.conf里面添加两行：
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
SSH执行 sysctl -p  生效
