### ISSUE TITLE
请问怎么配置才能支持CDN

### ISSUE THREAD

**Issue by PicaroonX** [kuoruan/luci-app-v2ray#31]
已经配置好了v2ray+ws+cdn，地址为wss://aaa.sample.com/ray。luci-app-v2ray中的socks_proxy已经可以正常使用，但是透明代理transparent_proxy会报错：
2019/10/26 01:03:48 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://aaa.sample.com/ray):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

因为socks_proxy可以正常使用，所以upstream_vmess应该是正确的。具体配置如果有需要再贴上来。
补充，如果不用ws+cdn是可以正常使用透明代理的。

怀疑是iptables的问题，之前是用的IP地址。现在加CDN必须使用域名，然后ping aaa.sample.com把得到的IP地址手动添加到V2RAY的NAT中。命令如下
iptables -t nat -A V2RAY -p tcp -d 104.27.130.111 -j RETURN
这个已经添加成功，**但透明代理还是无法使用**，不能访问pornhub^^

**Comment by PicaroonX** [comment]
先把完整配置补充上来：
{
	"log": {
		"loglevel": "warning",
		"access": "\/var\/log\/v2ray-access.log",
		"error": "\/var\/log\/v2ray-error.log"
	},
	"dns": {
		"hosts": {
			"example.com": "127.0.0.1"
		},
		"servers": [
			{
				"address": "208.67.222.222",
				"port": 5353
			},
			{
				"address": "114.114.114.114",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			}
		]
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"tag": "transparent_proxy",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"settings": {
				"network": "tcp,udp",
				"timeout": 300,
				"followRedirect": true
			}
		}
	],
	"outbounds": [
		{
			"sendThrough": "0.0.0.0",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "aaa.sample.com",
						"port": 443,
						"users": [
							{
								"id": "x-x-x-x-x"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"wsSettings": {
					"path": "\/ray",
					"headers": {
						
					}
				},
				"tlsSettings": {
					"allowInsecure": false,
					"alpn": [
						"http\/1.1"
					],
					"serverName": "aaa.sample.com",
					"allowInsecureCiphers": false
				},
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "freedom",
			"tag": "direct",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "blackhole",
			"tag": "block",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		}
	]
}

**Comment by kuoruan** [comment]
按这条 commit 修改一下
kuoruan/luci-app-v2ray@02a7559dce7afe5e3091bdf74f82d61e48183720

**Comment by PicaroonX** [comment]
好了，感谢大佬！！！
