### ISSUE TITLE
更新GFWList 镜像失败

### ISSUE THREAD

**Issue by gongyho** [kuoruan/luci-app-v2ray#310]
luci-app-v2ray:2.0.0-1
请求失败。 at eval (http://openwrt/luci-static/resources/view/v2ray/transparent-proxy.js?v=git-20.247.75781-0d0ab01:1:1662)
![image](https://user-images.githubusercontent.com/39721677/99902448-dd39db00-2cf8-11eb-9f8c-fbef3f86deb4.png)

**Comment by youland** [comment]
以root用户用ssh登录到openwrt，在/etc/dnsmasq.conf最后面加入以下4行，保存，重启一下。
no-resolv
cache-size=5000
server=127.0.0.1
server=114.114.114.114
然后再来更新gfwlist列表就ok了

这上面的4行可以解决很多问题，总的来说，就是解决了v2ray的dns不足。

**Comment by gongyho** [comment]
完美解决 感谢

**Comment by askiter** [comment]
luci-app-v2ray:2.0.0-1
上述修改dnsmasq.conf的方法无效

**Comment by youland** [comment]
> luci-app-v2ray:2.0.0-1 上述修改dnsmasq.conf的方法无效

github.com
216.58.200.46
raw.githubusercontent.com
把上面三个加入额外代理列表试一下。
