### ISSUE TITLE
折腾了三天，服务不运行，log中Reading config: stdin: (没有geoip.dat？)

### ISSUE THREAD

**Issue by zaaron345** [kuoruan/luci-app-v2ray#329]
新人一知半解的再折腾，之前重新安装系统软件重启都试过了，都是一样的问题。

luci中开启v2ray后，一直显示未运行（有时候会变一下运行，然后变回未运行）

log中：
```
root@OpenWrt:~# v2ray log 
V2Ray 4.33.0 (OpenWrt) R1 (go1.15.5 linux/mips)
A unified platform for anti-censorship.
2020/12/20 10:18:14 Using config from STDIN
2020/12/20 10:18:14 [Info] v2ray.com/core/main/jsonem: Reading config: stdin:
```
然后就一直没有了

这是我的配置
![Screenshot_2020-12-20 OpenWrt - Global Settings - LuCI](https://user-images.githubusercontent.com/64295005/102710897-af908380-42f0-11eb-8c6e-82551c6dde23.png)
![Screenshot_2020-12-20 OpenWrt - Inbound - LuCI](https://user-images.githubusercontent.com/64295005/102710896-aef7ed00-42f0-11eb-8e7d-1ae37f0a2b1e.png)
![Screenshot_2020-12-20 OpenWrt - Outbound - LuCI](https://user-images.githubusercontent.com/64295005/102710895-ae5f5680-42f0-11eb-9b97-515d633c423c.png)
![Screenshot_2020-12-20 OpenWrt - Routing - LuCI](https://user-images.githubusercontent.com/64295005/102710894-adc6c000-42f0-11eb-976e-13565184efef.png)
![Screenshot_2020-12-20 OpenWrt - Transparent Proxy - LuCI](https://user-images.githubusercontent.com/64295005/102710893-abfcfc80-42f0-11eb-8771-b236f823a5bf.png)

谢谢！

**Comment by zaaron345** [comment]
试了试命令行中规定config为/var/etc/v2ray/v2ray.main.json，提示没有geoip.dat
```
v2ray -c /var/etc/v2ray/v2ray.main.json
V2Ray 4.33.0 (OpenWrt) R1 (go1.15.5 linux/mips)
A unified platform for anti-censorship.
2020/12/20 10:47:55 [Info] v2ray.com/core/main/jsonem: Reading config: /var/etc/v2ray/v2ray.main.json
main: failed to read config files: [/var/etc/v2ray/v2ray.main.json] > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/bin/geoip.dat: no such file or directory
```
`open /usr/bin/geosite.dat: no such file or directory`

找到这篇issue：https://github.com/v2ray/v2ray-core/issues/1450，有人让把/etc/v2ray/的geosite.dat复制到/usr/bin/，但是/etc/v2ray/和/usr/bin/v2ray都没有geosite.dat。

另外一个issue：https://github.com/v2ray/v2ray-core/issues/1690，下载了这里面分享的geosite.dat文件放进去，结果runtime.stake没有内存。
```
root@OpenWrt:~# v2ray -c /var/etc/v2ray/v2ray.main.json
V2Ray 4.33.0 (OpenWrt) R1 (go1.15.5 linux/mips)
A unified platform for anti-censorship.
2020/12/20 10:46:27 [Info] v2ray.com/core/main/jsonem: Reading config: /var/etc/v2ray/v2ray.main.json
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe3dea4, 0x16)
	runtime/panic.go:1116 +0x60
```
现在就又卡住了

**Comment by predators46** [comment]
v2ray-core install

**Comment by zaaron345** [comment]
> v2ray-core install

是什么意思？
```
root@OpenWrt:~# v2ray-core install
-ash: v2ray-core: not found
root@OpenWrt:~# v2ray-core-mini install
-ash: v2ray-core-mini: not found
```

重新安装v2ray-core/v2ray-core-mini的话我已经安装了好几次了，没用。。。

**Comment by predators46** [comment]
> > v2ray-core install
> 
> 是什么意思？
> 
> ```
> root@OpenWrt:~# v2ray-core install
> -ash: v2ray-core: not found
> root@OpenWrt:~# v2ray-core-mini install
> -ash: v2ray-core-mini: not found
> ```
> 
> 重新安装v2ray-core/v2ray-core-mini的话我已经安装了好几次了，没用。。。

opkg install v2ray-core必须从头开始安装。我试图不发现这样的失败

**Comment by zaaron345** [comment]
> > > v2ray-core install
> > 
> > 
> > 是什么意思？
> > ```
> > root@OpenWrt:~# v2ray-core install
> > -ash: v2ray-core: not found
> > root@OpenWrt:~# v2ray-core-mini install
> > -ash: v2ray-core-mini: not found
> > ```
> > 
> > 
> > 重新安装v2ray-core/v2ray-core-mini的话我已经安装了好几次了，没用。。。
> 
> opkg install v2ray-core必须从头开始安装。我试图不发现这样的失败

我又恢复出厂设置 完全重新安装了一次（这应该是第三四次了） 安装没有报错 同样的错误。。。

**Comment by predators46** [comment]
> > > > v2ray-core install
> > > 
> > > 
> > > 是什么意思？
> > > ```
> > > root@OpenWrt:~# v2ray-core install
> > > -ash: v2ray-core: not found
> > > root@OpenWrt:~# v2ray-core-mini install
> > > -ash: v2ray-core-mini: not found
> > > ```
> > > 
> > > 
> > > 重新安装v2ray-core/v2ray-core-mini的话我已经安装了好几次了，没用。。。
> > 
> > 
> > opkg install v2ray-core必须从头开始安装。我试图不发现这样的失败
> 
> 我又恢复出厂设置 完全重新安装了一次（这应该是第三四次了） 安装没有报错 同样的错误。。。
> 难道是因为v2ray-core-mini的关系？（不过之前加U盘安装过v2ray-core也是一样的错误）

我在创建v2ray时仅看到v2ray-core具有geosite.dat

**Comment by zaaron345** [comment]
> > > > > v2ray-core install
> > > > 
> > > > 
> > > > 是什么意思？
> > > > ```
> > > > root@OpenWrt:~# v2ray-core install
> > > > -ash: v2ray-core: not found
> > > > root@OpenWrt:~# v2ray-core-mini install
> > > > -ash: v2ray-core-mini: not found
> > > > ```
> > > > 
> > > > 
> > > > 重新安装v2ray-core/v2ray-core-mini的话我已经安装了好几次了，没用。。。
> > > 
> > > 
> > > opkg install v2ray-core必须从头开始安装。我试图不发现这样的失败
> > 
> > 
> > 我又恢复出厂设置 完全重新安装了一次（这应该是第三四次了） 安装没有报错 同样的错误。。。
> > 难道是因为v2ray-core-mini的关系？（不过之前加U盘安装过v2ray-core也是一样的错误）
> 
> 我在创建v2ray时仅看到v2ray-core具有geosite.dat

就是这个问题！谢谢！

我安装了v2ray-core就好了！希望作者在readme里面写一下v2ray-core和mini之间的区别以防像我一样的新人搞这么半天搞不懂 👍
