### ISSUE TITLE
请大家帮一下忙，发一个可以用的v2ray路由配置

### ISSUE THREAD

**Issue by iyzh635428** [kuoruan/luci-app-v2ray#33]
我的服务器是用websocket+tls组建的v2ray，在padavan路由上能用的v2ray配置，ip做了相应的更改，在luci上，无论如何就是无法使用。实在没办法了，求助好心大神！

**Comment by kuoruan** [comment]
地址是填的域名吗？域名的支持刚加上，还没发布出去，准备明天再改改，添加 ipset 支持

**Comment by iyzh** [comment]
> 地址是填的域名吗？域名的支持刚加上，还没发布出去，准备明天再改改，添加 ipset 支持

大神，你害得我好苦呀，这么不完善的v2ray发布出来干啥？

**Comment by kuoruan** [comment]
总有一个迭代的过程，你说是吧？

**Comment by kuoruan** [comment]
按 #31 的修改，手动加上吧

**Comment by iyzh** [comment]
> 总有一个迭代的过程，你说是吧？

完全理解。我也是没办法，padavan系统的v2ray问题也不少，很容易用，结果发现100M的网络，变成不超过30M。改成v2ray配合transock代理，网速没问题了，有些网站却打不开，实在受不了，刷了个x-wrt系统，再装了你的v2ray，才发现，问题更多，最大的问题就是，太难用了。自定义配置，好歹告诉一下大家，要输入路径，按一下enter键才能录入。vmess里的setting，要点击“重载服务”，才能保存到v2ray.main.json。哇！太痛苦了。不过我还是很敬佩你，你比我高级多了。

**Comment by iyzh** [comment]
> 按 #31 的修改，手动加上吧

我说简单点，我只会安装，用现成的，至于commit，我猜你是要我自行编译，我只能说，我暂时不会，也不懂。

**Comment by kuoruan** [comment]
我这个 LuCI 是给 OpenWrt 写的，默认情况下点击 “保存并应用” 就可以提交修改。
至于其他的二次开发系统，并没有考虑兼容。
另外就是，我写的 LuCI 从来都不是考虑易用性，我觉得应该把更多的配置开放给用户，供自定义，而不是在 LuCI 里边把大部分东西自动配置好，造成了使用门槛大幅度升高。
所以就出现了不适合小白用户使用这个问题，毕竟开发的初衷是为了技术交流。

**Comment by MassSmith** [comment]
我也用websocket+tls，出现了证书验证错误，我是在树莓派中安装openwrt，v2ray程序直接使用官网的arm64版本，后来在配置中加一个配置就好了。
"tlsSettings": {
"allowInsecure": true
}
加在tls设置下。如果不加，使用中会出现x509错误。

**Comment by kuoruan** [comment]
@MassSmith 没装证书吗？ca-bundle

**Comment by MassSmith** [comment]
是的，后来发现，是没有安装这个包：ca-certificates
opkg update
opkg install ca-certificates
去掉
"tlsSettings": {
"allowInsecure": true
}
也可以正常使用了。

**Comment by nickleefly** [comment]
确认你的outbounds配置和服务端一致就可以了，比如我的websocket tls配置类似如下
具体可参考 #21
```
"outbounds": [
		{
			"sendThrough": "0.0.0.0",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"port": 443,
						"users": [
							{
								"id": "your-id-here",
								"alterId": 233,
								"security": "auto",
								"level": 0
							}
						],
						"address": "v2ray.yourdomain.com"
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"tlssettings": {
					"allowInsecure": true,
					"serverName": "v2ray.yourdomain.com"
				},
				"wssettings": {
					"connectionReuse": true,
					"headers": {
						"Host": "v2ray.yourdomain.com"
					},
					"path": "\/"
				},
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "dns",
			"tag": "dns_out",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		}
	]
```
