### ISSUE TITLE
插件自带的v2ray更新的时候没有更新 域名文件。

### ISSUE THREAD

**Issue by loftgame** [kuoruan/luci-app-v2ray#34]
geoip.dat 和 geosite.dat没有更新。。

导致如果配置文件里面有用新的域名key .会报错不能启动~

**Comment by kuoruan** [comment]
- LuCI 不自带 v2ray
- 如需要最新的 assets 文件，可以下载我的编译 https://github.com/kuoruan/openwrt-v2ray/releases
