### ISSUE TITLE
大大，这个支持tproxy吗？

### ISSUE THREAD

**Issue by dotjh** [kuoruan/luci-app-v2ray#36]

**Comment by dotjh** [comment]
"sockopt": {
          "tproxy": "tproxy" // 透明代理使用 TPROXY 方式
        }
在入口的底层协议中加入这个TPROXY，好像没用

**Comment by kuoruan** [comment]
我也不确定，暂时没用过这个功能

**Comment by kuoruan** [comment]
后期会加上 tproxy 透明代理支持

**Comment by maddie** [comment]
Looking forward to TPROXY support too.

Reference: https://guide.v2fly.org/app/tproxy.html
