### ISSUE TITLE
安装出错了，帮忙看下是什么原因

### ISSUE THREAD

**Issue by glenlau228** [kuoruan/luci-app-v2ray#367]
root@R6100:/tmp# opkg install luci-app-v2ray_1.5.6_all.ipk
Installing luci-app-v2ray (1.5.6) to root...
Installing dnsmasq-full (2.80-16.3) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/packages/mips_24kc/base/dnsmasq-full_2.80-16.3_mips_24kc.ipk
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-v2ray.

**Comment by sealpp** [comment]
老哥解决了吗
