### ISSUE TITLE
请教下透明代理的问题

### ISSUE THREAD

**Issue by csquya** [kuoruan/luci-app-v2ray#38]
我在恩山论坛发现你（估计是）发的贴子如下：

> 支持透明代理，但不支持透明代理路由器自身的网络，原因是如果开启路由器自身网络透明代理，再开启国内网址直连的话，会形成回环。如果有朋友有能力解决的话，可以提交 PR

能否解释下“不支持透明代理路由器自身的网络”到底是啥意思， 有什么影响。 谢谢。

**Comment by kuoruan** [comment]
已处理，现在应该是可以了
