### ISSUE TITLE
无法正确添加路由规则

### ISSUE THREAD

**Issue by starP-W** [kuoruan/luci-app-v2ray#4]
尝试将v2ray白话文教程中提供的[gfw域名文件](https://toutyrater.github.io/routing/sitedata.html)添加进v2ray-core的ipk中，并在luci路由页面下新建规则，规则创建完毕后无法正常向域名一栏中写入`ext:h2y.dat:gfw`，具体表现为点击保存时该栏会被直接清空并顺利保存，且预设规则中点击+号也无法新增文本框以填写规则。
使用的SDK：openwrt-sdk-x86-generic_gcc-7.4.0_musl.Linux-x86_64.tar.xz 发布于 Fri Jul 5 23:29:55 2019

**Comment by kuoruan** [comment]
无法复现

**Comment by starP-W** [comment]
用6号发布的SDK又能用了，玄学解决
