### ISSUE TITLE
安装完成后无法打开v2服务页面

### ISSUE THREAD

**Issue by Bearlele** [kuoruan/luci-app-v2ray#427]
/usr/lib/lua/luci/dispatcher.lua:1334: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1334: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1023: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:984: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

**Comment by xbwpc** [comment]
缺了luci-compat吧

**Comment by Bearlele** [comment]
> 缺了luci-compat吧

请问该怎么解决

**Comment by xbwpc** [comment]
> > 缺了luci-compat吧
> 
> 请问该怎么解决

连ssh
opkg update
opkg install luci-compat
或者你直接在luci的software页面里update/搜索/安装
另外要提醒你，在新版openwrt上这个luci-app还是有点bug的，比如在登陆页面就会出现这个插件
