### ISSUE TITLE
what is proper procedure/ in-negligible steps to update luci-app-v2ray to new version

### ISSUE THREAD

**Issue by RoninYuan-WY** [kuoruan/luci-app-v2ray#43]
what is proper procedure or in-negligible step to update luci-app-v2ray from a running old version seamlessly to new version？Because I met some update issues during direct update, it seems I need remove old version first and manually clean some dependencies and files, am I right?

**Comment by kuoruan** [comment]
dnsmasq-full is conflict with dnsmasq. you need to uninstall dnsmasq before installing dnsmasq-full
