### ISSUE TITLE
列表更新失败

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/luci-app-v2ray#44]
谢谢作者。刚用上，很好用。
两个小问题。
1，在透明代理配置页面上，试图更新gfwlist和chnroute，总是显示“列表更新失败”。
2，现在更新只能靠重新安装ipk吧？
有没有考虑建一个openwrt的软件源(feed)？当然，那有点麻烦。

**Comment by kuoruan** [comment]
看看系统日志里边是否有报错

**Comment by dalton-chiou** [comment]
> 看看系统日志里边是否有报错

是wget的问题。安装openssl库后解决。谢谢。
