### ISSUE TITLE
GFWList Proxy doesn't work in Transparent Proxy tab

### ISSUE THREAD

**Issue by RoninYuan-WY** [kuoruan/luci-app-v2ray#45]
Switching proxy mode to GFWList Proxy in transparent proxy doesn't work. meanwhile, updating CHRRoute and GFWList always failed.

**Comment by RoninYuan-WY** [comment]
first and second are positive, but can't see any log in v2ray-error.log, I don't know whether I choose right log level or other setting, even I switched different level of logs

**Comment by kuoruan** [comment]
Check your system log not your v2ray log

**Comment by RoninYuan-WY** [comment]
Thanks, I found the issue is related ssl/tls package, I installed wrong version, need libustream-.*[ssl|tls] packages. Thanks again and this issue should be closed.
