### ISSUE TITLE
请求为 22.03 之后版本添加 nft 支持（已有开发者添加了 kmod-nft-tproxy 包）

### ISSUE THREAD

**Issue by jerry-ch-issue** [kuoruan/luci-app-v2ray#451]
![Screenshot_20220502-204243](https://user-images.githubusercontent.com/65878337/166236737-f42c4a04-340e-4c12-aa8c-efe44882ce5a.png)
貌似不需要类似 iptables-mod-tproxy， 至少我试了，可以添加rule。
外行小白，自己试着修改init.d/v2ray，啃了半天没啃动。

**Comment by ttimasdf** [comment]
[\[OpenWrt Wiki\] nftables](https://openwrt.org/docs/guide-user/firewall/misc/nftables)

> OpenWrt currently uses fw3 to set the firewall, and that is not compatible with nftables; hence in OpenWrt it is not currently possible to use nftables from the web interface. However if users are comfortable using the command line interface, nftables are supported by OpenWrt. The rest of this article describes how to use them, users should do this with care, and read the general documentation for nftables.
> 
> Firstly nftables kernel modules, are in part not compatible with iptables, in particular the kernel module iptable_nat the nftables equivalents nf_nat* and nf_masq; so before using nftables you have to switch off the loading of iptable NAT.

劝退。跟现有的工具链完全不兼容。

**Comment by WordsWorthLess** [comment]
> ![Screenshot_20220502-204243](https://user-images.githubusercontent.com/65878337/166236737-f42c4a04-340e-4c12-aa8c-efe44882ce5a.png) 貌似不需要类似 iptables-mod-tproxy， 至少我试了，可以添加rule。 外行小白，自己试着修改init.d/v2ray，啃了半天没啃动。

试着改了一下/etc/init.d/v2ray, 可以通过nftables处理防火墙，不过openwrt上的dnsmasq最高为2.86版，无法往nftables 的set里面添加element, 也就是说，gfwlist模式无法使用，其余功能没问题. 不过始终搞不定ipv6的透明代理，有人可以指导一下吗

**Comment by jerry-ch-issue** [comment]
> > ![Screenshot_20220502-204243](https://user-images.githubusercontent.com/65878337/166236737-f42c4a04-340e-4c12-aa8c-efe44882ce5a.png) 貌似不需要类似 iptables-mod-tproxy， 至少我试了，可以添加rule。 外行小白，自己试着修改init.d/v2ray，啃了半天没啃动。
> 
> 试着改了一下/etc/init.d/v2ray, 可以通过nftables处理防火墙，不过openwrt上的dnsmasq最高为2.86版，无法往nftables 的set里面添加element, 也就是说，gfwlist模式无法使用，其余功能没问题. 不过始终搞不定ipv6的透明代理，有人可以指导一下吗

看了一下，2.87现在才进入测试版，那估计得23.××以后才能升级了

**Comment by ttimasdf** [comment]
gfwlist模式我个人认为完全没必要，增加了实现的复杂度，要说有啥优点就只剩一丁丁丁丁点性能优势——访问国外未墙网站的流量不需要经过xray。

莫不如直接把所有流量导入xray/v2ray，让v2ray根据路由策略自行分流，如果用支持XTLS的内核的话，在路由器上转发性能也有保证，我个人netgear某型号的路由器，过墙速度跑满千兆完全没问题

v2ray 可用的 gfwlist： https://github.com/Loyalsoldier/v2ray-rules-dat
使用方法：
1. 把这个geosite.dat丢给 v2ray，
2. 搞个 ipset 里装上 chnlist，
3. 剩下的流量全塞给 v2ray，路由规则写 `geosite:gfw`

就完事了。

不纠结 gfwlist 的话，就没有必要纠结 dnsmasq 的版本问题了。那东西再怎么魔改怎么升级，也不适合承载那么复杂的功能。

**Comment by jerry-ch-issue** [comment]
是这么个道理，但是我的场景是有限制的，，，首先我不想无谓增实体，所以排除了软路由，然后我想原生自带 硬 NAT ，所以可选的只有
MT7621架构，而这个架构，基本最大只有16M内存可选。装不了完整的 v2ray 或者 xray，所以只能选 upx
压缩过的版本，这个版本不带地址库，刚好符合我那捉襟见肘的内存需求。至于为什么不用白名单，还是为了减少暴露风险吧，其实专用设备还是用的白名单，不过是按需开启的。
