### ISSUE TITLE
如何让ping和ssh 直连？

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/luci-app-v2ray#460]
刚注意到，在透明代理方案为直连CN时，ping或ssh海外VPS也是走代理的。
如题，如何让这两个永远直连呢？

**Comment by WordsWorthLess** [comment]
icmp ping 還是 TCP ping？如果前者的話，是不可能的，你肯定弄錯了， V2RAY不能代理icmp協議，而且這個插件生成的iptables規則也不涉及icmp，如果后者的話，你可以添加一個路由，讓指定目標ip的指定TCP port走freedom出站

SSH的話，你可以添加一個路由規則，讓TCP port22(SSH的默認port，假如你的主機修改過默認的ssh port,則配置成對應的) 走 freedom協議出站，并且把這個路由優先級放到最高（即置頂）

**Comment by dalton-chiou** [comment]
> 谢谢回复。您说得完全对。我加了一条路由，不过又取消了，因为本来不开v2ray的路由功能，出站也只开一个vmess，为了SSH额外增加开销，觉得不值。
