### ISSUE TITLE
Cannot open file kuoruan-public.keyecho

### ISSUE THREAD

**Issue by fevid** [kuoruan/luci-app-v2ray#472]
after running `opkg update`
I get the following errors:

> Collected errors:
>  * opkg_conf_parse_file: /etc/opkg/customfeeds.conf:4: Ignoring invalid line: `Cannot open file kuoruan-public.keyecho'
>  * opkg_conf_parse_file: Duplicate src declaration (kuoruan_universal http://openwrt.kuoruan.net/packages/releases/all). Skipping.

therefore the `opkg install luci-app-v2ray`
throws the following errors:

> > Collected errors:
>  * opkg_conf_parse_file: /etc/opkg/customfeeds.conf:4: Ignoring invalid line: `Cannot open file kuoruan-public.keyecho'
>  * opkg_conf_parse_file: Duplicate src declaration (kuoruan_universal http://openwrt.kuoruan.net/packages/releases/all). Skipping.
>  * opkg_install_cmd: Cannot install package luci-app-v2ray.

my device running OpenWrt 22.03.5

**Comment by randomsymbols** [comment]
Collected errors:
 * opkg_conf_parse_file: /etc/opkg/customfeeds.conf:4: Ignoring invalid line: `src-git-full luci_app_xray https://github.com/yichya/luci-app-xray

[Powered by LuCI openwrt-24.10 branch (25.302.55195~bfcef12)](https://github.com/openwrt/luci) / RouteRich 24.10.4 r28959-29397011cc RR-3.8.2
