### ISSUE TITLE
Problem with latest luci-app-v2ray 1.4

### ISSUE THREAD

**Issue by Tualua** [kuoruan/luci-app-v2ray#48]
Hello!

I have a problem running latest luci-app-v2ray. When I configure it same way as 1.3 everything stops working. 
I have perfectly working similar router setup with latest 1.3 - no issues at all. 

I'm running Edgerouter-X. I tried 18.06.5 and now on master - same behavior. DNS not working at all.

    {
    	"log": {
    		"loglevel": "debug",
    		"access": "/var/log/v2ray-access.log",
    		"error": "/var/log/v2ray-error.log"
    	},
    	"dns": {
    		"hosts": {
    			"example.com": "127.0.0.1"
    		},
    		"servers": [
    			"8.8.8.8",
    			{
    				"address": "208.67.222.222",
    				"port": 5353
    			},
    			{
    				"address": "114.114.114.114",
    				"port": 53,
    				"domains": [
    					"geosite:cn"
    				]
    			}
    		]
    	},
    	"routing": {
    		"domainStrategy": "IPOnDemand",
    		"rules": [
    			{
    				"type": "field",
    				"ip": [
    					"geoip:private",
    					"geoip:cn"
    				],
    				"outboundTag": "direct"
    			},
    			{
    				"type": "field",
    				"domain": [
    					"geosite:cn"
    				],
    				"outboundTag": "direct"
    			}
    		]
    	},
    	"inbounds": [
    		{
    			"listen": "192.168.1.1",
    			"port": 1080,
    			"protocol": "socks",
    			"sniffing": {
    				"enabled": true,
    				"destOverride": [
    					"http",
    					"tls"
    				]
    			},
    			"settings": {
    				"udp": true,
    				"auth": "noauth",
    				"ip": "127.0.0.1"
    			}
    		},
    		{
    			"listen": "192.168.1.1",
    			"port": 1081,
    			"protocol": "dokodemo-door",
    			"tag": "dokodemo_door",
    			"sniffing": {
    				"enabled": true,
    				"destOverride": [
    					"http",
    					"tls"
    				]
    			},
    			"settings": {
    				"followRedirect": true,
    				"network": "tcp,udp"
    			}
    		}
    	],
    	"outbounds": [
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "vmess",
    			"mux": {
    				"enabled": true,
    				"concurrency": 4
    			},
    			"settings": {
    				"vnext": [
    					{
    						"address": "v2ray.hostname.tld",
    						"port": 443,
    						"users": [
    							{
    								"id": "uuid",
    								"alterId": 64,
    								"email": "t@t.tt",
    								"security": "auto"
    							}
    						]
    					}
    				],
    				"servers": null,
    				"response": null
    			},
    			"streamSettings": {
    				"network": "ws",
    				"security": "tls",
    				"tlsSettings": {
    					"allowInsecure": false,
    					"serverName": "v2ray.hostname.tld"
    				},
    				"tcpSettings": null,
    				"kcpSettings": null,
    				"wsSettings": {
    					"connectionReuse": true,
    					"path": "/ray",
    					"headers": {
    						"Host": "v2ray.hostname.tld"
    					}
    				},
    				"httpSettings": null,
    				"quicSettings": null,
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		},
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "freedom",
    			"tag": "direct",
    			"streamSettings": {
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		},
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "blackhole",
    			"tag": "block",
    			"streamSettings": {
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		},
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "dns",
    			"tag": "dns_out",
    			"streamSettings": {
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		}
    	]
    }

This is my config from 1.4
For me it looks like a problem with iptables. Could you help me to fix it?

**Comment by kuoruan** [comment]
What's the transparent proxy page like?

And the output of following command:

```
iptables -t nat -nL
```

**Comment by Tualua** [comment]
Here is iptables output

    root@OpenWrt:~# iptables -t nat -nL
    Chain PREROUTING (policy ACCEPT)
    target     prot opt source               destination
    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    V2RAY      tcp  --  0.0.0.0/0            0.0.0.0/0
    
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination
    
    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination
    V2RAY      tcp  --  0.0.0.0/0            0.0.0.0/0
    
    Chain POSTROUTING (policy ACCEPT)
    target     prot opt source               destination
    postrouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
    zone_lan_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    zone_wan_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    
    Chain V2RAY (2 references)
    target     prot opt source               destination
    RETURN     tcp  --  0.0.0.0/0            0.0.0.0/0            mark match 0xff
    RETURN     tcp  --  0.0.0.0/0            0.0.0.0/0            match-set v2ray_dst_direct_v4 dst
    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            redir ports 1081
    
    Chain postrouting_lan_rule (1 references)
    target     prot opt source               destination
    
    Chain postrouting_rule (1 references)
    target     prot opt source               destination
    
    Chain postrouting_wan_rule (1 references)
    target     prot opt source               destination
    
    Chain prerouting_lan_rule (1 references)
    target     prot opt source               destination
    
    Chain prerouting_rule (1 references)
    target     prot opt source               destination
    
    Chain prerouting_wan_rule (1 references)
    target     prot opt source               destination
    
    Chain zone_lan_postrouting (1 references)
    target     prot opt source               destination
    postrouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan postrouting rule chain */
    
    Chain zone_lan_prerouting (1 references)
    target     prot opt source               destination
    prerouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan prerouting rule chain */
    
    Chain zone_wan_postrouting (1 references)
    target     prot opt source               destination
    postrouting_wan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan postrouting rule chain */
    MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    
    Chain zone_wan_prerouting (1 references)
    target     prot opt source               destination
    prerouting_wan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan prerouting rule chain */
    root@OpenWrt:~#

And Transparent proxy tab.

![Annotation 2019-11-22 173220](https://user-images.githubusercontent.com/32481693/69414899-95335180-0d4e-11ea-9fb6-751f0cf746b1.png)

Also, I forgot to mention that DHCP stops working too. If you stop v2ray service - everything works fine

**Comment by kuoruan** [comment]
UDP redirect rules is missing, what's your LuCI version?

**Comment by Tualua** [comment]
Powered by LuCI Master (git-19.323.62983-cfd4db2) / OpenWrt SNAPSHOT r11538-1a0d6e1eba 

But the same problem was on 18.06.5, Even DHCP does not work.

    root@OpenWrt:~# iptables -t mangle -nL
    Chain PREROUTING (policy ACCEPT)
    target     prot opt source               destination
    V2RAY      udp  --  0.0.0.0/0            0.0.0.0/0
    
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination
    
    Chain FORWARD (policy ACCEPT)
    target     prot opt source               destination
    TCPMSS     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
    
    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination
    V2RAY_MARK  udp  --  0.0.0.0/0            0.0.0.0/0
    
    Chain POSTROUTING (policy ACCEPT)
    target     prot opt source               destination
    
    Chain V2RAY (1 references)
    target     prot opt source               destination
    RETURN     udp  --  0.0.0.0/0            0.0.0.0/0            mark match 0xff
    TPROXY     udp  --  0.0.0.0/0            0.0.0.0/0            TPROXY redirect 0.0.0.0:1081 mark 0x1/0x1
    
    Chain V2RAY_MARK (1 references)
    target     prot opt source               destination
    RETURN     udp  --  0.0.0.0/0            0.0.0.0/0            mark match 0xff
    MARK       udp  --  0.0.0.0/0            0.0.0.0/0            MARK set 0x1
    root@OpenWrt:~#

**Comment by kuoruan** [comment]
How about disable UDP proxy?

**Comment by Tualua** [comment]
The whole point is to make it work )) 
Does 1.3 support UDP proxy?

**Comment by kuoruan** [comment]
The iptables rules for UDP proxy on 1.4 is the same as 1.3.
So I don't know the reason why it can't work.

Do you use a custom config file?

**Comment by kuoruan** [comment]
What's the output of:
```iptables list v2ray_dst_direct_v4 | grep YOUR_SERVER_IP```

**Comment by Tualua** [comment]
It shows IP address of my v2ray server.
    root@OpenWrt:~# ipset list v2ray_dst_direct_v4 | grep <my_server_ip>
    <my_server_ip>
    root@OpenWrt:~#

**Comment by Tualua** [comment]
By the way, I have found, that on 1.3 UDP transparent proxy was not enabled. If I enable it - it breaks everything as in 1.4

What am I missing?
Could you share working config?

**Comment by Tualua** [comment]
> Do you use a custom config file?

No, I do not use custom config file

**Comment by kuoruan** [comment]
outdated issue, closing this
