### ISSUE TITLE
开启transparent proxy并且填入extra proxy list后，无法解析dns

### ISSUE THREAD

**Issue by vongoethe** [kuoruan/luci-app-v2ray#51]
开启transparent proxy并且填入extra proxy list后，无法解析dns。
在extra proxy list填入blogspot.com后，无法解析dns，无法上网，log如下，已经把域名替换为xxxxx.xxx

[Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx.xxx/ray):  > dial tcp: lookup xxxxx.xxx on 127.0.0.1:53: read udp 127.0.0.1:42711->127.0.0.1:53: read: connection refused v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx.xxx/ray):  > dial tcp: lookup xxxxx.xxx on 127.0.0.1:53: read udp 127.0.0.1:49203->127.0.0.1:53: read: connection refused v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx.xxx/ray):  > dial tcp: lookup xxxxx.xxx on 127.0.0.1:53: read udp 127.0.0.1:58375->127.0.0.1:53: read: connection refused v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx.xxx/ray):  > dial tcp: lookup xxxxx.xxx on 127.0.0.1:53: read udp 127.0.0.1:51333->127.0.0.1:53: read: connection refused v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx.xxx/ray):  > dial tcp: lookup xxxxx.xxx on 127.0.0.1:53: read udp 127.0.0.1:46210->127.0.0.1:53: read: connection refused] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by kuoruan** [comment]
看看 ```/tmp/dnsmasq.d/v2ray``` 里边有没有这个网址

**Comment by kuoruan** [comment]
然后把你的域名手动填入 Extra direct list

**Comment by vongoethe** [comment]
`/tmp/dnsmasq.d/v2ray` 里面有相应的域名。
开启透明代理后，一切正常，我手动填入 extra direct list 的域名也可以正常作用，但是一旦填写 extra proxy list 里面的域名后，就无法访问任何网站了，包括百度等国内网站，而且直接从 luci 界面无法删除填入的 extra proxy list 里面的域名，需要到 `/etc/v2ray` 路径下删除 proxylist.txt 文件才可以。
透明代理的模式我设置的是 fgwlist.txt 模式

**Comment by vongoethe** [comment]
如果不手动删除 `/etc/v2ray` 里面的 proxylist.txt 文件，即使关闭透明代理，依然无法上网

**Comment by kuoruan** [comment]
防火墙规则贴一下，需要信息

但是我发现列表剩最后一行的时候确实删不掉，我先看看这个问题

**Comment by vongoethe** [comment]
开启透明代理后，`iptables -t nat -nvL` 输出如下：

Chain PREROUTING (policy ACCEPT 265 packets, 27638 bytes)
 pkts bytes target     prot opt in     out     source               destination         
13815 1634K prerouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
10021 1313K zone_lan_prerouting  all  --  br-lan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 zone_wan_prerouting  all  --  eth0.2 *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
 3793  320K zone_wan_prerouting  all  --  pppoe-wan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    1  1010 zone_guest_prerouting  all  --  wlan1  *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
   77  4596 V2RAY      tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT 49 packets, 3752 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 101 packets, 6768 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    3   180 V2RAY      tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT 34 packets, 2278 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 7458  576K postrouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
  113 10531 zone_lan_postrouting  all  --  *      br-lan  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 zone_wan_postrouting  all  --  *      eth0.2  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
 6832  535K zone_wan_postrouting  all  --  *      pppoe-wan  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 zone_guest_postrouting  all  --  *      wlan1   0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain V2RAY (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    3   180 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xff
    9   576 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set v2ray_dst_direct_v4 dst
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set v2ray_dst_proxy_v4 dst redir ports 1081

**Comment by vongoethe** [comment]
`Chain PREROUTING (policy ACCEPT 3 packets, 542 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    6   726 prerouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
    4   262 zone_lan_prerouting  all  --  br-lan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 zone_wan_prerouting  all  --  eth0.2 *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 zone_wan_prerouting  all  --  pppoe-wan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    2   464 zone_guest_prerouting  all  --  wlan1  *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 V2RAY      tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT 1 packets, 78 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 V2RAY      tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    8   480 postrouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
    0     0 zone_lan_postrouting  all  --  *      br-lan  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 zone_wan_postrouting  all  --  *      eth0.2  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    6   364 zone_wan_postrouting  all  --  *      pppoe-wan  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 zone_guest_postrouting  all  --  *      wlan1   0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain V2RAY (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xff
    0     0 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set v2ray_dst_direct_v4 dst
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set v2ray_dst_proxy_v4 dst redir ports 1081

Chain postrouting_guest_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         `

**Comment by kuoruan** [comment]
如果你是用的自定义配置文件的话，v2ray_dst_direct_v4 这个 ipset 表里不会自动创建添加你服务器的 IP 地址。需要你手动在 Extra direct list 里边填入

**Comment by vongoethe** [comment]
extra direct list 部分没问题，有问题的是 extra proxy list 部分，一旦填入域名，就出现上述描述的问题了

**Comment by kuoruan** [comment]
填入 extra proxy list，然后开启透明代理
看看防火墙规则和 ```/tmp/dnsmasq.d/v2ray``` 和 ipset 是否正常

**Comment by kuoruan** [comment]
有可能是由于你的 dnsmasq 不支持 ipset 导致它没启动起来。

**Comment by vongoethe** [comment]
找到问题了，我的 dnsmasq 是 full 版本，这个 ok，ipset list 也正常
你说的对，问题出在 extra direct list 里面，我把 vmess 服务器的 ip 地址写了 direct list 里面，但是我的 vmess 用的是域名，我把服务器的域名也写到 extra direct list 里面，就正常了

**Comment by kuoruan** [comment]
我刚才做了个提交，使用自定义配置文件时自动扫描添加配置文件里边的服务端 IP
d53164628f91ac8787fc3b4461d328556507c7f6
马上发布一个新版本，用新版本后就不需要手动添加 direct 服务器域名了

**Comment by vongoethe** [comment]
> 我刚才做了个提交，使用自定义配置文件时自动扫描添加配置文件里边的服务端 IP
> [d531646](https://github.com/kuoruan/luci-app-v2ray/commit/d53164628f91ac8787fc3b4461d328556507c7f6)
> 马上发布一个新版本，用新版本后就不需要手动添加 direct 服务器域名了

非常感谢
