### ISSUE TITLE
How does proxy_list_dns and direct_list_dns work in transparent_proxy?

### ISSUE THREAD

**Issue by pongpongcn** [kuoruan/luci-app-v2ray#53]
While I do DNS queries, it still follows the rule of dns out.

```
2019/11/24 01:24:06 [Info] v2ray.com/core/app/dns: querying domain test1.xxx.jd.com at udp:223.5.5.5:53
2019/11/24 01:24:06 [Debug] v2ray.com/core/app/dns: querying DNS for: test1.xxx.jd.com.
2019/11/24 01:24:06 [Debug] v2ray.com/core/app/dns: updating IP records for domain:test1.xxx.jd.com.
2019/11/24 01:24:06 [Info] v2ray.com/core/app/dns: querying domain test1.xxx.jd.com at udp:223.5.5.5:53
2019/11/24 01:24:06 [Debug] v2ray.com/core/app/dns: querying DNS for: test1.xxx.jd.com.
2019/11/24 01:24:07 [Debug] v2ray.com/core/app/dns: updating IP records for domain:test1.xxx.jd.com.
2019/11/24 01:24:19 [Debug] v2ray.com/core/app/dns: querying DNS for: test1.xxx.google.com.
2019/11/24 01:24:19 [Debug] v2ray.com/core/app/dns: updating IP records for domain:test1.xxx.google.com.
2019/11/24 01:24:19 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain test1.xxx.google.com at server udp:8.8.8.8:53 > rcode: 3
2019/11/24 01:24:19 [Debug] v2ray.com/core/app/dns: querying DNS for: test1.xxx.google.com.
2019/11/24 01:24:19 [Debug] v2ray.com/core/app/dns: updating IP records for domain:test1.xxx.google.com.
2019/11/24 01:24:19 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain test1.xxx.google.com at server udp:8.8.8.8:53 > rcode: 3
```

```
config transparent_proxy 'main_transparent_proxy'
	option apnic_delegated_mirror 'apnic'
	option gfwlist_mirror 'github'
	option redirect_port '1081'
	option dns_proxy_enabled '1'
	option proxy_mode 'gfwlist_proxy'
	option proxy_list_dns '1.1.1.1#53'
	option direct_list_dns '114.114.114.114#53'
```

**Comment by kuoruan** [comment]
We use dnsmasq ipset to handle the proxy list and direct list

see ```/tmp/dnsmasq.d/v2ray

**Comment by pongpongcn** [comment]
OK, thanks. But my question is about proxy list DNS and direct list DNS.

Pocketpc

> On Nov 24, 2019, at 11:46, Xingwang Liao <notifications@github.com> wrote:
> 

﻿
We use dnsmasq ipset to handle the proxy list and direct list

see ```/tmp/dnsmasq.d/v2ray

**Comment by kuoruan** [comment]
Yes, the DNS you set will write to that file, dnsmasq will use the DNS server to resolve domain ip address and add the ip to direct ipset or proxy ipset.

If your DNS is not working, give more information, such us the iptables rules and transparent proxy settings and your config file.

**Comment by pongpongcn** [comment]
Got it. I should add a related DNS IP rule before the dns_out rule in route. I’d try later~

Pocketpc

> On Nov 24, 2019, at 12:44, Xingwang Liao <notifications@github.com> wrote:
> 

﻿
Yes, the DNS you set will write to that file, dnsmasq will use the DNS server to resolve domain ip address and add the ip to direct ipset or proxy ipset.

If your DNS is not working, give more information, such us the iptables rules and transparent proxy settings and your config file.

**Comment by pongpongcn** [comment]
Figured out.

1. Only domains in Extra proxy/direct list are assigned DNS server in dnsmasq config file, while domains in GFWList are not(only ipset). Well, this may be my misunderstanding.

    /etc/v2ray/proxylist.txt
    ```
    xxx.google.com
    ```

    /etc/v2ray/directlist.txt
    ```
    xxx.jd.com
    ```

    /tmp/dnsmasq.d/v2ray
    ```
    server=/xxx.jd.com/114.114.114.114
    ipset=/xxx.jd.com/v2ray_dst_direct_v4,v2ray_dst_direct_v6
    server=/xxx.google.com/1.1.1.1
    ipset=/xxx.google.com/v2ray_dst_proxy_v4,v2ray_dst_proxy_v6
    ipset=/youtu.be/v2ray_dst_proxy_v4,v2ray_dst_proxy_v6
    ipset=/youtube-nocookie.com/v2ray_dst_proxy_v4,v2ray_dst_proxy_v6
    ipset=/youtube.com/v2ray_dst_proxy_v4,v2ray_dst_proxy_v6
    ipset=/youtubecn.com/v2ray_dst_proxy_v4,v2ray_dst_proxy_v6
    ipset=/youtubeeducation.com/v2ray_dst_proxy_v4,v2ray_dst_proxy_v6
    ipset=/youtubegaming.com/v2ray_dst_proxy_v4,v2ray_dst_proxy_v6
    ```

    2. Destination DNS IP would go through V2Ray routing.

    With default plugin routing rules, `114.114.114.114` goes out to `direct`, `1.1.1.1` goes out to `dns_out`. So I just need add a new routing rule for `1.1.1.1`.

**Comment by kuoruan** [comment]
Actually, it's a bug. I will fix it.
