### ISSUE TITLE
Missing v2ray_dst_proxy_v6 in v2ray rules

### ISSUE THREAD

**Issue by pongpongcn** [kuoruan/luci-app-v2ray#54]
I haven't find similar code for `$IPSET_DST_PROXY_V6` like below.

https://github.com/kuoruan/luci-app-v2ray/blob/58475b1d39ec9aae3833cb7004a26bc6ccf6966d/root/etc/init.d/v2ray#L999

Is it a feature on the road map?

**Comment by kuoruan** [comment]
Currently not support ip6tables, but the ipset list has created for future use.
