### ISSUE TITLE
Ipset needs default timeout value.

### ISSUE THREAD

**Issue by pongpongcn** [kuoruan/luci-app-v2ray#55]
In my practice, I create gfwlist with a timeout value.

```
ipset create gfwlist hash:ip timeout 604800
```

It's useful for dnsmasq resolving result, because the IP of domains is not static. For long time running situation, wrong IP may goes through proxy or direct.

If you add IP directly into ipset(non DNS resolving result), that should never timeout.

```
ipset add gfwlist <targetIP> 0
```

Thanks for you greate work.

**Comment by kuoruan** [comment]
Done, thank you for the advice.
