### ISSUE TITLE
在 Transparent Proxy 配置页面更新 GFWList/CHNRoute 失败

### ISSUE THREAD

**Issue by thrieu** [kuoruan/luci-app-v2ray#56]
在 Transparent Proxy 配置页面点击“Update”按钮更新 GFWList/CHNRoute 失败，如下图。
我用的三个 Linksys WRT1900acs v2 路由器都这样，请问可能是什么原因？

![TIM图片20191120231544](https://user-images.githubusercontent.com/4617698/69788033-9c4bdb00-11f8-11ea-94c2-4eaccc0be022.png)

**Comment by kuoruan** [comment]
查看你的系统日志。
Check your System log.
