### ISSUE TITLE
关于代理配置问题求教

### ISSUE THREAD

**Issue by chenchunwei** [kuoruan/luci-app-v2ray#57]
你好，使用插件配置V2Ray的时候配置netfilter的时候没有弄好，求教下，谢谢：
1、v2ray的配置生成如下：
{
	"log": {
		"access": "/dev/null",
		"loglevel": "warning",
		"error": "/var/log/v2ray-error.log"
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			}
		]
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1080,
			"protocol": "socks",
			"sniffing": {
				"enabled": false
			},
			"settings": {
				"ip": "",
				"userLevel": 0,
				"timeout": 360,
				"udp": false,
				"auth": "noauth"
			}
		},
		{
			"listen": "127.0.0.1",
			"port": 1087,
			"protocol": "http",
			"sniffing": {
				"enabled": false
			},
			"settings": {
				"timeout": 360
			}
		}
	],
	"outbounds": [
		{
			"sendThrough": "0.0.0.0",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "vmess server",
						"users": [
							{
								"id": "uuid*****",
								"alterId": 4,
								"level": 0,
								"security": "aes-128-gcm"
							}
						],
						"port": 8080
					}
				]
			},
			"streamSettings": {
				"wsSettings": {
					"path": "/v2ray",
					"headers": {
						"host": "amazon.cn"
					}
				},
				"tlsSettings": {
					"allowInsecure": true
				},
				"security": "none",
				"network": "ws",
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "freedom",
			"tag": "direct",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		},
		{
			"sendThrough": "0.0.0.0",
			"protocol": "blackhole",
			"tag": "block",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
		}
	]
}
---------------------
配置的透明代理为：
人工指定端口:1080
保存生成

查看服务器的nat配置如下：
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
V2RAY      tcp  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
V2RAY      tcp  --  0.0.0.0/0            0.0.0.0/0           

Chain V2RAY (2 references)
target     prot opt source               destination         
RETURN     tcp  --  0.0.0.0/0            0.0.0.0/0            mark match 0xff
RETURN     tcp  --  0.0.0.0/0            0.0.0.0/0            match-set v2ray_dst_direct_v4 dst
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            redir ports 1080

---------------------
但在服务器上curl https://www.google.com的时候提示：

 curl https://www.google.com -v
*   Trying 69.171.224.85...
* TCP_NODELAY set
* Connected to www.google.com (69.171.224.85) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 

---------------------
如果主动添加socks代理指定的话可以正常访问：
curl -x socks://127.0.0.1:1080 http://www.google.com 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.hk/url?sa=p&amp;hl=zh-CN&amp;pref=hkredirect&amp;pval=yes&amp;q=http://www.google.com.hk/&amp;ust=1574942570273549&amp;usg=AOvVaw3In311NG8y8yXDjxMhZvTJ">here</A>.
</BODY></HTML>

求指教，谢谢

**Comment by kuoruan** [comment]
请使用任意门协议做透明代理

**Comment by chenchunwei** [comment]
> 请使用任意门协议做透明代理

原来这么简单就可以搞定，我舍近求远了，谢谢
