### ISSUE TITLE
請問有沒有簡單的說明或範本？把Openwrt變成區網內的翻牆gateway

### ISSUE THREAD

**Issue by kousyougi** [kuoruan/luci-app-v2ray#58]
我的環境是
路由器是192.168.0.1，區網內所有網路都是從這個路由器出去。
有一台Openwrt X86 generic 18.06.5 虛擬機是 192.168.0.2
已經把v2ray-core_4.21.3-1_i386_pentium4.ipk 跟 luci-app-v2ray_1.4.3-1_all.ipk
 裝在那個Openwrt X86上了。

我的目的是想要讓區網內那台Openwrt(192.168.0.2)，設定透明代理(TCP跟UDP)，變成翻牆出去的gateway。(區網內的設備只要gateway設定192.168.0.2，TCP跟UDP就會翻牆出去)

查了好多設定，試了好多方法都沒成功。透明代理那邊一直失敗。

請問有沒有關於這個的設定教學或範本？
如果有的話，每個人家裡都能用虛擬機做一個翻牆gateway，
另外對應其他不同的狀況，也會變得單純很多。

感激

**Comment by kuoruan** [comment]
把你的配置信息給一下，包括配置文件內容和透明代理頁截圖

**Comment by kousyougi** [comment]
謝謝你的回覆

V2ray的設定似乎是沒有問題，我的DNS、Routing、Policy、Reverse那幾頁功能全部設定關閉，inbound只設定dokodemo-door，outbound只設定vmess。感覺是透明代理iptable那邊不知道出了什麼問題。

![trans](https://user-images.githubusercontent.com/43228565/70121665-66a06980-16b2-11ea-8c58-31ce016923e3.png)

然後CHNRoute跟GFWList按Update的時候會瞬間跳出List update failed. 完全沒有連線那種感覺。

![error](https://user-images.githubusercontent.com/43228565/70121684-6d2ee100-16b2-11ea-8ace-a146edf028b5.png)


我後來照：
https://github.com/felix-fly/v2ray-dnsmasq-dnscrypt
這邊的做法弄成功了。
我的需求主要只用到V2ray的inbound:dokodemo-door、outbound:vmess跟iptable而已，這個傻瓜套餐對我來說反而比較不會出錯。

**Comment by kuoruan** [comment]
1. 关掉 UDP proxy 试试；
2. List 无法升级时看看你的系统日志，有解决方案；

总之，能用就行了。

**Comment by kousyougi** [comment]
謝謝你的回覆。
我把UDP proxy關掉，然後把tproxy改成redrect就正常了。
現在UDP+tproxy的透明代理一直都失敗。不知該怎麼解。

**Comment by kuoruan** [comment]
现在还不支持 tproxy 的代理，下个版本会支持
