### ISSUE TITLE
It does not work through a modem connected via the NCM protocol

### ISSUE THREAD

**Issue by Yolkis** [kuoruan/luci-app-v2ray#59]
Hello! I am a user from Russia!
I tried v2ray and it turned out to be superfast on my mobile network. I decided to run it on the router by connecting a modem to it.
Everything worked perfectly with the HiLink modem, but when it was switched to NCM mode, nothing worked.
The fact is that connecting via NCM is faster than HiLink
It was worth turning off v2ray everything worked again
[There is a log of v2ray](https://pastebin.com/hmWYVquu)
Help please :)

**Comment by Yolkis** [comment]
I can provide all the configs, but I don’t know which ones

**Comment by Yolkis** [comment]
FIrewall Status
![Screenshot_2019-11-29 OpenWrt - Firewall - LuCI](https://user-images.githubusercontent.com/30495707/69840730-bfbd6700-1286-11ea-9950-ce3372000664.png)

**Comment by Yolkis** [comment]
Firewall Status when v2ray is turned on
![Screenshot_2019-11-29 OpenWrt - Firewall - LuCI(1)](https://user-images.githubusercontent.com/30495707/69840862-43775380-1287-11ea-86df-14e07e863cee.png)

**Comment by Yolkis** [comment]
Routes
![Screenshot_2019-11-29 OpenWrt - Routes - LuCI](https://user-images.githubusercontent.com/30495707/69840927-6d307a80-1287-11ea-8624-9a2a0b25a25f.png)

**Comment by Yolkis** [comment]
I think the problem is in the dynamic ip address of the NCM interface (wwan0)

**Comment by Yolkis** [comment]
![Screenshot_2019-11-29 OpenWrt - Inbound - LuCI](https://user-images.githubusercontent.com/30495707/69841085-1a0af780-1288-11ea-952a-3e1dd98ecf7c.png)
![Screenshot_2019-11-29 OpenWrt - About - LuCI](https://user-images.githubusercontent.com/30495707/69841086-1aa38e00-1288-11ea-8689-d08d9a7ac165.png)
![Screenshot_2019-11-29 OpenWrt - Transparent Proxy - LuCI](https://user-images.githubusercontent.com/30495707/69841087-1aa38e00-1288-11ea-9fd9-46e6bf049e77.png)

**Comment by kuoruan** [comment]
It seems no output traffic through iptables nat table chain OUTPUT?

**Comment by Yolkis** [comment]
> It seems no output traffic through iptables nat table chain OUTPUT?

How can I fix it :D

**Comment by kuoruan** [comment]
Clear your error log, enable V2Ray and transparent proxy to see if there is any traffic redirect to V2Ray.

**Comment by Yolkis** [comment]
[Done](https://pastebin.com/YbtLDpiv)
Log Level is info

**Comment by kuoruan** [comment]
I look back to your screen shot, find that your outbounds' streamSettings is error.

Edit it  and see if it works.

**Comment by Yolkis** [comment]
Hmmmm..

is it correct?
{
   "upstream_vmess": {
     "tlssettings": {
       "serverName": "online.sberbank.ru",
       "allowInsecure": true
     },
     "wssettings": {
       "path": "",
       "connectionReuse": true,
       "headers": {
         "Host": "online.sberbank.ru"
       }
     },
     "network": "ws",
     "security": ""
   }
 }

**Comment by kuoruan** [comment]
see: https://www.v2ray.com/en/configuration/transport.html#streamsettingsobject

**Comment by kuoruan** [comment]
Any update?

**Comment by Yolkis** [comment]
I deleted outbounds' streamSettings
It doesn't work yet

**Comment by kuoruan** [comment]
Not delete your outbounds' streamSettings, it shoud be:

```json
{
  "tlssettings": {
    "serverName": "online.sberbank.ru",
    "allowInsecure": true
  },
 "wssettings": {
    "path": "",
    "connectionReuse": true,
    "headers": {
    "Host": "online.sberbank.ru"
  },
  "network": "ws",
  "security": ""
}
```

which match your v2ray config.
