### ISSUE TITLE
display problem for "/" in "Stream settings" 

### ISSUE THREAD

**Issue by rny** [kuoruan/luci-app-v2ray#6]
when write path in Stream settings

```
"path": "/ws/"
```

save, it shows

```
"path": "\/ws\/"
```

**Comment by kuoruan** [comment]
http://www.json.org/ recommend to escapes slashes.
![20190707103501](https://user-images.githubusercontent.com/8685618/60763260-2c02b880-a0a3-11e9-9a76-5b64bbc828f2.png)
and it's the default behavior by lua, I can't change it.
