### ISSUE TITLE
大佬 可以搞个 高恪能用的版本？

### ISSUE THREAD

**Issue by mlpzaq9998** [kuoruan/luci-app-v2ray#60]
由于需要用单线并发多拨功能，只能用高恪固件，但别人写的只有SSR，现在太容易封了，你的包里所需要的依赖
LUCI_DEPENDS:=+jshn +luci-lib-jsonc +ip +ipset +iptables +iptables-mod-tproxy \
	+resolveip +dnsmasq-full
高恪 找不到luci-lib-jsonc，并且没有iptables-mod-tproxy，不能UPD转发，但udp转发也没啥用，dnsmasq-full是不带dnsmasq的版本，编译ipk需要https://archive.openwrt.org/barrier_breaker/14.07/ramips/mt7620a/OpenWrt-SDK-ramips-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
不求功能多 ，只要可以订阅v2ray并自动透明代理就好，可以吗大佬

**Comment by kuoruan** [comment]
我估计会在下个版本移除 luci-lib-jsonc
但是高恪没用过，不知道怎么写，如有需要，可以自行修改

**Comment by mlpzaq9998** [comment]
这个是SSR 高恪能用的，高恪脚本是op BB 版本 脚本什么的运行都一样，只不过luci 定义模块可能不大一样 ，大佬可以改个，给测试吗？
https://github.com/mlpzaq9998/openwrt-feeds/tree/master/applications/luci-app-shadowsocksr

**Comment by kuoruan** [comment]
无此计划。
