### ISSUE TITLE
[Request] Create configuration interface for non-advanced users

### ISSUE THREAD

**Issue by Yolkis** [kuoruan/luci-app-v2ray#62]
Creating a configuration interface for non-advanced users will simplify the configuration and also reduce configuration errors

How I see interface, like in V2rayNG android app
![photo_2019-12-01_09-46-13](https://user-images.githubusercontent.com/30495707/69909094-a13ea380-141f-11ea-81b8-5bdffeaf6e0e.jpg)

**Comment by kuoruan** [comment]
In development.

**Comment by sharljimhtsin** [comment]
i need it very much~

generate config.json step by step is GOOD.

thank you~
