### ISSUE TITLE
is outbound which network type is WS with subpath supported?

### ISSUE THREAD

**Issue by sharljimhtsin** [kuoruan/luci-app-v2ray#63]
i try to create a outbound using websocket,and its url is not just a root path. i save the config via luci web,and check the generated main.json, i can not find the info about subpath in it.

why? i made a wrong configuration or it is not supported ?

**Comment by sharljimhtsin** [comment]
and i edit a 3rd json file with above outbound. upload and using this file via web,reload and restart v2ray,and not work either.plz help.

**Comment by kuoruan** [comment]
you need to add your wsSettings to Stream Settings field.
it's a json object.

**Comment by sharljimhtsin** [comment]
i upgrade app to latest version,and edit it again.it works now. thank you.
