### ISSUE TITLE
无法运行在openwrt master

### ISSUE THREAD

**Issue by fuqiang03** [kuoruan/luci-app-v2ray#64]
无法运行在openwrt master
手动执行也无效果
![QQ截图20191202142847](https://user-images.githubusercontent.com/26851715/69935543-328d4300-1510-11ea-8b64-09764417bb47.png)
但是没有报错误

**Comment by kuoruan** [comment]
信息不足，请提供详细信息。

**Comment by fuqiang03** [comment]
openwrt 主库的代码和openwrt18.06代码都无法启动 貌似上个版本好好的
这个图是路由器的配置
![QQ截图20191202150231](https://user-images.githubusercontent.com/26851715/69937208-0fb15d80-1515-11ea-84f2-61e47f268b8c.png)

**Comment by kuoruan** [comment]
看文件而不是界面。
```/etc/config/v2ray```

**Comment by fuqiang03** [comment]
[v2ray.txt](https://github.com/kuoruan/luci-app-v2ray/files/3909876/v2ray.txt)

**Comment by kuoruan** [comment]
你用的哪个版本？

```
ps -w | grep v2ray
```
是否有输出？

**Comment by fuqiang03** [comment]
![QQ截图20191202152858](https://user-images.githubusercontent.com/26851715/69938595-b1867980-1518-11ea-9a0a-e4aedae27de9.png)
![QQ截图20191202152929](https://user-images.githubusercontent.com/26851715/69938601-b3e8d380-1518-11ea-878c-884087750ca7.png)
有输出

**Comment by kuoruan** [comment]
```
/etc/init.d/v2ray start
```
然后看看你的系统日志

**Comment by fuqiang03** [comment]
Mon Dec  2 22:51:00 2019 cron.err crond[8394]: USER root pid 20208 cmd /usr/bin/set_kernel_timezone >/dev/null 2>&1
Mon Dec  2 22:51:11 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 22:51:11 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 22:51:11 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 22:51:11 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 12 crashes, 0 seconds since last crash
Mon Dec  2 22:51:12 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 22:51:12 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 22:51:12 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 22:51:12 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 13 crashes, 0 seconds since last crash
Mon Dec  2 22:51:25 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 22:51:25 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 22:51:25 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 22:51:25 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 14 crashes, 0 seconds since last crash
Mon Dec  2 22:51:26 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 22:51:26 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 22:51:26 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 22:51:26 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 15 crashes, 0 seconds since last crash
Mon Dec  2 22:51:47 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 22:51:47 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 22:51:47 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 22:51:47 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 16 crashes, 0 seconds since last crash
Mon Dec  2 22:51:48 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 22:51:48 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 22:51:48 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 22:51:48 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 17 crashes, 0 seconds since last crash
Mon Dec  2 23:21:46 2019 authpriv.info dropbear[3288]: Child connection from 192.168.1.2:14057
Mon Dec  2 23:21:46 2019 authpriv.notice dropbear[3288]: Auth succeeded with blank password for 'root' from 192.168.1.2:14057
Mon Dec  2 23:31:00 2019 daemon.notice ttyd[13225]: HTTP / - 192.168.1.2 (192.168.1.2)
Mon Dec  2 23:31:00 2019 daemon.notice ttyd[13225]: HTTP /auth_token.js - 192.168.1.2 (192.168.1.2)
Mon Dec  2 23:31:00 2019 daemon.notice ttyd[13225]: WS   /ws - 192.168.1.2 (192.168.1.2), clients: 1
Mon Dec  2 23:31:01 2019 daemon.notice ttyd[13225]: started process, pid: 8136
Mon Dec  2 23:39:13 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 23:39:46 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 23:39:46 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 23:39:46 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 23:40:11 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 6 crashes, 0 seconds since last crash
Mon Dec  2 23:40:35 2019 daemon.info v2ray: Policy disabled: main_policy
Mon Dec  2 23:40:35 2019 daemon.info v2ray: Reverse disabled: main_reverse
Mon Dec  2 23:40:35 2019 daemon.info v2ray: Transparent proxy disabled.
Mon Dec  2 23:40:35 2019 daemon.info procd: Instance v2ray::v2ray.main s in a crash loop 7 crashes, 0 seconds since last crash

**Comment by kuoruan** [comment]
现在明白了吗？检查一下你的配置文件。

把配置文件拷贝出来，手动跑一下

```
v2ray -config v2ray.main.json
```

**Comment by fuqiang03** [comment]
哎  饭了个低级错误 v2ray 构架我编译错了
![QQ截图20191202162547](https://user-images.githubusercontent.com/26851715/69943726-8c960480-1520-11ea-89ff-c2275bd143dd.png)
