### ISSUE TITLE
路由/tmp/dnsmasq.d里没有v2ray文件   v2ray正常运行但不能翻墙

### ISSUE THREAD

**Issue by yangguangyu369** [kuoruan/luci-app-v2ray#65]
安装在openwrt-18.06.5-x86-64-combined-ext4.img版本,正常配置后运行,发现/tmp/dnsmasq.d里没有v2ray文件,路由也不能翻墙,系统日志:daemon.info v2ray: Transparent proxy disabled.同样配置在其他软路由上正常使用.求解决

**Comment by kuoruan** [comment]
确定一下你是否启用透明代理，并把配置和相关页面截图

**Comment by yangguangyu369** [comment]
![image](https://user-images.githubusercontent.com/56715620/69944053-54db8c80-1521-11ea-89c9-8b8d7b3b95f8.png)

**Comment by yangguangyu369** [comment]
![image](https://user-images.githubusercontent.com/56715620/69944142-88b6b200-1521-11ea-802d-0bd60d7048ed.png)

**Comment by kuoruan** [comment]
在透明代理页面启用一下透明代理，设置成你的任意门端口 12345

**Comment by yangguangyu369** [comment]
开启以后什么网也连不上了

**Comment by yangguangyu369** [comment]
![image](https://user-images.githubusercontent.com/56715620/69944507-7426e980-1522-11ea-8a2e-25cde2eb3627.png)

**Comment by yangguangyu369** [comment]
在防火墙自定义

**Comment by yangguangyu369** [comment]
![image](https://user-images.githubusercontent.com/56715620/69945048-b69cf600-1523-11ea-8130-6876e14eddd9.png)

**Comment by kuoruan** [comment]
LuCI 会自动帮你添加防火墙规则，请勿重复添加

**Comment by yangguangyu369** [comment]
已经解决,谢谢了
