### ISSUE TITLE
transparent proxy on causes crash on Koolshare mod v2.33

### ISSUE THREAD

**Issue by RoninYuan-WY** [kuoruan/luci-app-v2ray#66]
can't turn on dokodemo door in transparent proxy. socks proxy works fine.

**Comment by kuoruan** [comment]
Please check your system log.

**Comment by RoninYuan-WY** [comment]
before going further, I found when I install luci-app-v2ray, it shows below:
root@Openwrt:~# opkg install luci-app-v2ray_1.4.3-1_all.ipk 
Installing luci-app-v2ray (1.4.3-1) to root...
Configuring luci-app-v2ray.
[info] Transparent proxy disabled.
root@Openwrt:~#

**Comment by RoninYuan-WY** [comment]
logread keep running when I access yb, like below, and I interrupted it later then.

Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:81 +0x49
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.Copy(0xe20180, 0xc005ec3cc0, 0xe1f9e0, 0xc0032ce460, 0xc00058af68, 0x1, 0x1, 0xe39720, 0xc001d5df80)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:104 +0xa8
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/proxy/freedom.(*Handler).Process.func2(0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/proxy/freedom/freedom.go:156 +0x1c5
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.Run.func1(0xc005ec3d20, 0xc000ee1c20, 0xc0061b6af0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:28 +0x2b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: created by v2ray.com/core/common/task.Run
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:27 +0xd7
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: goroutine 13421 [IO wait]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.runtime_pollWait(0x7f85769da470, 0x72, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	runtime/netpoll.go:184 +0x55
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.(*pollDesc).wait(0xc003c4e498, 0x72, 0x800, 0x800, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	internal/poll/fd_poll_runtime.go:87 +0x45
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.(*pollDesc).waitRead(...)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	internal/poll/fd_poll_runtime.go:92
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.(*FD).ReadFrom(0xc003c4e480, 0xc006251000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	internal/poll/fd_unix.go:219 +0x1c3
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: net.(*netFD).readFrom(0xc003c4e480, 0xc006251000, 0x800, 0x800, 0xc0000ab560, 0xc000474230, 0x20, 0x18, 0xc006259bd8)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	net/fd_unix.go:208 +0x5b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: net.(*UDPConn).readFrom(0xc005ec3d18, 0xc006251000, 0x800, 0x800, 0x7f85792b86d0, 0x0, 0xc006259c58, 0x40d756)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	net/udpsock_posix.go:47 +0x6a
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: net.(*UDPConn).ReadFrom(0xc005ec3d18, 0xc006251000, 0x800, 0x800, 0xc006251000, 0xc000052700, 0x7f85792b86d0, 0x0, 0x800)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	net/udpsock.go:121 +0x5d
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/transport/internet.(*packetConnWrapper).Read(0xc00338ac60, 0xc006251000, 0x800, 0x800, 0xc62380, 0x1, 0xc00338aec0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/transport/internet/system_dialer.go:123 +0x51
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.(*Buffer).ReadFrom(0xc00338aec0, 0x7f8576df8c88, 0xc00338ac60, 0xc000051d50, 0x8, 0x8)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/buffer.go:175 +0x73
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.readOneUDP(0x7f8576df8c88, 0xc00338ac60, 0xc005ec3d28, 0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/reader.go:13 +0xe8
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.(*PacketReader).ReadMultiBuffer(0xc0032ce3f0, 0x20, 0xc29880, 0xc005ec3d28, 0xc00338ae80, 0xc000051de8)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/reader.go:178 +0x3b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.copyInternal(0xe1f9a0, 0xc0032ce3f0, 0xe201a0, 0xc005ec3ce8, 0xc00338ae20, 0xc000051e01, 0xc00338ad00)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:81 +0x49
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.Copy(0xe1f9a0, 0xc0032ce3f0, 0xe201a0, 0xc005ec3ce8, 0xc000051f40, 0x1, 0x1, 0x8000000000000, 0x38)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:104 +0xa8
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/proxy/freedom.(*Handler).Process.func3(0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/proxy/freedom/freedom.go:172 +0x1a1
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.OnSuccess.func1(0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:12 +0x2f
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.Run.func1(0xc005ec3d20, 0xc000ee1c20, 0xc00338ace0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:28 +0x2b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: created by v2ray.com/core/common/task.Run
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:27 +0xd7
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: goroutine 13406 [select]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.Run(0xe32260, 0xc00248c7e0, 0xc006273e70, 0x3, 0x3, 0xc002b80a00, 0xe395a0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:42 +0x1ea
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/proxy/dokodemo.(*DokodemoDoor).Process(0xc000460b40, 0xe32260, 0xc0
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:81 +0x49
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.Copy(0xe20180, 0xc005ec3cc0, 0xe1f9e0, 0xc0032ce460, 0xc00058af68, 0x1, 0x1, 0xe39720, 0xc001d5df80)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:104 +0xa8
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/proxy/freedom.(*Handler).Process.func2(0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/proxy/freedom/freedom.go:156 +0x1c5
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.Run.func1(0xc005ec3d20, 0xc000ee1c20, 0xc0061b6af0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:28 +0x2b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: created by v2ray.com/core/common/task.Run
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:27 +0xd7
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: goroutine 13421 [IO wait]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.runtime_pollWait(0x7f85769da470, 0x72, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	runtime/netpoll.go:184 +0x55
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.(*pollDesc).wait(0xc003c4e498, 0x72, 0x800, 0x800, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	internal/poll/fd_poll_runtime.go:87 +0x45
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.(*pollDesc).waitRead(...)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	internal/poll/fd_poll_runtime.go:92
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: internal/poll.(*FD).ReadFrom(0xc003c4e480, 0xc006251000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	internal/poll/fd_unix.go:219 +0x1c3
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: net.(*netFD).readFrom(0xc003c4e480, 0xc006251000, 0x800, 0x800, 0xc0000ab560, 0xc000474230, 0x20, 0x18, 0xc006259bd8)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	net/fd_unix.go:208 +0x5b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: net.(*UDPConn).readFrom(0xc005ec3d18, 0xc006251000, 0x800, 0x800, 0x7f85792b86d0, 0x0, 0xc006259c58, 0x40d756)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	net/udpsock_posix.go:47 +0x6a
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: net.(*UDPConn).ReadFrom(0xc005ec3d18, 0xc006251000, 0x800, 0x800, 0xc006251000, 0xc000052700, 0x7f85792b86d0, 0x0, 0x800)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	net/udpsock.go:121 +0x5d
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/transport/internet.(*packetConnWrapper).Read(0xc00338ac60, 0xc006251000, 0x800, 0x800, 0xc62380, 0x1, 0xc00338aec0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/transport/internet/system_dialer.go:123 +0x51
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.(*Buffer).ReadFrom(0xc00338aec0, 0x7f8576df8c88, 0xc00338ac60, 0xc000051d50, 0x8, 0x8)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/buffer.go:175 +0x73
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.readOneUDP(0x7f8576df8c88, 0xc00338ac60, 0xc005ec3d28, 0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/reader.go:13 +0xe8
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.(*PacketReader).ReadMultiBuffer(0xc0032ce3f0, 0x20, 0xc29880, 0xc005ec3d28, 0xc00338ae80, 0xc000051de8)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/reader.go:178 +0x3b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.copyInternal(0xe1f9a0, 0xc0032ce3f0, 0xe201a0, 0xc005ec3ce8, 0xc00338ae20, 0xc000051e01, 0xc00338ad00)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:81 +0x49
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/buf.Copy(0xe1f9a0, 0xc0032ce3f0, 0xe201a0, 0xc005ec3ce8, 0xc000051f40, 0x1, 0x1, 0x8000000000000, 0x38)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/buf/copy.go:104 +0xa8
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/proxy/freedom.(*Handler).Process.func3(0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/proxy/freedom/freedom.go:172 +0x1a1
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.OnSuccess.func1(0x0, 0x0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:12 +0x2f
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.Run.func1(0xc005ec3d20, 0xc000ee1c20, 0xc00338ace0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:28 +0x2b
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: created by v2ray.com/core/common/task.Run
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:27 +0xd7
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: goroutine 13406 [select]:
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/common/task.Run(0xe32260, 0xc00248c7e0, 0xc006273e70, 0x3, 0x3, 0xc002b80a00, 0xe395a0)
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: 	v2ray.com/core@/common/task/task.go:42 +0x1ea
Tue Dec 10 23:49:59 2019 daemon.err v2ray[23152]: v2ray.com/core/proxy/dokodemo.(*DokodemoDoor).Process(0xc000460b40, 0xe32260, 0xc0

**Comment by RoninYuan-WY** [comment]
CPU and memory exhausted after that.

**Comment by kuoruan** [comment]
Try new version, and see if it works now.

**Comment by StoneMoe** [comment]
> CPU and memory exhausted after that.

I meet this issue too.

I use telnet to connect dokodemo door port directly and send some random string, then RAM and CPU exhausted. when I disconnect and try to connect again, v2ray process crashed.

But I tested it with same configuration on other platform(on my mac), dokodemo door port will reject the connection instantly, that's wired.

Details:
1. Openwrt 18.06.2 r7676-cddd7b4c77
2. arch x86_64
3. v2ray 4.22.1 from kuoruan's opkg repository (current latest)

**Comment by kuoruan** [comment]
@StoneMoe Did you try official build?

**Comment by StoneMoe** [comment]
> @StoneMoe Did you try official build?

I tried the build for darwin like I said above, on my mac.

What do you mean exactly?

**Comment by kuoruan** [comment]
@RoninYuan-WY Install official build v2ray in your router and try send data to dokodemo-door port.

**Comment by RoninYuan-WY** [comment]
I have been testing on a fresh new router img and it works with all your app and core ipk, I investigated GFWlist mod failure, I found it may be related to DNS query mechanism under this settings with related DNS settings and DNS proxy ticked or not, because I found the failure when I first switched to GFWlist mode, and it worked after I manually add ipv6 dns because I am using two stack.

**Comment by RoninYuan-WY** [comment]
BTW, I found other issues that I can't update CHNROUTE but GFWLIST, and ad-block route rule seems no function.

**Comment by kuoruan** [comment]
libustream-openssl and ca-bundle is required if you want to update list.

**Comment by RoninYuan-WY** [comment]
I have properly installed both and I can update GFWLIST, but fail on updating CHNROUTE

**Comment by kuoruan** [comment]
Maybe timeout. Enable proxy and try update, or use another mirror.

**Comment by RoninYuan-WY** [comment]
I found the failure reason that v2ray cause 'nf_conntrack: table full' when I started to update CHNROUTE, I did several test on fresh new router img, and found v2ray run out of memory when the setting was default of proxy mode, which is exactly same failure log I first raised in this thread, after I switched proxy mode to either CN direct or GFWLIST mode, it was stable. But the issue seems intermittent at this moment.

**Comment by RoninYuan-WY** [comment]
Just can't update CHNROUTE anyway, no clue in the log either, can you show me the script to update CHNROUTE, so I want to test it manually.

**Comment by kuoruan** [comment]
https://github.com/kuoruan/luci-app-v2ray/blob/f2e3521e8930c301c19a14eb93263eb0b4b7f281/luasrc/model/v2ray.lua#L112-L184

**Comment by RRRRRm** [comment]
I have the same problem on OpenWRT 19.07.0
