### ISSUE TITLE
匹配koolshare的lede似乎有些问题

### ISSUE THREAD

**Issue by sitieqiang** [kuoruan/luci-app-v2ray#67]
我再koolshare的lede中无法 看到有些选项似乎没有办法显示出来  我再其他人的issuse中看到的是
![image](https://user-images.githubusercontent.com/42805344/70528534-5b08e300-1b89-11ea-9879-f8e8d0b22590.png)的但是再我的这里是
![image](https://user-images.githubusercontent.com/42805344/70528605-8db2db80-1b89-11ea-8ff7-ee5c3424ebd8.png)
![image](https://user-images.githubusercontent.com/42805344/70528621-986d7080-1b89-11ea-9242-695417f67875.png)并没有 启用透明代理的选项 请大佬帮看看

**Comment by kuoruan** [comment]
启用透明代理的选项已经移动到了透明代理 TAB
