### ISSUE TITLE
DNS配置不支持DoH

### ISSUE THREAD

**Issue by riverscn** [kuoruan/luci-app-v2ray#69]
参考文档
https://www.v2ray.com/chapter_02/04_dns.html
目前报错
![Snipaste_2019-12-16_12-29-54](https://user-images.githubusercontent.com/555062/70879359-f83b9f80-1fff-11ea-9bd7-bf2ef9011af5.png)

**Comment by kuoruan** [comment]
这个问题会在以后的版本修复，你可以先通过修改配置文件填入
