### ISSUE TITLE
关于dns_out

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/luci-app-v2ray#70]
您好。有一点不解：在全局设置的出站代理中选中“dns_out”，去看/var/etc里的配置文件，虽然outbound里有了dns_out，但没有相应的路由规则。那么，这条outbound不成了摆设？

（还有，透明代理如果选中代理UDP，就不能翻墙了。不知是我哪里弄的不对。）

**Comment by kuoruan** [comment]
我在默认配置里提供了一条 dns route，可以启用它
具体可以参考这里：
1. https://steemit.com/cn/@v2ray/dns
2. https://medium.com/@TachyonDevel/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0

至于 UDP 代理的问题，可以查看一下你的日志

**Comment by dalton-chiou** [comment]
谢谢回答。可能我前面没有描述清楚，我的意思是，在v2ray路由中是不是应该有类似“ "outboundTag": "dns_out" 这样的一条？现在是没有的。

**Comment by kuoruan** [comment]
有的
https://github.com/kuoruan/luci-app-v2ray/blob/73a3b0977d58d274b9721468fa4c6b9b60f7d78c/root/etc/config/v2ray#L63-L69

**Comment by dalton-chiou** [comment]
是的。我以前没注意这个文件，只看到/var/etc/v2ray/v2ray.main.json里没有。

**Comment by kuoruan** [comment]
```/var/etc/v2ray/v2ray.main.json``` 这个文件是自动生成的
