### ISSUE TITLE
提示：无法获取 V2Ray 版本信息

### ISSUE THREAD

**Issue by tinyhugh** [kuoruan/luci-app-v2ray#71]
我的路由器是斐讯K3，openwrt固件，我尝试了所有arm开头的安装包，只有arm a9可以安装，但是提示无法获取 V2Ray 版本信息，我也尝试了从v2ray-core上下载自行安装最新版本及最近的几个版本，均提示无法获取 V2Ray 版本信息。这个是不支持我的路由器吗？还是仅支持个别版本？通过v2ray --version命令，提示Illegal instruction，不明白为什么是这样的提示。
我找到了这个链接https://github.com/coolsnowwolf/lede/issues/1284#issuecomment-492747568  ，不过看不明白。

**Comment by kuoruan** [comment]
你直接下 https://github.com/v2ray/v2ray-core/releases 的 arm 版本也不行吗？

**Comment by tinyhugh** [comment]
> 你直接下 https://github.com/v2ray/v2ray-core/releases 的 arm 版本也不行吗？

是的，我在查找这个问题的时候好像看到有人反映这个问题，v2ray-core的作者也给予了回复。

**Comment by kslr** [comment]
Try 4.22.0

**Comment by kuoruan** [comment]
官方的版本应该已经修复了，下 armv6 试试

**Comment by tinyhugh** [comment]
> 官方的版本应该已经修复了，下 armv6 试试

最新版4.22.1arm版本armv6依然不可用，因为没有v6版本的v2ctl文件，所以另外两个v2ctl文件我都尝试了，依然不可用。
