### ISSUE TITLE
一开启UDP代理，DNS就失效

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/luci-app-v2ray#73]
如题。无法解析任何网站。在路由器上nslookup，找不到DNS server 。关闭UDP代理则一切正常。
 错误日志中，关键信息是：
v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mysite:2053/mypath/):  > dial tcp: lookup mysite on 127.0.0.1:53: read udp 127.0.0.1:53034->127.0.0.1:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket 

贴一下自动生成的配置文件中的相关部分：
	"dns": {
		"servers": [
			"8.8.8.8",
			{
				"address": "1.1.1.1",
				"port": 53
			},
			{
				"address": "119.29.29.29",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"dokodemo-door"
				],
				"outboundTag": "dns_out"
			},
		...........
	},
	"inbounds": [
		........
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"tag": "dokodemo_door",
                         "streamSettings": {
                               "sockopt": {
                               "tproxy": "tproxy"
                             }
                           },
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"settings": {
				"followRedirect": true,
				"network": "tcp,udp"
			}
		}
	],
	"outbounds": [
		..............
		{
			"sendThrough": "0.0.0.0",
			"protocol": "dns",
			"tag": "dns_out",
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}

防火墙， iptables -S  -t mangle 的输出：
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N V2RAY
-N V2RAY_MARK
-A PREROUTING -p udp -j V2RAY
-A FORWARD -o pppoe-wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A OUTPUT -p udp -j V2RAY_MARK
-A V2RAY -p udp -m mark --mark 0xff -j RETURN
-A V2RAY -p udp -j TPROXY --on-port 1081 --on-ip 0.0.0.0 --tproxy-mark 0x1/0x1
-A V2RAY_MARK -p udp -m mark --mark 0xff -j RETURN
-A V2RAY_MARK -p udp -j MARK --set-xmark 0x1/0xffffffff

我水平太低，实在是找不出问题在哪里。只好请教了。

**Comment by popofthedead** [comment]
second this, having the same issue.

**Comment by dalton-chiou** [comment]
需要在任意门中使用tproxy。

**Comment by popofthedead** [comment]
"streamSettings": {
"sockopt": {
"tproxy": "tproxy"
}  这里已经申明了。还是说有其他的tproxy？
