### ISSUE TITLE
安装过程和dnsmasq冲突

### ISSUE THREAD

**Issue by kafire** [kuoruan/luci-app-v2ray#74]
Installing dnsmasq-full (2.80-1.4) to root...
Downloading http://downloads.openwrt.org/releases/18.06.5/packages/mipsel_24kc/base/dnsmasq-full_2.80-1.4_mipsel_24kc.ipk
Configuring kmod-nfnetlink.
Configuring kmod-ipt-tproxy.
Configuring libmnl.
Configuring libgmp.
Configuring libnettle.
Configuring resolveip.
Configuring libnfnetlink.
Configuring kmod-nf-conntrack-netlink.
Configuring libnetfilter-conntrack.
Configuring kmod-ipt-ipset.
Configuring libipset.
Configuring ipset.
Configuring iptables-mod-tproxy.
Configuring ip-tiny.
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-v2ray.

**Comment by Naturalforce** [comment]
卸载dnsmasq就行了 他会直接安装dnsmasq-full

**Comment by kafire** [comment]
卸载以后，还是有一个错误，关于DHCP的
root@OpenWrt:~# opkg install luci-app-v2ray_*.ipk
Installing luci-app-v2ray (1.4.3-1) to root...
Installing dnsmasq-full (2.80-1.4) to root...
Downloading http://downloads.openwrt.org/releases/18.06.5/packages/mipsel_24kc/base/dnsmasq-full_2.80-1.4_mipsel_24kc.ipk
Configuring dnsmasq-full.
udhcpc: started, v1.28.4
udhcpc: sending discover
udhcpc: no lease, failing
Configuring luci-app-v2ray.
[info] Transparent proxy disabled.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc/config/dhcp-opkg.

**Comment by Naturalforce** [comment]
这个无所谓 显示的是之前配置文件还存在 会用新文件替换 已经安装成功了
