### ISSUE TITLE
vnext in outbound 

### ISSUE THREAD

**Issue by carmineyiu** [kuoruan/luci-app-v2ray#78]
在 Luci Config V2Ray 客户端： 
在 outbounds - setting 加了 “vnext", 在 About 内 没有显示。
e.g. 加 protocol vmess, setting 内加以下：
"vnext":   {      
 "port": 443,
}

Save and Applied 后， 在About
    "settings": {	

		}, 
vnext 的 statement 没有加进去。 
是不是 Luci 只支持 服务器端？

**Comment by kuoruan** [comment]
都支持，不管是客户端还是服务端

**Comment by carmineyiu** [comment]
我是想加settings 内的 vnext: 句子 到outbound - setting , 加了(拷贝vnext:整段）后，在About 内没有显示，有没有地方看到Log error?
"outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "v2ray.testing.com",
            "port": 443,
            "users": [
              {
                "id": "uuid....",
                "alterId": 64
              }
            ]
          }
        ]
      },

**Comment by kuoruan** [comment]
settings 必须是个 json 对象

**Comment by carmineyiu** [comment]
https://www.v2ray.com/chapter_02/protocols/vmess.html,
vnext 是标准的outbound object, 在 luci-app-v2ray 哪里能加进vnext? 有没有标准的案例能了解如何用luci-app-v2ray?

**Comment by kuoruan** [comment]
json 对象：
```
{
  "vnext": {
  }
}
```

**Comment by carmineyiu** [comment]
谢谢。
outbound setting 内: 
{
				"vnext": [
					{
						"address": "v2ray.myserver.com",
						"port": 443,
						"users": [
							{
								"id": "uuid.....",
								"alterId": 64
							}
						]
					}
				]
			},
