### ISSUE TITLE
恢复 inbound dokodemo-door

### ISSUE THREAD

**Issue by carmineyiu** [kuoruan/luci-app-v2ray#79]
以前测试是删掉inbound/outbound 的sample. “reset" 重装Luci-app-v2ray 也没有找回来。
主要是 看到 route dns-out, 没有找到对应的 客户端 inbound/outbound 的例子。
（ "type": "field",
	"port": "53",
	"network": "udp",
	"inboundTag": [
	"dokodemo_door"
	],
	"outboundTag": "dns_out"
}

看到 https://steemit.com/cn/@v2ray/dns 内的 inbound 是 指向 1.1.1.1 . 在DNS 内也有 1.1.1.1 的设置。 
没有找到tls 相关的设置？
我的V2ray 服务端已有tls+ws, 能找 1.1.1.1 换成自己的 Server?  
在DNS setting 内加 自己的 server? (加 iptable route udp?)

**Comment by kuoruan** [comment]
现在的配置放在 /etc/v2ray 下的 json 文件中，由于是单独处理的，所以不能恢复。
另外就是自带的配置不全，需要其他配置需要自行添加
