### ISSUE TITLE
modify Settings may not trigger a restart of service

### ISSUE THREAD

**Issue by rny** [kuoruan/luci-app-v2ray#8]
V2Ray - Edit Outbound

modify Settings

save & apply

it prompt:

```
There are no changes to apply.
```

not sure v2ray is restarted or not.

**Comment by kuoruan** [comment]
The changes to settings and stream settings will write to external files, and can't be monitored by LuCI.
You can open about page to see if the config file changes.

**Comment by kuoruan** [comment]
The files are in /etc/v2ray

https://github.com/kuoruan/luci-app-v2ray/tree/master/root/etc/v2ray
