### ISSUE TITLE
DNS proxy not working

### ISSUE THREAD

**Issue by Tualua** [kuoruan/luci-app-v2ray#80]
Hello! 
Setup fresh openwrt 19.07.0-rc2. Latest v2ray and luci-app
Added configuration for upstream_vmess
TCP transparent proxy is working fine. I can open Google and Youtube. 
Enabled DNS transparent proxy - still all DNS queries goes to DNS server supplied by DHCP server on WAN interface.

Could anybody point me to my mistake?

Autogenerated config

    {
    	"log": {
    		"access": "/dev/null",
    		"loglevel": "warning",
    		"error": "/var/log/v2ray-error.log"
    	},
    	"dns": {
    		"hosts": {
    			"example.com": "127.0.0.1"
    		},
    		"servers": [
    			"8.8.8.8",
    			{
    				"address": "208.67.222.222",
    				"port": 5353
    			},
    			{
    				"address": "114.114.114.114",
    				"port": 53,
    				"domains": [
    					"geosite:cn"
    				]
    			}
    		]
    	},
    	"routing": {
    		"domainStrategy": "IPIfNonMatch",
    		"rules": [
    			{
    				"type": "field",
    				"ip": [
    					"geoip:private",
    					"geoip:cn"
    				],
    				"outboundTag": "direct"
    			},
    			{
    				"type": "field",
    				"domain": [
    					"geosite:cn"
    				],
    				"outboundTag": "direct"
    			},
    			{
    				"type": "field",
    				"port": "53",
    				"network": "udp",
    				"inboundTag": [
    					"dokodemo_door"
    				],
    				"outboundTag": "dns_out"
    			}
    		]
    	},
    	"inbounds": [
    		{
    			"listen": "0.0.0.0",
    			"port": 1080,
    			"protocol": "socks",
    			"sniffing": {
    				"enabled": true,
    				"destOverride": [
    					"http",
    					"tls"
    				]
    			},
    			"settings": {
    				"udp": true,
    				"auth": "noauth",
    				"ip": "127.0.0.1"
    			}
    		},
    		{
    			"listen": "0.0.0.0",
    			"port": 1081,
    			"protocol": "dokodemo-door",
    			"tag": "dokodemo_door",
    			"sniffing": {
    				"enabled": true,
    				"destOverride": [
    					"http",
    					"tls"
    				]
    			},
    			"settings": {
    				"followRedirect": true,
    				"network": "tcp,udp"
    			}
    		}
    	],
    	"outbounds": [
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "vmess",
    			"settings": {
    				"vnext": [
    					{
    						"address": "v2ray.server",
    						"port": 443,
    						"users": [
    							{
    								"id": "uuid",
    								"alterId": 64,
    								"security": "auto"
    							}
    						]
    					}
    				],
    				"servers": null,
    				"response": null
    			},
    			"streamSettings": {
    				"network": "ws",
    				"security": "tls",
    				"tlsSettings": {
    					"allowInsecure": false,
    					"serverName": "v2ray.server"
    				},
    				"tcpSettings": null,
    				"kcpSettings": null,
    				"wsSettings": {
    					"connectionReuse": true,
    					"path": "/ray",
    					"headers": {
    						"Host": "v2ray.server"
    					}
    				},
    				"httpSettings": null,
    				"quicSettings": null,
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		},
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "freedom",
    			"tag": "direct",
    			"streamSettings": {
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		},
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "blackhole",
    			"tag": "block",
    			"streamSettings": {
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		},
    		{
    			"sendThrough": "0.0.0.0",
    			"protocol": "dns",
    			"tag": "dns_out",
    			"streamSettings": {
    				"sockopt": {
    					"mark": 255
    				}
    			}
    		}
    	]
    }

**Comment by kuoruan** [comment]
Try 1.5.1-1 and later
