### ISSUE TITLE
出站连接socks协议的服务器地址无法保存

### ISSUE THREAD

**Issue by kkjorker** [kuoruan/luci-app-v2ray#85]
版本:
luci-app-v2ray ( 1.5.0-2 )
v2ray-core ( 4.22.1-1 )

问题: 
通过Luci新增socks协议的出站连接,填上服务器地址和端口后,其余保持默认,保存并应用后查看配置文件,出站连接中socks协议中服务器地址的值为空 "address": "",

出站连接中socks协议配置:
{
	"sendThrough": "0.0.0.0",
	"protocol": "socks",
	"settings": {
		"servers" [
			{
				"address": "",
				"port": 1080,
				"users": [
					{
						"user": "",
						"pass": ""
					}
				]
			}
		]
	},
	"streamSettings": {
		"sockopt": {
			"mark": 255
		}
	}
}

**Comment by kuoruan** [comment]
已在 b777d9d8dae9f789dcbebbef6fa0190c92fdf523 修复
