### ISSUE TITLE
请教两个小问题

### ISSUE THREAD

**Issue by dalton-chiou** [kuoruan/luci-app-v2ray#86]
1，freedom出站，域名策略不论是留空、填写AsIs，或useip之类，生成的配置文件中都是一样的留空。这是有意设计的吗？
2，透明代理gfwlist方式，“代理列表DNS” 留空，生成的dnsmasq表中没有server=/site/dns 这一项。但这样也正确解析并生成ipset。这是怎么实现的呢？（我猜测是使用了v2ray的内置DNS，就是不知道怎么发过去的。没有设置任何DNS劫持。系统DNS是国内的。）

**Comment by kuoruan** [comment]
server 没设置的话会使用 dnsmasq 默认的上级 DNS 解析，
dnsmasq 发出的解析请求会被 iptables 重定向到 v2ray 再发出

**Comment by dalton-chiou** [comment]
> dnsmasq 发出的解析请求会被 iptables 重定向到 v2ray 再发出
就是这里不清楚。因为我iptables里转发至v2ray的只有nat表的一项：
-A V2RAY -p tcp -m set --match-set v2ray_dst_proxy_v4 dst -j REDIRECT --to-ports 1081
重定向是在哪里发生的呢？
当前设置是，v2ray只启用一个任意门入站，一个vmess出站。没开启DNS，没开路由。透明代理那里没有代理UDP或DNS；“代理列表DNS”，为8.8.8.8#53 。
比如：
server=/wireguard.com/8.8.8.8#53
ipset=/wireguard.com/v2ray_dst_proxy_v4
Dnsmasq向8.8.8.8发出解析wireguard的请求，这一请求是怎么走到远端的v2ray服务器的？

**Comment by dalton-chiou** [comment]
> server 没设置的话会使用 dnsmasq 默认的上级 DNS 解析，
> dnsmasq 发出的解析请求会被 iptables 重定向到 v2ray 再发出

当前设置是，v2ray只启用一个任意门入站，一个vmess出站。没开启DNS，没开路由。透明代理那里没有代理UDP或DNS ，只是gfwlist方式。
iptables里转发至v2ray的只有nat表的一项：
-A V2RAY -p tcp -m set --match-set v2ray_dst_proxy_v4 dst -j REDIRECT --to-ports 1081
重定向是在哪里发生的呢？
比如：
server=/wireguard.com/8.8.8.8#53
ipset=/wireguard.com/v2ray_dst_proxy_v4
Dnsmasq向8.8.8.8发出解析wireguard的请求，这一请求是怎么走到远端的v2ray服务器的？
还有，不填写“代理列表dns",也就是没有server=/wireguard.com/8.8.8.8#53，也能正常解析。而我v2ray没有DNS项。这里也是不明白的地方。

我dig时发现，如果是gfwlist里的网站，只有+tcp才能解析，看来肯定是走了v2ray（因为我没开启UDP）。而dig国内网站，如果不指定dns服务器，出来好几种情况：
~# dig www.jd.com
; <<>> DiG 9.11.14 <<>> www.jd.com
;; global options: +cmd
;; connection timed out; no servers could be reached

而：
# dig www.jd.com +tcp
; <<>> DiG 9.11.14 <<>> www.jd.com +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 50647
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.jd.com.			IN	A

;; Query time: 10 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jan 07 07:19:26 CST 2020
;; MSG SIZE  rcvd: 39

还有更奇怪的：
dig www.jd.com @119.29.29.29
; <<>> DiG 9.11.14 <<>> www.jd.com @119.29.29.29
;; global options: +cmd
;; connection timed out; no servers could be reached

而：
:~# dig www.jd.com @114.114.114.114

; <<>> DiG 9.11.14 <<>> www.jd.com @114.114.114.114
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59605
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59605
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.jd.com.			IN	A

;; ANSWER SECTION:
www.jd.com.		98	IN	CNAME	www.jd.com.gslb.qianxun.com.
www.jd.com.gslb.qianxun.com. 38	IN	CNAME	www.jdcdn.com.
www.jdcdn.com.		38	IN	CNAME	img2x-v6-sched.jcloudedge.com.
img2x-v6-sched.jcloudedge.com. 97 IN	A	61.182.138.3

;; Query time: 9 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Tue Jan 07 07:21:13 CST 2020
;; MSG SIZE  rcvd: 157

——我已经糊涂了。

**Comment by kuoruan** [comment]
访问 wireguard.com 之后，IP 地址有正确添加到 v2ray_dst_proxy_v4 吗？

**Comment by dalton-chiou** [comment]
有。因为它不在gfwlist里，我把它加入了proxylist。

**Comment by kuoruan** [comment]
有的话说明还是走的 dnsmasq 解析的，并没有过 V2Ray

**Comment by kuoruan** [comment]
可以把 V2Ray 的日志打开，看看有没有收到 DNS 请求

**Comment by dalton-chiou** [comment]
比如访问wireguard ,日志debug模式，有如下三条：
2020/01/07 09:55:19 [Info] [577311628] v2ray.com/core/app/dispatcher: default ro
ute for tcp:www.wireguard.com:443
2020/01/07 09:55:19 [Info] [577311628] v2ray.com/core/transport/internet/websock
et: creating connection to tcp:my.site:2053
2020/01/07 09:55:20 [Info] [577311628] v2ray.com/core/proxy/vmess/outbound: tunn
eling request to tcp:www.wireguard.com:443 via tcp:my.site:2053
看不到dns内容。

**Comment by kuoruan** [comment]
那估计就是 sniffing 起作用了吧。
https://toutyrater.github.io/basic/vmess.html#%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by dalton-chiou** [comment]
看了一下服务端的情况。
看来是，v2ray客户端直接把域名发给了服务端，服务端接到请求，使用系统DNS运行了查询。VPS是debian 9,  resolve.conf 头一行是8.8.8.8。在VPS上nslookup ，看到走的是8.8.8.8。
我觉得这样效率还是挺高的。（折腾这些，就是想避免v2ray发生多次或不必要的dns查询影响速度）。谢谢您前面的回答，对我帮助很大。
