### ISSUE TITLE
facebook.com打不开

### ISSUE THREAD

**Issue by sebastianchuk** [kuoruan/luci-app-v2ray#87]
仅发现facebook.com无法访问，手机侧m.facebook.com正常访问。其他谷歌推特等等都没问题。

**Comment by kuoruan** [comment]
信息不足，无法判断问题。
检查一下你的解析是否正常，然后开启 v2ray 的错误日志再定位具体问题

**Comment by sebastianchuk** [comment]
/var/log/v2ray-error.log这个日志吗？没有错误。请教怎么排查？

**Comment by kuoruan** [comment]
把错误日志等级开到 info, 再访问具体网站，会有日志输出

**Comment by sebastianchuk** [comment]
2020/01/09 08:56:25 [Info] [3367290053] v2ray.com/core/app/dispatcher: sniffed domain: facebook.com
2020/01/09 08:56:25 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: metrics.icloud.com. TypeA -> [17.248.129.107 17.248.129.73 17.248.129.168 17.248.129.72 17.248.129.212 17.248.129.77 17.248.129.137 17.248.129.243] 271.279948ms
2020/01/09 08:56:25 [Info] [521372748] v2ray.com/core/app/dispatcher: default route for tcp:metrics.icloud.com:443
2020/01/09 08:56:25 [Info] [521372748] v2ray.com/core/common/mux: dispatching request to tcp:metrics.icloud.com:443
2020/01/09 08:56:25 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: metrics.icloud.com. TypeAAAA -> [[2620:149:a43:102::5] [2620:149:a43:101::5] [2620:149:a43:103::6] [2620:149:a43:103::5] [2620:149:a43:104::8] [2620:149:a43:105::7] [2620:149:a43:106::c] [2620:149:a43:109::5]] 272.231819ms
2020/01/09 08:56:25 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: facebook.com. TypeA -> [157.240.11.35] 243.479404ms
2020/01/09 08:56:25 [Info] [3367290053] v2ray.com/core/app/dispatcher: default route for tcp:facebook.com:443
2020/01/09 08:56:25 [Info] [3367290053] v2ray.com/core/common/mux: dispatching request to tcp:facebook.com:443
2020/01/09 08:56:25 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: facebook.com. TypeAAAA -> [[2a03:2880:f10d:183:face:b00c:0:25de]] 243.746504ms

**Comment by sebastianchuk** [comment]
2020/01/09 08:56:25 [Info] [3367290053] v2ray.com/core/app/dispatcher: sniffed domain: facebook.com
2020/01/09 08:56:25 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: facebook.com. TypeA -> [157.240.11.35] 243.479404ms
2020/01/09 08:56:25 [Info] [3367290053] v2ray.com/core/app/dispatcher: default route for tcp:facebook.com:443
2020/01/09 08:56:25 [Info] [3367290053] v2ray.com/core/common/mux: dispatching request to tcp:facebook.com:443
2020/01/09 08:56:25 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: facebook.com. TypeAAAA -> [[2a03:2880:f10d:183:face:b00c:0:25de]] 243.746504ms

**Comment by kuoruan** [comment]
这里的日志没有问题，你的配置文件贴出来看看，还有透明代理页

**Comment by sebastianchuk** [comment]
{
	"log": {
		"access": "\/dev\/null",
		"loglevel": "info",
		"error": "\/var\/log\/v2ray-error.log"
	},
	"dns": {
		"servers": [
			"8.8.8.8",
			{
				"address": "8.8.8.8",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"protocol": [
					"bittorrent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "dns_out"
			}
		]
	},
	"inbounds": [
		{
			"port": 1081,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "tproxy"
				}
			},
			"tag": "transparent",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "mydomain.com",
						"port": 443,
						"users": [
							{
								"id": "xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxxx",
								"alterId": 64
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"tlsSettings": {
					"serverName": "mydomain.com",
					"allowInsecure": false,
					"allowInsecureCiphers": false,
					"disableSystemRoot": false,
					"certificates": [
						
					]
				},
				"wsSettings": {
					"path": "\/mypath"
				},
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "proxy",
			"mux": {
				"enabled": true,
				"concurrency": 8
			}
		},
		{
			"protocol": "freedom",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "block"
		},
		{
			"protocol": "dns",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "dns_out"
		}
	]
}

**Comment by sebastianchuk** [comment]
![image](https://user-images.githubusercontent.com/40374240/72057702-6292e780-3301-11ea-9d4d-28141e9a8c94.png)

**Comment by sebastianchuk** [comment]
![image](https://user-images.githubusercontent.com/40374240/72057788-8c4c0e80-3301-11ea-91c5-d96a08a2f00d.png)

**Comment by kuoruan** [comment]
添加一条路由规则，让 8.8.8.8 走代理

**Comment by sebastianchuk** [comment]
![image](https://user-images.githubusercontent.com/40374240/72058667-0e890280-3303-11ea-826a-2a562c219225.png)
![image](https://user-images.githubusercontent.com/40374240/72058701-1c3e8800-3303-11ea-958a-8ecfa4662081.png)

也试过这样，但是没用，还是访问不了facebook.com

**Comment by sebastianchuk** [comment]
以前电信宽带是可以上facebook的，但是移动宽带不行。

**Comment by kuoruan** [comment]
你本机的 dns 填的什么？
另外你的 任意门 没有设置接收 udp，导致你的 dns routing 根本没起作用

**Comment by kuoruan** [comment]
默认情况下，你不代理 dns 流量的话，设置了 sniffing 之后，会自动尝试解决 dns 污染的问题，
你这个应该是 dns 还是被污染了

**Comment by sebastianchuk** [comment]
![image](https://user-images.githubusercontent.com/40374240/72119669-c06a1280-3387-11ea-8063-2a98c1d97106.png)
![image](https://user-images.githubusercontent.com/40374240/72119672-c3fd9980-3387-11ea-9fe5-168cad30876b.png)
![image](https://user-images.githubusercontent.com/40374240/72119682-c9f37a80-3387-11ea-8a19-e17099be0478.png)
一样的症状，没有改变。

**Comment by kuoruan** [comment]
倒是把 dns 代理钩上啊，然后本机的 dns 设置为你的网关。
