### ISSUE TITLE
出站连接socks协议的用户认证问题

### ISSUE THREAD

**Issue by kkjorker** [kuoruan/luci-app-v2ray#88]
版本:
luci-app-v2ray ( 1.5.2-1 )
v2ray-core ( 4.22.1-1 )

问题:
在出站连接中socks协议的"用户"和"密码"为空的话,配置文件中会默认添加了"users" : [ {"user": "", "pass": ""} ],如果v2ray服务器端的socks入站没有开启用户认证会导致连接不上,目前只能把服务器端的socks入站开启了用户认证才能正常连接,可否考虑如果"用户"和"密码"的值为空时,配置文件中出站的socks默认没有"users"项?

v2ray服務器log的输出如下"v2ray.com/core/proxy/socks: no matching auth method"

**Comment by kuoruan** [comment]
fixed.
