### ISSUE TITLE
v2ray文件路径

### ISSUE THREAD

**Issue by shikkoku** [kuoruan/luci-app-v2ray#9]
若是安装ipk版本v2ray 则文件路径为
/usr/bin/v2ray/v2ray

**Comment by kuoruan** [comment]
路径根据自己的需要自行设置，如果你使用的是我的 ipk 的话，默认安装位置就是 /usr/bin/v2ray

**Comment by kuoruan** [comment]
不可能啊，我的都是安装到了 /usr/bin 下的
https://github.com/kuoruan/openwrt-v2ray/blob/9753ab69c009f46562c20716c9314bb29514e859/Makefile#L266

**Comment by shikkoku** [comment]
> 不可能啊，我的都是安装到了 /usr/bin 下的
> https://github.com/kuoruan/openwrt-v2ray/blob/9753ab69c009f46562c20716c9314bb29514e859/Makefile#L266

我安装后文件是/usr/bin里有个v2ray的文件夹，v2ray的文件夹里面有个v2ray文件……

**Comment by kuoruan** [comment]
那你估计不是装的我的 ipk

**Comment by ttimasdf** [comment]
你用的官方的安装脚本？那可太强了…不拿upx压一下，路由器rom根本塞不下原版……
