### ISSUE TITLE
默认配置下的路由器安全问题

### ISSUE THREAD

**Issue by StoneMoe** [kuoruan/luci-app-v2ray#90]
默认配置下，socks_proxy 以及 dokodemo_door 监听在0.0.0.0下，且没有密码验证。

这对于面向公网的路由器是较大的安全隐患。

且在尝试过程中发现透明代理功能似乎依赖 dokodemo_door 监听在 0.0.0.0 下，可以考虑增加防火墙规则屏蔽来自INPUT链的请求。

**Comment by kuoruan** [comment]
默认情况下，OpenWrt 已有防火墙规则 REJECT WAN 的 INPUT
不知道你指的是哪种情况？

**Comment by StoneMoe** [comment]
这边指的是忽略路由器本身的防火墙策略的情况，看您判断了。

**Comment by kuoruan** [comment]
Won't fix
