### ISSUE TITLE
透明代理的TProxy选项会导致入站流量被错误路由

### ISSUE THREAD

**Issue by StoneMoe** [kuoruan/luci-app-v2ray#91]
可能的相关Issue：https://github.com/kuoruan/luci-app-v2ray/issues/39

当开启透明代理中的TProxy选项时，从wan zone访问路由器本身提供的服务以及路由器通过SNAT&DNAT做的端口映射都会失效。

初步排查可能是因为 OUTPUT 链中 V2RAY_MASK 无脑打了 0x1 造成的，但不太确定。

**Comment by StoneMoe** [comment]
附 flow diagram一张：
https://upload.wikimedia.org/wikipedia/commons/3/37/Netfilter-packet-flow.svg

**Comment by kuoruan** [comment]
也就是说不使用 TProxy 添加 iptables 时能正常访问吗？
另外，社区的 TProxy 代理网关流量时都是无脑 set-mark 1
本人能力有限，不知道有没有其他方法能正常代理。

https://guide.v2fly.org/app/tproxy.html#%E9%85%8D%E7%BD%AE%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E8%A7%84%E5%88%99

**Comment by StoneMoe** [comment]
> 也就是说不使用 TProxy 添加 iptables 时能正常访问吗？
> 另外，社区的 TProxy 代理网关流量时都是无脑 set-mark 1
> 本人能力有限，不知道有没有其他方法能正常代理。
> 
> https://guide.v2fly.org/app/tproxy.html#%E9%85%8D%E7%BD%AE%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E8%A7%84%E5%88%99

经过多种选项组合测试发现确实是TProxy选项引起的问题，包括不勾选TProxy但勾选代理DNS流量（即使也是使用TProxy去转发53端口）时也不会出现问题。

晚些时候我会再做更进一步的测试

**Comment by csquya** [comment]
> 也就是说不使用 TProxy 添加 iptables 时能正常访问吗？
> 另外，社区的 TProxy 代理网关流量时都是无脑 set-mark 1
> 本人能力有限，不知道有没有其他方法能正常代理。
> 
> https://guide.v2fly.org/app/tproxy.html#%E9%85%8D%E7%BD%AE%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E8%A7%84%E5%88%99

也许解决了TProxy问题，也就解决了我的 #83 问题， 因为目前的redirect不支持ipv6透明代理。

**Comment by StoneMoe** [comment]
研究了一下：
1. OpenWRT的Port forwarding实现在NAT table 的prerouting和postrouting链上，而TProxy启用下的v2ray相关规则实现在mangle下，导致v2ray的规则拦截了端口转发的规则

```
只能把Port forwarding功能的实现改到mangle来解决这个问题，但这显然太dirty了
```

2. 路由器本身提供的服务无法正常访问（如网关上提供了一个VPN Server via TCP）

```
TProxy和REDIRECT模式下，显然都把出站的包交给v2ray处理了，但是TProxy却无法正常工作，这个可能跟TProxy和REDIRECT的具体实现差异有关，这方面暂时还没有深入地看。
```

**Comment by StoneMoe** [comment]
最后我针对自己使用场景的解决办法是，手动裁剪掉了代理路由器本身的功能，仅使用redirect，因为这一部分的防火墙规则侵入性太强了。

**Comment by ToutyRater** [comment]
添加一个 dokodemo 和 freedom，dokodemo 监听 wan 和设定转发的 ip:port，freedom 指定 sendThought 为 lan，通过 routing 将 dokodemo 和 freddom 连起来。这种方法应该可以

**Comment by fo2w** [comment]
> 添加一个 dokodemo 和 freedom，dokodemo 监听 wan 和设定转发的 ip:port，freedom 指定 sendThought 为 lan，通过 routing 将 dokodemo 和 freddom 连起来。这种方法应该可以

这个方案真的可以么, 还挺感兴趣的

**Comment by ToutyRater** [comment]
> 
> 
> > 添加一个 dokodemo 和 freedom，dokodemo 监听 wan 和设定转发的 ip:port，freedom 指定 sendThought 为 lan，通过 routing 将 dokodemo 和 freddom 连起来。这种方法应该可以
> 
> 这个方案真的可以么, 还挺感兴趣的

这个方法相当于绕过了使用 V2Ray 绕过了 NAT，dokodemo 本质就是一种端口转发，应该是可以，但我没实际使用过。
