### ISSUE TITLE
请教这个软件我还需要手动设置iptable么？

### ISSUE THREAD

**Issue by littlesum** [kuoruan/luci-app-v2ray#92]
有两个问题请教：
1# 在luci界面配置好以后我还需要手动配置iptables的转发规则么？

2# 后续可以做到自己读取json到luci配置界面吗？用自定义配置文件，luci无法读取啊？

**Comment by kuoruan** [comment]
1. 会自动配置好
2.  已经自定义配置文件了，就没必要加载到 LuCI

**Comment by littlesum** [comment]
我这是个二级路由 旁路由 这个自动规则咋不行！水平有限 搞不明白是什么问题！curl 测试socks5 没问题，但是没发过透明代理！

**Comment by kuoruan** [comment]
请给配置，透明代理页截图和防火墙规则列表。
不要无意义的说不行。
