### ISSUE TITLE
Dokodemo-door - Network udp never work

### ISSUE THREAD

**Issue by tritu** [kuoruan/luci-app-v2ray#94]
The udp option in Dokodemo-door can never be converted to JSON file even it's ticked. The JSON file sill shows tcp only.
"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp"
			},

**Comment by kuoruan** [comment]
Your luci version?

**Comment by tritu** [comment]
luciversion = "git-20.013.52473-5ce29c8".
Here is how I reproduce this error.
1. everything is in default setting, tick the udp in dokodemo_door under Inbound tab, save & apply, the udp is shown in JSON, looks good.
2. in Transparent Proxy tab, choose "Redirect port" to docodemo_door -1081, save & apply, the udp is gone in JSON.

**Comment by kuoruan** [comment]
As LuCI shows, dokodemo_door's Network option is ignored when transparent proxy set on it's port.

https://github.com/kuoruan/luci-app-v2ray/blob/bb9bc4e8fda057621d8b08e31a7bda1868dbbb83/luasrc/model/cbi/v2ray/inbound-detail.lua#L69-L73

**Comment by tritu** [comment]
Yes u r right. Close it now.
