### ISSUE TITLE
initial config

### ISSUE THREAD

**Issue by carmineyiu** [kuoruan/luci-app-v2ray#95]
用了LUCI 一段时间，感觉非常方便。因为测试中不停的reset config,有没有方法能 启动是加入 initial ws +tls 客户端 parameter?  例如 ：VMess - Address， VMess - Port，VMess - User ID，TLS - Server name， WebSocket - Path.

**Comment by kuoruan** [comment]
没明白你的具体意思，是想要添加默认配置吗？
修改之后把 ```/etc/config/v2ray``` 保存下来，reset 之后恢复文件即可

**Comment by carmineyiu** [comment]
因为要 继续尝试try and error，所以恢复 LUCI 页面内的 上1/2/3次的配置。那不用每次重新开始配置。

**Comment by kuoruan** [comment]
LuCI 官方不支持。

**Comment by carmineyiu** [comment]
那能读 initial file， 将 Vmess/Websocket 的数据加入。不用每次重新填写。

**Comment by kuoruan** [comment]
用导入功能，或者备份 ```/etc/config/v2ray```
