### ISSUE TITLE
Is it possible to forward all UDP traffic except DNS requests?

### ISSUE THREAD

**Issue by maddie** [kuoruan/luci-app-v2ray#97]
The scenario is as follows:

I have IPv6 addresses across my devices, thus I have IPv6 network access. However, some websites (read Facebook) cannot be accessed via IPv6, and the forwarded DNS requests return IPv6 addresses that is not accessible. When I was using Shadowsocks, I used to mark the related address as non IPv6 routable in my dnsmasq config, however, it won't work this way now since all UDP traffic is being redirected to V2Ray.

**Comment by kuoruan** [comment]
Not support now.
You can try add some dns rules in dns tab for Facebook.
